### ISSUE TITLE
suggestion: option to select either topic now playing or game nowplaying

### ISSUE THREAD

**Issue by Disputes** [jagrosh/MusicBot#10]
could we get an option to toggle between the song showing in the channel topic or the bots playing (game)

would be good for servers that have multiple bots for users to select from

http://prntscr.com/earlfi might explain it a bit better

**Comment by jagrosh** [comment]
This is a planned possibility for music bots that are only connected to 1 server. For bots on more than one server it will not be possible because it is very confusing for the servers that aren't playing music.

**Comment by TheLameCompany** [comment]
My bot is connected to my test server, which i am currently only in and my other server which is for the music bot (it isnt public) its only for the server

**Comment by jagrosh** [comment]
This is now possible, although it will only show the song in the game as long as it is only playing music on 1 server (it can still be _connected_ to multiple, but can only be playing on one)
