### ISSUE TITLE
[Feature Request] Check if the bot is already online, before starting a new instance

### ISSUE THREAD

**Issue by TheGreenPig** [jagrosh/MusicBot#1002]
### Is your feature request related to a problem? Please describe.

If you run the jar file multiple times, the bot has some very weird behaviour. It sends every message multiple times, playback doesn't work etc. so why not (if possible) check if the bot is already online before the start up to prevent this from happening.

### What is your ideal solution to the problem?

If the user runs the jar file even though the bot is online, send a message in the console like "Bot already online" and stop with the start-up process. Maybe add a setting in the config file to turn this feature off as well, but I would turn it on by default.

### How would this feature be used?

1. Run the jar file multiple times
2. The first instance works expected and normally
3. The other ones send an info message and then stop with the start-up process

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
Discord's API does not allow you to detect if the bot is already online.

**Comment by jagrosh** [comment]
Some people intentionally run multiple instances of JMusicBot on the same machine, and I guess I'm not sure why you can't just check if you have it running?

**Comment by TheGreenPig** [comment]
🤷🏼‍♂️I just thought it would at least be helpful to tell the user that problems can occur when you run the bot multiple times on the same token...

**Comment by MichailiK** [comment]
There is no mechanism in JMusicBot to do IPC with other JMusicBot instances to check if they run on the same token, that is too complex & not worth the effort. And since there are legitimate use cases of running the bot multiple times, there will be no restrictions put in place to avoid multiple instances..
