### ISSUE TITLE
[Feature Request] Leave VC when sharing the channel with only bots

### ISSUE THREAD

**Issue by MaikKrisanov** [jagrosh/MusicBot#1029]
### Is your feature request related to a problem? Please describe.

When using two separate instances of the music bots (or other bots) and then leaving the Voice Channel, the bots do not automatically leave the channel.

### What is your ideal solution to the problem?

When the bot shares the channel only with other bots, it leaves the channel. 

### How would this feature be used?

1. Have the bot join a voice channel.
2. Have a different, unrelated bot join the voice channel.
3. Leave the voice channel.
4. MusicBot is now expected to leave the voice channel after a certain amount of time.

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
This is already what the `alonetimeuntilstop` field in the [config](https://jmusicbot.com/config/) is for. Bots and users that are deafened do not count as "listening", and therefore don't count against the bot considering itself "alone."

**Comment by jagrosh** [comment]
https://github.com/jagrosh/MusicBot/blob/master/src/main/java/com/jagrosh/jmusicbot/audio/AloneInVoiceHandler.java#L90-L97
