### ISSUE TITLE
[Feature Request] Auto join channel for guilds that have setup auto-summon-channel in their guild settings

### ISSUE THREAD

**Issue by victoryy2003** [jagrosh/MusicBot#1044]
### Is your feature request related to a problem? Please describe.

After restarted the bot, I had to self command the bot to let it joins every guilds voice channels and playback the playlist

### What is your ideal solution to the problem?

Add a new section of `auto-summon-voice-channel-id` into `serversettings.json`
Add a new section of `enable-auto-summon` into `serversettings.json`
Bot will read the `serversettings.json` file at startup and joins the channels and plays `default-playlist` if existed

### How would this feature be used?

After restarting the bot, it can **automatically join** to those **`voice channels`** and **play `default-playlist`** based on their guild settings

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
[Auto playlists](https://jmusicbot.com/commands/#autoplaylist-playlistname) already exists. Use the `autoplaylist` command on each server you want the bot to play a playlist on on start up.

**Comment by victoryy2003** [comment]
> [Auto playlist](https://jmusicbot.com/commands/#autoplaylist-playlistname) already exists. Use the `autoplaylist` command on each server you want the bot to play a playlist on on start up.

Nah, my main idea is to let the bot automatically joins the voice channel after start up
