### ISSUE TITLE
[Feature Request] Read config from HTTP request

### ISSUE THREAD

**Issue by hypnguyen1209** [jagrosh/MusicBot#1061]
### Is your feature request related to a problem? Please describe.

when I use heroku to deploy, JmusicBot can't read the file on the storage, so why can't we let it read the config from a certain url for example.

### What is your ideal solution to the problem?

Specify a different config file:
java -Dconfig=https://example.com/config.txt -jar JMusicBot.jar

I think it's a good idea

### How would this feature be used?

java -Dconfig=https://example.com/config.txt -jar JMusicBot.jar

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
Heroku is not supported.
