### ISSUE TITLE
[Feature Request] possibility to remove the bot as a bot owner from the server on which you have no rights

### ISSUE THREAD

**Issue by schnorbi** [jagrosh/MusicBot#1063]
### Is your feature request related to a problem? Please describe.

If I have no permissons on a Discord-Server I have no chance to remove the bot from the server "I think".

### What is your ideal solution to the problem?

Add a feature so the Bot-Owner can remove the Bot from a Server where he has no permissions.

### How would this feature be used?

1. Use for example the command $serverleave in combination with the ID of the Server
2. The Bot leaves the Server

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
https://jmusicbot.com/advanced-eval/
