### ISSUE TITLE
Can't play mp3s

### ISSUE THREAD

**Issue by baby-Mario** [jagrosh/MusicBot#1066]
### Bug Description

Whenever I try and play mp3s the bot says
🚫 Error loading: Unknown file format. 

### Steps to Reproduce

Prefix p mp3 file

### Expected Result

I expected for the mp3 to play

### Debug Output

```shell
[20:35:00] [WARN] [NativeResourceHolder]: Should have been closed before finalization (com.sedmelluq.discord.lavaplayer.natives.mp3.Mp3Decoder).
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by yo-louk** [comment]
I'm not sure I understand the steps to reproduce. Maybe you could send a screenshot of the command being executed?

**Comment by MichailiK** [comment]
Could you send a sample of the mp3 file you're trying to play?

**Comment by MichailiK** [comment]
Assuming this issue is resolved/stale. If not, please upload a sample of audio you have trouble playing.
