### ISSUE TITLE
Default volume is too damn high

### ISSUE THREAD

**Issue by khionu** [jagrosh/MusicBot#107]
100% is default, but it's FAR too high. 50% sounds the same as 100%, and I found it comfortable at 7%. I'd recommend rescaling it.

**Comment by jagrosh** [comment]
The current default (100) exists because it is uses far fewer resources to run the bot at 100 volume than changing it. However, I've added setting the default volume via the config file to the [suggested features list](https://github.com/jagrosh/MusicBot/projects/1)
