### ISSUE TITLE
[Feature Request] Desktop version

### ISSUE THREAD

**Issue by rubenh2905** [jagrosh/MusicBot#1078]
### Is your feature request related to a problem? Please describe.

all bots need to be deploy some where with kinda good network and hardware.

### What is your ideal solution to the problem?

maybe a desktop version like "VlC media player" or "KMPlayer"

### How would this feature be used?

dont need to be deploy any where or connect it to discord

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
You can open YouTube or SoundCloud in your web browser.
