### ISSUE TITLE
Player no longer plays Twitch streams

### ISSUE THREAD

**Issue by PSI-Nightshade** [jagrosh/MusicBot#108]
lavaplayer recently fixed an issue where Twitch streams were no longer playable by lavaplayer (apparently caused when Twitch switched to go.twitch.tv URLs). The MusicBot would need to update its lavaplayer libraries to benefit from the fix as it is currently unable to play Twitch streams.

Thank you.

**Comment by jagrosh** [comment]
This will be fixed with the next release, which should be within the week

**Comment by jagrosh** [comment]
This should be fixed as of `0.1.1`

**Comment by PSI-Nightshade** [comment]
I confirm that it works. Thank you!
