### ISSUE TITLE
[Feature Request] Randomise Autoplaylist

### ISSUE THREAD

**Issue by DataGecko** [jagrosh/MusicBot#1085]
### Is your feature request related to a problem? Please describe.

The autoplaylist always plays tracks in order, there is no option to randomise the track selection.

### What is your ideal solution to the problem?

Add an owner setting to set the autoplaylist to randomise track selection.

### How would this feature be used?

Using the bot in a radio style mode it would allow tracks to be played randomly from the autoplaylist so as to keep the music interesting.
The advanced version of this would play each track from the playlist only once before repeating.

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
You can include `#shuffle` or `//shuffle` within the playlist for it to always shuffle when loaded.

**Comment by DataGecko** [comment]
Awesome, thank you so much for that. Perfect!!!
