### ISSUE TITLE
[Feature Request] Allow whitelisting servers

### ISSUE THREAD

**Issue by e00E** [jagrosh/MusicBot#1086]
### Is your feature request related to a problem? Please describe.

I want my self hosted instance to only join a select few servers. Using the normal link to add bot to server anyone could add the bot to their server which I don't want.
I am aware that the discord developer portal allows you to make a bot private. This is not the same thing as it makes the bot only invitable by me. But I want other people to invite the bot to their servers (on which I am not an admin) and whitelist those servers.

### What is your ideal solution to the problem?

A configuration option to whitelist a list of servers.

### How would this feature be used?

.

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
This is so extremely niche, and also unnecessary once the bot is on those servers. If you have a list of servers you want the bot on, and you don't have perms, just temporarily make the bot public and let those servers add it. If someone maliciously added it to a server while it was public, you can just have it leave once it is private again.
