### ISSUE TITLE
Suggestion: remember settings

### ISSUE THREAD

**Issue by Waester** [jagrosh/MusicBot#11]
An idea would be to make commands like setgame and volume be remembered. So in the event of a reboot you wont have to re-enter some settings

**Comment by jagrosh** [comment]
I will add volume to the server settings file
I'll also add a `game=` line support to the config; setting the game via the bot won't save it (because sometimes you want something to show up just for a bit) but editing the config would change the default game.

**Comment by jagrosh** [comment]
`game=` is supported in the config, and volume is remembered after quit, as of release 0.0.3
