### ISSUE TITLE
[Feature Request] Have a command for owners to leave servers by ID/name

### ISSUE THREAD

**Issue by luevano** [jagrosh/MusicBot#1101]
### Is your feature request related to a problem? Please describe.

Can't remove a bot from a server if I don't have admin privileges anymore, I'm the owner.

### What is your ideal solution to the problem?

Make a command to be able to leave a server by a command if you're the owner. Because sometimes you may be revoked the admin privileges to add/remove bots.

### How would this feature be used?

Leave servers on command if you're the owner. Either by ID or just name.

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
This is already possible [via the eval command](https://jmusicbot.com/advanced-eval/)
