### ISSUE TITLE
[Bug Report] Bot in limbo after failed DNS resolution

### ISSUE THREAD

**Issue by BrunoBerger** [jagrosh/MusicBot#1112]
### Bug Description

This is more unexpected behaviour than bug.
When starting the bot at boot, the bot catches this error:
```Feb 07 15:04:23 raspberrypi bash[1297]: [15:04:23] [WARN] [Settings]: Failed to load server settings (this is normal if no settings have been set yet): java.nio.file.NoSuchFileException: serversettings.json
Feb 07 15:04:24 raspberrypi bash[1297]: [15:04:24] [INFO] [Startup]: Loaded config from /home/pi/myGithubStuff/selfhosted_bots/jMusicBot/config.txt
Feb 07 15:04:24 raspberrypi bash[1297]: [15:04:24] [ERROR] [Requester]: DNS resolution failed: discord.com: Temporary failure in name resolution
Feb 07 15:04:24 raspberrypi bash[1297]: Exception in thread "main" net.dv8tion.jda.api.exceptions.ErrorResponseException: -1: java.net.UnknownHostException
Feb 07 15:04:24 raspberrypi bash[1297]:         at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227) 
[...]
``` 
and then doesn't do anything but also does not exit, so it is forever in a sort of limbo

### Steps to Reproduce

Start the bot at boot with a sytemd-service

### Expected Result

That the bot would either:
- Try to start again
or
- exit properly

### Debug Output

```
System Properties:
  java.version = 11.0.12
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 11
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 11.0.12+7-post-Debian-2
  java.specification.version = 11
  os.arch = aarch64
  os.name = Linux

JMusicBot Information:
  Version = 0.3.6
  Owner = 150378001681481728
  Prefix = !
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.3.0_324
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.78

Runtime Information:
  Total Memory = 60
  Used Memory = 26

Discord Information:
  ID = 351463254515777546
  Guilds = 4
  Users = 1
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by Sanduhr32** [comment]
It should exit after the failed DNS resolution.
However we can't fix this issue through code.

**Comment by krux3r** [comment]
Don't know if it is same as your scenario, but I accidentaly left my dns blank on my Ubuntu server and that's what caused this exact issue. Inputing Google's dns to the dns field fixed up the issue for me. Strange but it works.

**Comment by MichailiK** [comment]
I believe making a solution for this on JMusicBot would be hacky & confusing to read. I rather consider this to be an issue with JDA (the library we use to connect to Discord), as it should be automatically trying to re-connect.

I'll close this, as I doubt we will implement a fix/workaround for this limbo state in JMusicBot,

**Comment by codemeister64** [comment]
Hi! 
I have the same issue. I'm using [this docker-image](https://hub.docker.com/r/alexandreteles/jmusicbot). 
If workaround/fix isn't implemented yet, maybe it is possible to completly fail docker container on mentioned exception? Then Watchtower will jsut restart the container. As for now, container just stucking on this exception

**Comment by FerroEduardo** [comment]
Happened to me today
JDA: `5.0.0-alpha.22`

```java
[JDA RateLimit-Worker 1] ERROR Requester - DNS resolution failed: discord.com: Temporary failure in name resolution
Exception in thread "main" net.dv8tion.jda.api.exceptions.ErrorResponseException: -1: java.net.UnknownHostException
```
