### ISSUE TITLE
Please add spotify

### ISSUE THREAD

**Issue by jakub96124124** [jagrosh/MusicBot#112]
good day of your project I like but spotify ba there personally all fit

**Comment by TheMonitorLizard** [comment]
Spotify requires an API key, which cannot be provided in the bot.

**Comment by jakub96124124** [comment]
it's nice to have a key so put into the config every one of my keys

**Comment by jakub96124124** [comment]
scope = 'playlist-modify-public'
        token = util.prompt_for_user_token("USERNAME", scope, "3b7eba6edc674bb4a78d62c111abb0f6",
                                           "9902c953bc9d4ab38a2343caf", "web")
        sp = spotipy.Spotify(auth=token)
        #DISPUTES IS JESUS ;) added checks for URI format
        #URI must be in format spotify:user:USERNAME:playlist:PLAYLISTID
        if URI.split(":")[1] == "user":
            username = URI.split(":")[2]
            playlist = URI.split(":")[4]
            res = sp.user_playlist_tracks(username, playlist)
            for items in res["items"]:
                song = items["track"]["name"]
                artist = items["track"]["artists"][0]["name"]
                songToPlay = str(song) + " by " + str(artist) + " Lyrics"
                await self.cmd_play(player, channel, author, permissions, leftover_args, songToPlay)
        #URI must be in format spotify:track:TRACKID
        elif URI.split(":")[1] == "track":
            track = URI.split(":")[2]
            res = sp.track(track)
            song = res['name']
            artist = res['artists'][0]['name']
            songToPlay = str(song) + " by " + str(artist) + " Lyrics"
            await self.cmd_play(player, channel, author, permissions, leftover_args, songToPlay)
        #URI must be in format spotify:album:ALBUMID
        elif URI.split(":")[1] == "album":
            album = URI.split(":")[2]
            res = sp.album_tracks(album)
            for items in res["items"]:
                song = items["name"]
                artist = items["artists"][0]["name"]
                songToPlay = str(song) + " by " + str(artist) + " Lyrics"
                await self.cmd_play(player, channel, author, permissions, leftover_args, songToPlay)
                
        # TODO checks to see if it fails
        
        #TODO Check if everything was added to queue
        return Response(songToPlay+" Added")

**Comment by vitalkanev** [comment]
Can you not leak the key?

**Comment by jakub96124124** [comment]
it is not a good idea to implement

**Comment by jagrosh** [comment]
I've stated on multiple occasions that I will not be adding features that require additional API keys at this time.

**Comment by jakub96124124** [comment]
thank you for your embarrassment
