### ISSUE TITLE
[Bug Report] Spotify Tracks & Playlists

### ISSUE THREAD

**Issue by REMOOO** [jagrosh/MusicBot#1131]
### Bug Description

the bot can't play Spotify Tracks & Playlists , why ?

### Steps to Reproduce

the bot can't play Spotify Tracks & Playlists , why ?

### Expected Result

the bot can't play Spotify Tracks & Playlists , why ?

### Debug Output

the bot can't play Spotify Tracks & Playlists , why ?

### Additional Info

the bot can't play Spotify Tracks & Playlists , why ?

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
https://jmusicbot.com/things-that-wont-be-added/#spotify
