### ISSUE TITLE
[Feature Request] Encrypt Bot Token in Config

### ISSUE THREAD

**Issue by cheezymousehouse825** [jagrosh/MusicBot#1132]
### Is your feature request related to a problem? Please describe.

If the host of the bot gets hacked and someone steals the bot's token, the hacker could possibly use the account for malicious activities like spamming advertisements and possibly nuking the server (I am not sure this is possible due to the bots permissions)

### What is your ideal solution to the problem?

Have a separate file that contains the bot token that is password encrypted.

### How would this feature be used?

1. Instead of entering the token into the config, make it generate if there is not token file already detected
2. To generate it, users must first enter the token, and then the password they would like to use to encrypt the token
3. In order to start the bot you put in the password which you set in step two so that the bot can un-encrypt and use the token

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
Just use these types of security on your host; if someone can hack your host, they'd be able to get your bot's token from runtime even without it being explicitly in the config file.

**Comment by jagrosh** [comment]
Additionally, you should not be giving a music bot any kind of elevated permissions; certainly not Administrator.
