### ISSUE TITLE
[Bug Report] Error when playing a track

### ISSUE THREAD

**Issue by kubo6472** [jagrosh/MusicBot#1142]
### Bug Description

When loading a track sometimes this error occurs. Music then stops.

### Steps to Reproduce

1. Play some music
2. Observe

### Expected Result

Music keeps playing

### Debug Output

[ERROR] [RestAction]: RestAction queue returned failure: [ErrorResponseException] 10008: Unknown Message
Apr 1 10:59:39 PM  net.dv8tion.jda.api.exceptions.ContextException: null        at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)       at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71) at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:197)      at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:573)   at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:539)   at com.jagrosh.jmusicbot.commands.music.PlayCmd$ResultHandler.loadSingle(PlayCmd.java:119)      at com.jagrosh.jmusicbot.commands.music.PlayCmd$ResultHandler.playlistLoaded(PlayCmd.java:166)  at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:446)        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)   at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98) at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)    at java.base/java.lang.Thread.run(Thread.java:829)

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
This is tracked under #1144.
