### ISSUE TITLE
Summon bot to new channel

### ISSUE THREAD

**Issue by joshbrown50** [jagrosh/MusicBot#115]
Is it possible to add a summon command to be able to change channels without having roles to move people?

**Comment by jagrosh** [comment]
I don't see a need for this.

If the bot is not being used, the `play <song>` command already makes the bot join the channel.

If the bot is already being used, regular users shouldn't be able to take the bot away from others. DJs and Admins can already stop the bot and then start playing in another channel.

**Comment by joshbrown50** [comment]
Do you need to stop the bot in order for the play song to switch channels? Because its the DJ's that I want to give the summon power to

**Comment by jagrosh** [comment]
A `move` command for DJs (with `summon` as an alias) would be fine I guess, I'll add this to the [suggested features list](https://github.com/jagrosh/MusicBot/projects/1)

**Comment by PallavBS** [comment]
This would be awesome
