### ISSUE TITLE
[Bug Report] YouTube playlist still dont work

### ISSUE THREAD

**Issue by HaTeMikee** [jagrosh/MusicBot#1150]
### Bug Description

Its giving me an error when i want to play any puplic Playlists. I downloaded the newest Version 0.3.8 but its still not working

### Steps to Reproduce

Plaing Playlists from youtube 

### Expected Result

That its playing music for me

### Debug Output

Idk

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by purnell569** [comment]
ive just updated and tested the bot. works perfectly for playlists. remember in the playlist.txt file to add the youtube links, (ie. https://www.youtube.com/watch?v=dQw4w9WgXcQ ) without any extra and 1 per line

**Comment by purnell569** [comment]
you create the file. so in your config.txt file, there is a section which says:
// This sets an alternative folder to be used as the Playlists folder
// This can be a relative or absolute path
playlistsfolder = "Playlists"

1. create a folder called Playlists(or rename to whatever youve named in the config.txt) <--- create playlist subfolder where .jar file is.
2. inside the folder create a file called playlist1.txt
3. edit playlist1.txt and put youtube links in there and save
4. with bot, just do command: !play playlist1
5. done

**Comment by HaTeMikee** [comment]
And how can i play playlist from youtube itself? An week ago there was no
problem but now it say an error "error loading track"
How can i play those again?

purnell569 ***@***.***> schrieb am Do., 7. Apr. 2022, 15:24:

**Comment by MichailiK** [comment]
I'm going to assume that you were trying to play a mix playlist. Issues with YouTube mixes are already tracked under #1147.
