### ISSUE TITLE
[Feature Request] q as alias for queue

### ISSUE THREAD

**Issue by TheArcaneBrony** [jagrosh/MusicBot#1170]
### Is your feature request related to a problem? Please describe.

having to type queue

### What is your ideal solution to the problem?

add an alias `q`

### How would this feature be used?

1. you type <prefix>q
2. it displays queue

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
This is already possible, you can set aliases in the [config](https://jmusicbot.com/config/)
