### ISSUE TITLE
Failing to play YT links and song names with spaces

### ISSUE THREAD

**Issue by TTTime05** [jagrosh/MusicBot#1171]
### Bug Description

Bot failing to play songs. Seems to be YouTube links and spaces in the name. Underscores instead of spaces fixed the issue. Happened to multiple people, with different privileges, including an admin. The message just would not send.

### Steps to Reproduce

1. Try inputting a link or a name with spaces
2. See Discord refuse to allow the message to send.

### Expected Result

The message to send and the bot to function

### Debug Output

OS: Windows 10 for all affected parties
Version: 0.3.8 I believe

### Additional Info

I use / for commands. Changing this seemed to fix it. It may very well be Discord's fault

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
This is the Discord client thinking, in some circumstances, that you're trying to use a slash command. It won't let you send a normal message when it doesn't find a slash command.
