### ISSUE TITLE
Suggestion : Song limit per user

### ISSUE THREAD

**Issue by PliCx** [jagrosh/MusicBot#118]
Some people are adding a lot and a lot of songs to the queue list, it would be great to add a song limit per user in config.txt

**Comment by jagrosh** [comment]
This feature is already on the in-progress section of the [Suggested Features List](https://github.com/jagrosh/MusicBot/projects/1)

Also, don't forget that FairQueue means that nobody can hog the queue if multiple people are adding songs, so this shouldn't be a huge issue anyway.
