### ISSUE TITLE
[Feature Request] A restart command

### ISSUE THREAD

**Issue by bjarkeh14** [jagrosh/MusicBot#1189]
### Is your feature request related to a problem? Please describe.

I like the bot to have a restart command, in case it stops working. So I don't need to login to my server to restart the bot

Something like !restart

### What is your ideal solution to the problem?

And command to restart bot

### How would this feature be used?

1. !restart
2. The bot restart and rejoin the last channel it was in
3. Starts playing the last request or if none the auto playlist

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
This is not a reliable possibility, as once the java process ends, it can no longer spawn a new java process. I would recommend running the bot within a looping script such that when you use the `shutdown` command, it will effectively restart.

If there is already music playing (and thus working), then why would a restart be needed? If it's not playing and something went wrong, it's likely that either the track will never play, or that starting fresh would be the best option anyway.
