### ISSUE TITLE
Suggestion: Playlist loop

### ISSUE THREAD

**Issue by Z3USS** [jagrosh/MusicBot#12]
Make an option maybe do not know, so that the playlist is repeated when finished so you do not have to be adding the songs again, For the bot to be used as a "**radio**".

**Comment by jagrosh** [comment]
My vision for this is a toggle-able mode. When this mode is not toggled on, everything behaves as normal. When toggled on, whenever a song finishes, it is added back to the queue as if the user who originally added it did so again. New songs would still be able to be added and played songs would continue to be re-added until the mode was toggled off or the `stop` command was used.

**Comment by Z3USS** [comment]
Would be that, in my view would be a very interesting option.

**Comment by Humhah** [comment]
Need it too,a useful function.Hope to see it soon.

**Comment by SunburntRock89** [comment]
Yeah, because when it gets to the end of a playlist it leaves the channel, needing resummoned, good idea

**Comment by jagrosh** [comment]
This is now possible as of version 0.1.1; check out the `repeat` command
