### ISSUE TITLE
StreamTheWorld decoding issues(?)

### ISSUE THREAD

**Issue by Mamumimi** [jagrosh/MusicBot#120]
Having issues getting two local stations hosted by streamtheworld to work. Launching the containers through !!play fills the console with errors but pretends to work on discord, disconnecting from the voice channel half a second after joining. Something about decoding going wrong. These are all working fine through VLC.

95.7 BENFM Philadelphia (AAC): 
pls: http://provisioning.streamtheworld.com/pls/WBENFMAACIHR.pls
m3u: http://provisioning.streamtheworld.com/m3u/WBENFMAACIHR.m3u

93.3 WMMR Philadelphia (AAC):
pls: http://provisioning.streamtheworld.com/pls/WMMRFMAACIHR.pls
m3u: http://provisioning.streamtheworld.com/m3u/WMMRFMAACIHR.m3u

**Comment by Mamumimi** [comment]
Any news, @jagrosh ?

**Comment by Mamumimi** [comment]
Turns out the links inside the containers do work, but the bot does not properly parse the container. Links such as "http://16083.live.streamtheworld.com:80/WMMRFMAACIHR_SC" work (first line of WMMRFMAACIHR.pls)

**Comment by jagrosh** [comment]
Is this issue still present with the latest version (0.2.1)?

**Comment by jagrosh** [comment]
Alright, I'm going to close this now; if you find more links that you think _should_ work but don't, and you can reproduce the link not working, I'd recommend opening an issue on [lavaplayer](https://github.com/sedmelluq/lavaplayer), as lavaplayer handles all the decoding for audio sources.
