### ISSUE TITLE
Bot needs Message Content Intent

### ISSUE THREAD

**Issue by Shokushu** [jagrosh/MusicBot#1207]
### Bug Description

Since september 1st, bots require Message Content Intent to read channel messages. It can be temporarily set in the Discord Developper Portal, but a warning says "Verified apps may re-enable message content until October 1, 2022. Doing so will stop your bot from joining more servers until disabled."

### Steps to Reproduce

Tried sending commands to the bot but it doesn't see them

### Expected Result

The bot is supposed to see the commands sent in chat

### Debug Output

version 0.3.8

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
I published a message [in my development server](https://discord.gg/0p9LSGoRLu6Pet0k) about this. This is something you'll need to do yourself, it's not a modification to the bot. Here's the original message for people who aren't in the server:

> 
> If your music bot stopped responding to commands _today_, it may have been because of the recent Discord rollout to intents changes. If you bot is on more than 75 servers, it will likely be permanently broken. However, if you've kept it private (as intended), here's what you'll need to do:
> 
> 1. Head on over to <https://discord.com/developers/applications> and find your bot application.
> 2. Click on the **Bot** tab on the sidebar (see first image below)
> 3. Turn **Message Content Intent** (should be the last checkbox on the page) **ON**
> 4. Make sure your checkboxes match the ones I have shown (see second image below)
> ![image1](https://cdn.discordapp.com/attachments/159848738569977858/1015010597219356694/unknown.png)
> ![image2](https://cdn.discordapp.com/attachments/159848738569977858/1015010597491965994/unknown.png)

**Comment by Shokushu** [comment]
Thank you, so nothing else should be done by October 1st? I will close this =)

**Comment by jagrosh** [comment]
Assuming your bot is private and on less than 75 servers, enabling this should be all you need to do; you shouldn't need to do anything come Oct 1st.
