### ISSUE TITLE
Is it possible to put the Bot's status as Streamer Mode?

### ISSUE THREAD

**Issue by WumboCumbo** [jagrosh/MusicBot#121]
I honestly just like the purple color

**Comment by jagrosh** [comment]
You can do this if you want to enable the eval command and set it manually (included necessary eval below). I'll add this to the suggested features list.

`eval jda.getPresence().setGame(Java.type("net.dv8tion.jda.core.entities.Game").streaming("Game name", "http://twitch.tv/yourname"))`
