### ISSUE TITLE
[Bug Report] Title Here 

### ISSUE THREAD

**Issue by Chonkyboi3407** [jagrosh/MusicBot#1214]
### Bug Description

cannot change name of bot
i write !setname and name multiple different things and it says that nam is not valid

### Steps to Reproduce

.

### Expected Result

i expected the name to be changed

### Debug Output

latest version 

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
Try setting the name in the [Developer Dashboard](https://discord.com/developers/applications) by going to your app -> Bot & changing the name there.

![image](https://user-images.githubusercontent.com/39029839/194779641-bac9754e-983d-4a56-b5e5-1d259c0ca49f.png)

**Comment by jagrosh** [comment]
If you're unable to change the name via the command, then the correct way is via the developer portal as per the message above. Discord has hefty ratelimits on changing usernames, and some characters are invalid, so it is much more consistent to use the developer portal for this action. The `setname` command is from a time before the developer portal method existed.
