### ISSUE TITLE
Set default volume in config

### ISSUE THREAD

**Issue by slepkin** [jagrosh/MusicBot#123]
Like most music bots, JMusicBot is by default too loud for most users. Each user can easily turn it down to the appropriate level, but it's very jarring for all new users to the server. Until Discord implements this [on their side](https://feedback.discordapp.com/forums/326712-discord-dream-land/suggestions/17905765-set-default-volume-of-bot-for-all-users-as-server), it'd be nice if default volume was a config option in JMB.

**Comment by ringmatthew** [comment]
This is already on the [suggested features list](https://github.com/jagrosh/MusicBot/projects/1)

**Comment by slepkin** [comment]
Ah, I checked the issues but not the features. Thanks!
