### ISSUE TITLE
[Feature Request] Support YouTube API key for optional use

### ISSUE THREAD

**Issue by lynrayy** [jagrosh/MusicBot#1241]
### Is your feature request related to a problem? Please describe.

YouTube api key will be useful for play 18+ videos like in https://github.com/jagrosh/MusicBot/issues/1026

### What is your ideal solution to the problem?

Add support of YouTube API that can be optionally set in config file

### How would this feature be used?

1. Enable Youtube api in google account
2. copy key
3. paste it in config

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
You have not read the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added/#features-requiring-additional-api-keys).

**Comment by lynrayy** [comment]
Ok if it will not be added, will you fix NSFW videos requiring authorization?

**Comment by MichailiK** [comment]
It will depend on if a workaround can be found. Subscribe to #1026 for any updates until then.
