### ISSUE TITLE
[Feature Request] Run the Bot 24/7

### ISSUE THREAD

**Issue by PatriotRBX** [jagrosh/MusicBot#1251]
### Is your feature request related to a problem? Please describe.

How do you run the bot 24/7?

### What is your ideal solution to the problem?

How to run the bot 24/6

### How would this feature be used?

1. The bot runs 24/7 and doesn't require the persons computer to stay on. 

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by skoinks** [comment]
You need a machine for the bot to run on. It can't run on thin air. The documentation has a few options for hosting the bot on an external server.
