### ISSUE TITLE
[Bug Report] The bot wont respond to commands

### ISSUE THREAD

**Issue by Peanutis1mo** [jagrosh/MusicBot#1259]
### Bug Description

I invited to the bot, the first command I did was help, it worked. But all other commands wont do anything and the bot is unresponsive. I tried restarting it, there are no errors in console and it is online. It wont even join the voice channel. It does nothing.

### Steps to Reproduce

Invite the bot
write a command
nothing happends

### Expected Result

To do the things the bot has to do

### Debug Output

Well I tried running it but it is unresponsive.

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
Incredibly likely to be #1215. If it's not, comment & I will reopen the issue.
