### ISSUE TITLE
does not join vc when changing the prefix from config file 

### ISSUE THREAD

**Issue by tototo123113** [jagrosh/MusicBot#1261]
### Bug Description

does not join vc when changing the prefix from config file 

### Steps to Reproduce

Prefix='!'

### Expected Result

to join my vc and play music

### Debug Output

the prefix to be !play and then it would join but it wouldnt 

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
See #1215
