### ISSUE TITLE
[Feature Request] Spotify compability

### ISSUE THREAD

**Issue by JUJKZ** [jagrosh/MusicBot#1267]
### Is your feature request related to a problem? Please describe.

Can somehow be done that the bot can play a spotify links?

### What is your ideal solution to the problem?

I want that the bot will play a spotify songs \_[:)]_/ 

i dont know how to solve it
(what is this question [ I am requesting a feature not solving it I am not shane bee ])

### How would this feature be used?

Instead of youtube link you will paste a spotify song link

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
https://jmusicbot.com/things-that-wont-be-added/#spotify
