### ISSUE TITLE
Blank as prefix work as default prefix (@mention).

### ISSUE THREAD

**Issue by lenkunz** [jagrosh/MusicBot#127]
In config example. It said when blank as prefix, it will not use prefix. But bot seems to use @mention as prefix instead.

```java
    this.prefix = prefix==null || prefix.isEmpty() ? DEFAULT_PREFIX : prefix;
```
[source](https://github.com/JDA-Applications/JDA-Utilities/blob/e78c34d6d83677241a73ec1dcb1e1c72c04adfc1/src/main/java/com/jagrosh/jdautilities/commandclient/impl/CommandClientImpl.java#L128)

**Comment by jagrosh** [comment]
Due to changes to the configuration format, as well as limitations of some underlying libraries, I don't think that a blank prefix will be supported at this time.

**Comment by samueldcorbin** [comment]
If this isn't going to be fixed, could the line be removed from the provided config.txt? It should not advertise a capability that is not present, much less one for which support isn't planned.

Though I hope you will reconsider. The option to set no prefix would be very nice in the use case where MusicBot is set to listen on a separate, muteable text channel. I have two servers set up like this so users can see notifications from normal text channels without interrupting them with MusicBot commands and replies. In this case, it would make a lot of sense for MusicBot to just respond to any chat in that channel as a command.

**Comment by jagrosh** [comment]
This is not a limitation of JMusicBot, this is a limitation of JDA-Utilities, so it won't be possible. The provided config has the line
```
prefix = "@mention"
```
so the feature isn't being 'advertised'.

**Comment by jagrosh** [comment]
Also, I'm a bit confused by `to just respond to any chat in that channel as a command`. Having a blank prefix would still require writing the full name of the command, for example:
`play Spiderman 2 Pizza Game Theme`

It wouldn't respond to something like
`Hello there` 
nor 
`someone play Spiderman 2 Pizza Game Theme`

just like how if you set the prefix to `!`, it won't respond to
`!Hello there` 
nor 
`!someone play Spiderman 2 Pizza Game Theme`

**Comment by samueldcorbin** [comment]
See: https://github.com/jagrosh/MusicBot/wiki/Example-Config

It is also present in config.txt of the current release.

` //  If you make this blank, the bot will not use a prefix`

I imagine this is simply an outdated comment, but it should probably be removed.

As for what I meant by "respond to any chat in that channel as a command", I meant exactly what you are describing: treating any chat in the text channel as a potential command, regardless of whether it comes with a prefix.

I admit I'm not really sure what the confusion is though - how could it even in theory respond to something like `Hello there`? What would it respond with? I'm not sure what you imagine I might have been imagining, so sorry if I'm not answering your question clearly.

**Comment by jagrosh** [comment]
Ah, yes that's an old comment, I've removed it.

As for the responding to chat, it wouldn't be 'regardless' though, if you included a `!` before the message, it _wouldn't_ respond. All you'd be doing is setting the prefix to nothing, in which case you still have to use all the commands as normal, they just need to be preceded by exactly nothing instead of exactly a `!`.

Another negative side-effect would be that unless you modified permissions so that the bot could _only_ see your music channel, typing something like `help me` in any channel the bot could see would result in receiving a DM with the commands.

**Comment by samueldcorbin** [comment]
Right, I meant without a prefix.

As for modifying permissions so the bot can only see the music channel, I assumed that was what settc already did. It appears that I was wrong and it still responds to commands and sends DMs, including for `help`, so I suppose you're right (though as an aside I find it pretty strange that it would watch and respond to commands in another channel after I've set "the text channel for music commands" - that is definitely not what I expected).

I guess it's not really doable given those responses, and it sounds like it's difficult or impossible without substantial changes to the libraries you're using anyway.

**Comment by jagrosh** [comment]
The `settc` effect is only for commands in the `Music` category; all non-music commands function normally in any channel.

**Comment by lenkunz** [comment]
It's kind of weird about digging the old thread.

But to workaround with that I override the method to prepend "!" to every message when the prefix is set to blank. Then override the prefix to "!"
