### ISSUE TITLE
[Bug Report] Prefix in combination with other commands

### ISSUE THREAD

**Issue by perqss** [jagrosh/MusicBot#1275]
### Bug Description

Executing commands  

1. !prefix !play
2. !play queue

searches for 'queue' and plays a song.

### Steps to Reproduce

Type in commands:

1. !prefix !play
2. !play queue

### Expected Result

Same result as if !queue command was executed.

### Debug Output

```
System Properties:
  java.version = 17.0.4.1
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 17
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 17.0.4.1+1
  java.specification.version = 17
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.3.8
  Owner = 689431450508066911
  Prefix = !
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.0_352
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.78

Runtime Information:
  Total Memory = 37
  Used Memory = 14

Discord Information:
  ID = 1029868760045207602
  Guilds = 2
  Users = 4
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
Your (global) prefix, `!` got recognized, not the guild prefix `!play`, so this seems like technically valid behavior. This doesn’t look like worth changing how prefixes work anyway.
