### ISSUE TITLE
[Feature Request] Having multiple people with owner command access

### ISSUE THREAD

**Issue by Argentum047** [jagrosh/MusicBot#1278]
### Is your feature request related to a problem? Please describe.

In the config, you cannot set multiple people to be owners/ have access to owner-only commands. If there is support for multiple "owners", there is nothing stating the fact that you can add multiple ids (from a previous request opened in 2018, seems to not have been supported yet).

### What is your ideal solution to the problem?

Once multiple owners have been supported, add a comment in the config briefly explaining how to add multiple owners. Another option on top of that would be running a command to make someone an "owner" or have owner level permissions. (i.e., "setowner <id-here>" or setowner <@mention>). 

An alternative solution would be to have one main "owner" and then have other "co-owners" that can run the current owner-only commands (similar to admin commands). 

### How would this feature be used?

1. Grab someone's user id by right clicking on them, or just know their nickname.
2. Either a) edit the config file to include their user ID or run a command to set someone to an owner (via ID or mention).

### Additional Info

Old issue - https://github.com/jagrosh/MusicBot/issues/186

(Note that I have no knowledge on the matter so I don't know if any of this is possible)

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
#186 is still open, please don't open duplicate issues
