### ISSUE TITLE
[Feature Request] Add Linux Support

### ISSUE THREAD

**Issue by drachedachte1** [jagrosh/MusicBot#1288]
### Is your feature request related to a problem? Please describe.

to be able to have it run 24/7 i would like to have a version for linux

### What is your ideal solution to the problem?

Linux Support

### How would this feature be used?

By people that want to have the bot running 24/7 from a linux server, vps etc

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
It already works on linux

**Comment by drachedachte1** [comment]
> It already works on linux

how to install
