### ISSUE TITLE
Bot stays in channel after adding invalid link to queue.

### ISSUE THREAD

**Issue by VeryLongNicknameSuchWow** [jagrosh/MusicBot#129]
I am running the latest version (0.1.2) on Ubuntu Server 16.04. When anyone adds a link from youtube that is "unavailable" when you open it in your browser then bot stays in voice channel even though stayinchannel is set to false in config. There are no errors in console output.

**Comment by jagrosh** [comment]
This will be resolved in the next release with the merge of #583
