### ISSUE TITLE
I Can't Set Custom Prefix 

### ISSUE THREAD

**Issue by Assasinowy** [jagrosh/MusicBot#1295]
### Bug Description

The Only Prefix that work Is "@mention" i tried to set it to ! or - and it don't work

### Steps to Reproduce

1.Change the Prefix to something Else than @mention 

### Expected Result

Error Or Something Bot just Don't Detect Command

### Debug Output

i cannot run the command My operating system Version is Windows 10 JmusicBot version is 0.3.8

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by CelaldoganGunes** [comment]
I have same bug

**Comment by CelaldoganGunes** [comment]
https://jmusicbot.com/getting-a-bot-token/ step 7

![image](https://user-images.githubusercontent.com/17123945/218855402-63467dc3-9519-423f-8eea-ac2765ff8281.png)
