### ISSUE TITLE
[Bug Report] Prefix issue

### ISSUE THREAD

**Issue by n00blance** [jagrosh/MusicBot#1299]
### Bug Description

Basically, I am unable to change the prefix. whenever I change the prefix it completely stops working. I can only use the bot mention as a prefix since it's the only one that doesn't break..

### Steps to Reproduce

1. change prefix to something custom

### Expected Result

bot using new prefix

### Debug Output

[debug_information.txt](https://github.com/jagrosh/MusicBot/files/10814985/debug_information.txt)

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
See #1215.
