### ISSUE TITLE
Max Amount of Songs Allowed in a Single Playlist

### ISSUE THREAD

**Issue by OrangeFlare** [jagrosh/MusicBot#130]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [X] I am running the [latest version][download]: [![Release][release]][download]
- [X] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [X] I have read through the [planned and suggested features][features]

### Issue Type

- [ ] Bug Report
- [X] Feature Request

### Description

What would be nice is a maximum amount of songs in a playlist
For example we have a cuck in our server who has this 500 song playlist on youtube, It would be nice if he wouldn't be able to play that, like have a value in the config file that passes through to the youtube download Class/File and before it starts to play the songs from the playlist it checks if the playlist is over the maximum amount of songs limit

**Comment by jagrosh** [comment]
Thanks for using the template! This was actually already covered by an issue, but I can see how the wording wouldn't make it clear. I've reworded this in the 'In Progress' column on the [planned features list](https://github.com/jagrosh/MusicBot/projects/1).
