### ISSUE TITLE
[Bug Report] Bot keeps disconnecting from voice channel after 4-5 seconds

### ISSUE THREAD

**Issue by Dushuav2** [jagrosh/MusicBot#1306]
### Bug Description

When I try to open any song the bot joins the voice channel and leaves after 5 seconds then comes back again then leaves again it does this the whole time.

### Steps to Reproduce

1. !play song
2. disconnect after 4-5 secs
3. join back after 2 secs
4. repeat 

### Expected Result

Play the song

### Debug Output

[debug_information.txt](https://github.com/jagrosh/MusicBot/files/10861865/debug_information.txt)

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
This seems to have happened very recently. We're looking into this now.

**Comment by theKAKAN** [comment]
It happened to me as well. On one server, music played. On another server, the bot kept disconnecting and reconnecting. Also, for that particular server, it sometimes generated error logs like these:
![image](https://user-images.githubusercontent.com/22027824/222175254-9c9b2235-2e89-4815-bdb4-c8b016d4e375.png)
![image](https://user-images.githubusercontent.com/22027824/222175286-420d4162-a424-40d6-9f92-8c94eb20aaa8.png)

The music ID in question: `FM7MFYoylVs`

Though, a lot of times, it just kept disconnecting and reconnecting _without_ any errors as well.

**Comment by mythseller** [comment]
Reporting this as well, can provide logs but same as above. Tested in two servers, two instances, one with everyone permissions

**Comment by r-vd-woude** [comment]
I believe this is related to the following, closed issues. I reported the issue there a couple of days ago. 
#249

**Comment by IbbyWondrous** [comment]
I haven't changed anything with the bot and it started having this issue today. Granted, I don't know anything about bots and followed a tutorial but everything should be correct so idk what's wrong.

**Comment by ClassyCustom** [comment]
same issue

**Comment by MichailiK** [comment]
I believe that this is caused by Discord making changes to Voice Connections. I can't pin down what they changed at the moment, but a workaround that seems to work is changing the channel's voice region to something else (i.e. Hong Kong)

**Comment by ClassyCustom** [comment]
Tried that didn't work for me

**Comment by mythseller** [comment]
I have a server using 0.3.6 and its working, but unsure if maybe its just a discord VC thing

**Comment by MichailiK** [comment]
I'm locking the issue for now to avoid commentary & focus on any updates or workarounds that come up.

**Comment by MichailiK** [comment]
The issue has been identified by JDA, and a hotfix has been made. We will soon make a release of JMusicBot that contains this fix.

**Comment by MichailiK** [comment]
I've just published [Version 0.3.9](https://github.com/jagrosh/MusicBot/releases/tag/0.3.9) which fixes this issue. Please update to it, as 0.3.8 and below are not expected to function anymore.

For some technical context: Discord has (unexpectedly?) changed the data that gets sent when JDA attempts to do UDP Discovery, causing JDA to retry the voice connection over & over.

**Comment by MichailiK** [comment]
This issue *might* happen on v0.3.9, in case Discord hasn't deployed this change on all voice regions yet (although I expect for it to have been rolled out worldwide by now), so if you continue to encounter this issue on v0.3.9, please mention it here.

**Comment by MichailiK** [comment]
Discord has made an [announcement](https://discord.com/channels/613425648685547541/697138785317814292/1080623873629884486) on the [Discord Developers server](https://discord.gg/discord-developers) in regards to the change that broke JMusicBot:

<img width="776" alt="image" src="https://user-images.githubusercontent.com/39029839/222380337-5ad6ce3f-e9f3-4f95-b09c-5bfbe0f98442.png">

JMusicBot 0.3.8 should work again until 15th March. After that, 0.3.8 is expected to break again & you must update to [the latest version](https://github.com/jagrosh/MusicBot/releases/latest) to be able to use JMusicBot.

**Comment by ABowlOfEleven** [comment]
I'm seeing the again using ver 0.3.9. 

!play, then joins the VC, then immediately leaves the vc.

System Properties:
  java.version = 11.0.13
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 11
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 11.0.13+8-Ubuntu-0ubuntu1.21.04
  java.specification.version = 11
  os.arch = amd64
  os.name = Linux
JMusicBot Information:
  Version = 0.3.9
  Owner = 225045208390172673
  Prefix = !
  AltPrefix = -
  MaxSeconds = 0
  NPImages = true
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true
Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.78
