### ISSUE TITLE
Suggestion: Be able to list the songs in a playlist and delete certain ones

### ISSUE THREAD

**Issue by mcao** [jagrosh/MusicBot#131]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [x] I am running the [latest version][download]: [![Release][release]][download]
- [x] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [x] I have read through the [planned and suggested features][features]

## Issue

Suggestion: Be able to list the songs in a playlist and delete certain ones

### Issue Type

- [ ] Bug Report
- [x] Feature Request

### Description

I use the bot's playlist feature a lot, and it's annoying to have to go into nano to see and edit the songs in a playlist. A way to see the songs and remove certain ones from Discord would be appreciated :)

**Comment by jagrosh** [comment]
I've added this to the [suggested features list](https://github.com/jagrosh/MusicBot/projects/1); thanks for the suggestion for using the template!
