### ISSUE TITLE
Can we run the music bot on Linux Server?

### ISSUE THREAD

**Issue by Rikusen0335** [jagrosh/MusicBot#132]
I ran the Music Bot on ubuntu server, but it didn't play a song.

**Comment by FarukGamer** [comment]
Yes you can :)

**Comment by Rikusen0335** [comment]
It plays some songs can be played, others can not.

**Comment by FarukGamer** [comment]
Which song does not play?

**Comment by Rikusen0335** [comment]
I found these:
https://www.youtube.com/watch?v=5YxVMyeIGvA
https://www.youtube.com/watch?v=rI-t2M0t63s
https://www.youtube.com/watch?v=MpZFVM800f8

**Comment by FarukGamer** [comment]
The songs are playing fine for me, did you made sure to download the latest version? or any error messages on the Server?

**Comment by jagrosh** [comment]
Please use the issue template. Can you provide information about what version you are running, with screenshots of what the bot replies and the contents of console?

**Comment by Rikusen0335** [comment]
Thanks for your reply, and I apologize you that I didn't use 0.1.2, and used 0.1.0 instead.
So this issue ends.
