### ISSUE TITLE
PM owner when a new update is released

### ISSUE THREAD

**Issue by Frogperson** [jagrosh/MusicBot#134]
Maybe add a setting for the bot to check for updates periodically and then pm the owner when a new update is released so they can update it.

**Comment by ringmatthew** [comment]
In my opinion, this seems a bit unnecessary. Just join the [support server](https://discord.gg/VVSjAdv) and do `%roleme Music Updates` to receive MusicBot updates.

**Comment by Frogperson** [comment]
I wasn't aware we could do that so thank you. I still think this would be a cool feature for people who don't want to clutter up their server lists. And should be relatively easy to add.

**Comment by jagrosh** [comment]
This has been added to the [suggested features list](https://github.com/jagrosh/MusicBot/projects/1)
