### ISSUE TITLE
Unable to change prefix

### ISSUE THREAD

**Issue by pashalecqua** [jagrosh/MusicBot#1344]
### Bug Description

The bot works perfectly fine with "@mention" but when I try to change it to "le" or "pls" it fails to work at all, but then works again when I switch it back. 

### Steps to Reproduce

Change the "@mention" to "le" or "le "

// This sets the prefix for the bot
// The prefix is used to control the commands
// If you use !!, the play command will be !!play
// If you do not set this, the prefix will be a mention of the bot (@Botname play)

prefix = "@mention"

### Expected Result

I would be able to type le play x and x would play

### Debug Output

```
System Properties:
  java.version = 11.0.18
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 11
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 11.0.18+10-post-Debian-1deb11u1
  java.specification.version = 11
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.3.9
  Owner = 275067676575924226
  Prefix = @mention
  AltPrefix = le
  MaxSeconds = 0
  NPImages = false
  SongInStatus = true
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.78

Runtime Information:
  Total Memory = 38
  Used Memory = 29

Discord Information:
  ID = 1089234504733954128
  Guilds = 1
  Users = 7
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
#1215
