### ISSUE TITLE
manual prefixes result in no response from the bot, despite it telling me to use the prefix under its name.

### ISSUE THREAD

**Issue by snorasaur** [jagrosh/MusicBot#1348]
### Bug Description

i used to use the bot with a prefix of '-'
but when i updated to 0.3.9 today, it would not work.
i reset the token, the owner id, remade the bot, but nothing worked.
only when i deleted the config, and let the bot regenerate a config did it work. but only with the default prefix of "@mention"
once i changed the prefix to '-', saved config, and restarted the bot, it would no longer respond, despite it saying its "playing: type -help" under its name on the right of discord.
i tried '-', '--', '!', and '!!' (like the config shows in the comments) and NONE of them work.
the bot simply will not respond, or emote on what i type. nor will is DM me the "help" message.

![jbot bug](https://user-images.githubusercontent.com/127803473/230743192-c9649c26-6b25-4a90-8120-e9272cf2e1f4.png)

### Steps to Reproduce

open config
set prefix to anything other than default? (i tried -, --, !, and !!)
save config
start or restart the bot
note the change in its "playing: type -help" message under its name on the right side
type -help, but get no DM
type -play "song name", but have nothing happen

### Expected Result

bot should respond to the prefix i set

### Debug Output

```
System Properties:
  java.version = 1.8.0_333
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 1.8.0_333-b02
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.3.9
  Owner = 239877749420982273
  Prefix = @mention
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.78

Runtime Information:
  Total Memory = 380
  Used Memory = 53

Discord Information:
  ID = 1094364901776040067
  Guilds = 1
  Users = 2
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
#1215

**Comment by snorasaur** [comment]
> #1215

that fixed it thanks. i searched for similar bugs, but missed this. hopefully it will be added to the guide to help future noobs like me.

**Comment by MichailiK** [comment]
Enabling the intents [is already in the Wiki](https://jmusicbot.com/getting-a-bot-token/) though.

<img width="1440" alt="Screenshot 2023-04-09 at 01 35 01" src="https://user-images.githubusercontent.com/39029839/230746902-bc38d3df-a1b3-4f90-b8b7-9a3a01af4198.png">

**Comment by snorasaur** [comment]
> Enabling the intents [is already in the Wiki](https://jmusicbot.com/getting-a-bot-token/) though.
> 
> <img alt="Screenshot 2023-04-09 at 01 35 01" width="1440" src="https://user-images.githubusercontent.com/39029839/230746902-bc38d3df-a1b3-4f90-b8b7-9a3a01af4198.png">

oh im sorry i guess i just missed that part
