### ISSUE TITLE
Unknown title

### ISSUE THREAD

**Issue by codc3** [jagrosh/MusicBot#135]
![image](https://user-images.githubusercontent.com/25847896/36075953-bf40f0fc-0f3c-11e8-9768-f275cd61faa2.png)

the bot still does not recognize the name of online radio link musics even when the link provides the names of the songs being played. Is there any forecast for this to be updated?
http://music.classicrock109.com:10042

**Comment by SiE98** [comment]
yes. Also from http://5.189.142.165:8096/stream

**Comment by jagrosh** [comment]
Is this still the case with the latest version (0.2.1)?

**Comment by SiE98** [comment]
eeemm. In status Playing type #help. On #playingnow command is write Source: Braingell-Radio-BGR
Not work for tags songs (((

**Comment by jagrosh** [comment]
Can you provide a screenshot of the nowplaying command for a source that still doesn't display correctly?

**Comment by Sanduhr32** [comment]
This might be fixed, since the issue is several years old now.
