### ISSUE TITLE
ZIP FILE

### ISSUE THREAD

**Issue by crybabydiscord** [jagrosh/MusicBot#1374]
### Bug Description

When I try to download the latest file of the music bot (the jar file) It will download fine but then I check my downloads and it's a zip file, I just need the console, help lol-

### Steps to Reproduce

idk

### Expected Result

I thought I was gonna get the jar file but instead I got a zip file

### Debug Output

I can't because its a zip file

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
You are probably using WinRAR & It has made itself the default program to launch JAR files with. On Windows 11, Right click -> Open with -> Other… -> Java -> Always Open.
For any further support, please use Discussion or join the Support server.
