### ISSUE TITLE
Using the bot with raspberry pi

### ISSUE THREAD

**Issue by Hagepaka** [jagrosh/MusicBot#138]
First thanks for making this great bot.
Ihave some quetions and bug report with the bot.
I have running the bot on my raspberry pi now. It's  working well.But when I change the volume like !!volume 1 then the bot will  stop playing and can't play the music anymore.If I delete serversettings.json and run the bot again it will be fine.

And the quetion is how can I play the music inside the  raspberry pi ? I can't play the music with typing path to the discord.

**Comment by jagrosh** [comment]
Please follow the issue template. It may be possible you did not follow the instructions found [here](https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi)

**Comment by Hagepaka** [comment]
Sorry for the  template. I think I already did  the instructions
https://imgur.com/a/wMI0c

**Comment by Lawlietnao** [comment]
yes, I'm facing the same issue here, and I've followed every single step as well. this had never happened until the new update :/

**Comment by jagrosh** [comment]
This should be fixed as of the [latest update](https://github.com/jagrosh/MusicBot/releases/latest). If you use the Linux jar, it already has the required library included.

**Comment by Lawlietnao** [comment]
@jagrosh problem solved, thank you so much!
