### ISSUE TITLE
[Bug Report] Bot leaves the voice channel and doesn't play the next song on queue

### ISSUE THREAD

**Issue by Lynchy21** [jagrosh/MusicBot#1384]
### Bug Description

The bot was working fine on the first day, but after day, the bot leaves the Voice channel after a song ends even though there are songs in queue. And skips/leave right before a song is gonna end.
the bot takes at least 30 - 40 seconds to start playing a song, and yes am up to date the the version.

I get this often while using the play command -> 🚫 Error loading track.  So I have to retry the command several times to get it work.  

Console says : https://pastebin.com/i2imgNJs
raw : https://pastebin.com/raw/i2imgNJs

### Steps to Reproduce

1. Bot must play the songs in queue.
2. bot should'not leave the vc or skip to the next song before a song gets over.

### Expected Result

I expected it to be an easy fix just by reinstalling everything again. but its doesn't work perfectly.

### Debug Output

System Properties:
  java.version = 20.0.1
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 20
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 20.0.1+9-29
  java.specification.version = 20
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.3.9
  Owner = 585444433785257985
  Prefix = d.
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = true
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.78

Runtime Information:
  Total Memory = 58
  Used Memory = 30

Discord Information:
  ID = 1111986095035523092
  Guilds = 2
  Users = 2

### Additional Info

this all started when i first use the volume command, i don't know if that has to do anything with the play command. I am using java version 20.

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
> No such host is known (www.youtube.com)

Your configured DNS server seems to sometimes fail. Try using a different DNS server, such as Cloudflare's `1.1.1.1` or Google's `8.8.8.8`.

**Comment by MichailiK** [comment]
You'd need to consult the documentation for your OS. It should be pretty easy to google though, e.g. "Change DNS server Windows" or "Change DNS server Ubuntu."

This issue seems stale, so I'll close it for now. Please open a [new troubleshooting discussion](<https://github.com/jagrosh/MusicBot/discussions/new?category=troubleshooting>) or join the support Discord server (found in the README) if you're still experiencing trouble.
