### ISSUE TITLE
[Bug Report] No certificates

### ISSUE THREAD

**Issue by MineTurtlee** [jagrosh/MusicBot#1399]
### Bug Description

![image](https://github.com/jagrosh/MusicBot/assets/97010924/cbcab641-f485-4e91-be48-505013b39634)
See this and help!

### Steps to Reproduce

1.use Repl
2.set it fully up
3. done, test!

### Expected Result

I just expected that the bot would eventually be online

### Debug Output

Online hosting: Replit
JMusicBot ver.: 0.3.9

### Additional Info

nah

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
Replit is [explicitly discouraged as hosting](https://jmusicbot.com/hosting/#dont-use-this-hosting). Generally, we expect you to run JMusicBot in a machine/environment you have full control over (i.e. computer, VPS etc). We have no intention to write code that caters towards the limited environments found in replit & other free hosting services.
