### ISSUE TITLE
Suggestion: Radio

### ISSUE THREAD

**Issue by Z3USS** [jagrosh/MusicBot#14]
Make a command so that the Admin uses to deichar the bot in Radio Mode, it would be playing a Music live Streaming from Youtube, or playing a song via http example http://streaming307.radionomy.com:80/RadioHunter-TheHitzChannel
As long as you have Radio on it will be playing even if you are alone on the channel

**Comment by jagrosh** [comment]
You can make a playlist (in the Playlists folder) with the stream link as the only entry in the playlist, then set that playlist to be the default for the server, and then it will automatically join the set voice channel (`setvc`) at startup and beginning playing from the stream.
