### ISSUE TITLE
support spotify

### ISSUE THREAD

**Issue by Mishary0** [jagrosh/MusicBot#140]
can you make the bot support spotify its gonna be more then better

**Comment by spotlightishere** [comment]
Sadly, Spotify isn't open and this would be extremely hard to do. Check out #66 and #82 for some more information.

A good alternative is playing the same songs off YouTube or similar sites.

**Comment by jagrosh** [comment]
Like @spotlightishere mentioned, this is not possible. Check out the [wiki page on Playlists](https://github.com/jagrosh/MusicBot/wiki/Playlists) for a workaround to convert a spotify playlist into a youtube playlist.
