### ISSUE TITLE
[Feature Request] Command List

### ISSUE THREAD

**Issue by Emtecsus** [jagrosh/MusicBot#1405]
### Is your feature request related to a problem? Please describe.

It would be really cool if the bot had a prefix to show all the available command of the bot, since when you try to use it, discord automatically tries to use an already existent bot that has a similar prefix to run the command.

### What is your ideal solution to the problem?

A list of commands for the bot

### How would this feature be used?

If you type the prefix of the bot, discord will show you all the possible commands of the bot

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by Matdbx10** [comment]
try help

**Comment by jagrosh** [comment]
You are describing the `help` command, which already exists
