### ISSUE TITLE
[Bug Report] Bot won't respond to anything that isn't @botname

### ISSUE THREAD

**Issue by Sir-Lags-A-Lot** [jagrosh/MusicBot#1409]
### Bug Description

What the title says, I'll change the prefix to something like ! but it won't respond to it. I've tried using the command and the config but nothing works. The server config does say ! is the prefix. I've restarted it after making changes of course, even when using commands. Even after changing it, it still responds to the default of @botname. Everything else about the bot works just fine, its just this prefix issue. I'm lost at this point.it's

### Steps to Reproduce

1. Change prefix using the prefix command or use the config to use ! as the prefix
2. Restart bot
3. Try using !help

### Expected Result

Not sure if the expected result here is with the bug occurring or if working correctly. With the bug occurring, it doesn't respond to the set prefix and still only responds to @botname. If working correctly, it would respond to something such as !help.

### Debug Output

```
System Properties:
  java.version = 17.0.7
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 17
  java.runtime.name = OpenJDK Runtime Environment

### Additional Info

_No response_

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
https://jmusicbot.com/getting-a-bot-token/

**Comment by Sir-Lags-A-Lot** [comment]
Thank you very much! I guess I looked over that part.
