### ISSUE TITLE
Can't Be Hosted To Heroku

### ISSUE THREAD

**Issue by mozartrafikt** [jagrosh/MusicBot#141]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [x] I am running the [latest version][download]: [![Release][release]][download]
- [x] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [x] I have read through the [planned and suggested features][features]

## Issue

I Can't Host To Heroku, How To Host This

### Issue Type

- [x] Feature Request

### Description

Hello! I Love My JMusic BOTS With The Features, But I Can't Host This To Make It Stay Online.
So, How To Host It On Heroku (Java Supported)
Pls Give Help! By Making a Tutorial... :(

**Comment by hardlyneutral** [comment]
I have it set up and running just fine on Heroku with the JVM Common buildpack. I'm using a single hobby worker dyno. Here is what I have in my procfile:

```
worker: java -jar JMusicBot-0.1.2.jar -nogui
```

**Comment by mozartrafikt** [comment]
ok thx

**Comment by mozartrafikt** [comment]
no need any more files? like package.json, maybe

**Comment by mozartrafikt** [comment]
can i have JMusic Bot "pom.xml" files?
