### ISSUE TITLE
Heroku Deploy Failed

### ISSUE THREAD

**Issue by ghost** [jagrosh/MusicBot#143]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [x] I am running the [latest version][download]: [![Release][release]][download]
- [x] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [x] I have read through the [planned and suggested features][features]

### Issue Type

- [x] Bug Report
- [x] Feature Request

### Description

Failed To Host On Heroku

**Comment by mozartrafikt** [comment]
I Just Have Done Follows The Step By Adding File "Procfile" with the worker code.

When I Deploy Its Fail Again!
-----> App not compatible with buildpack: https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/java.tgz
       Could not find a pom.xml file! Please check that it exists and is committed to Git.
       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
 !     Push failed

**Comment by hardlyneutral** [comment]
You shouldn't need a pom.xml file. My directory structure is as follows:

```
.gitignore
JMusicBot-0.1.2.jar
Procfile
README.md
config.txt
serversettings.json
```

It sounds like you may have not set up the buildpack correctly. I'm using heroku/jvm.

**Comment by krcore04** [comment]
putting pom.xml file in repository fixed it for me

**Comment by jagrosh** [comment]
Heroku is not intended to be used for services like this, as it doesn't allow writing files. I'd recommend switching to a different VPS provider.

**Comment by KGTasa** [comment]
> putting pom.xml file in repository fixed it for me

what did you put i that file?
