### ISSUE TITLE
[Bug Report] File Reading Issue

### ISSUE THREAD

**Issue by Circuitella** [jagrosh/MusicBot#1430]
### Bug Description

Bots Not Playing MP3's Anymore

### Steps to Reproduce

1. Tell It To Play A MP3 Or Any File It Supports
2. watch it not work for somereason

### Expected Result

MP3 Should Have Played No Problem

### Debug Output

[20:17:39] [WARN] [NativeResourceHolder]: Should have been closed before finalization (com.sedmelluq.discord.lavaplayer.natives.mp3.Mp3Decoder).

### Additional Info

My friends are complaining ahhh

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
There have been several updates since this issue was posted, several of which have changed the lavaplayer version. If you are still encountering this issue, feel free to re-open this issue, ideally providing logs as well.
