### ISSUE TITLE
[Bug Report] Puzzle Pirates?

### ISSUE THREAD

**Issue by IbbyWondrous** [jagrosh/MusicBot#1431]
### Bug Description

Not sure if this is a Discord issue or a bot issue, but I thought I'd let it be known that currently whenever I run the bot, Discord registers it as if I'm playing 'Puzzle Pirates'. I know it's the bot cause when I stream it it streams the console, and it goes away when I close it. 

It's weird.

![image](https://github.com/jagrosh/MusicBot/assets/87488482/a0570795-85bb-4310-a97c-e6de57e3b548)
![image](https://github.com/jagrosh/MusicBot/assets/87488482/2bdef586-bdc7-4df4-88c1-1ec347c09485)
![image](https://github.com/jagrosh/MusicBot/assets/87488482/470f2736-f4e6-435a-904d-cd6f3ab6eb02)

### Steps to Reproduce

Opened the music bot console. 

### Expected Result

Not to be playing Puzzle Pirates when I run the bot.

### Debug Output

(idk how to do that 😬) ver 0.3.9

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by ephdagadu** [comment]
Also experiencing the same issue for at least two days and can confirm the bug description. I tried switching JREs, looking through Discord for options, and looking at my local config file, but I'm still "playing" puzzle pirates.

**Comment by jagrosh** [comment]
Is this still happening?

**Comment by IbbyWondrous** [comment]
> Is this still happening?

It hasn't happened for a while, no. I think it was an issue on discord's end.

**Comment by jagrosh** [comment]
Excellent, feel free to reopen this issue if it happens again
