### ISSUE TITLE
[Bug Report] Songs gets add randomly on queue

### ISSUE THREAD

**Issue by admonxetrii** [jagrosh/MusicBot#1436]
### Bug Description

The songs get added to queue randomly and once the latest added music is plays the further queues gets skipped

### Steps to Reproduce

1. Play a song
2. add new songs to queue
3. After a while if another song is added, gets queued in random position
4. Once the latest song is played
5.queues gets skipped

### Expected Result

Queue should be added serially.

### Debug Output

```
System Properties:
  java.version = 17.0.8.1
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 17
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 17.0.8.1+1
  java.specification.version = 17
  os.arch = amd64
  os.name = Windows Server 2019

JMusicBot Information:
  Version = 0.3.9
  Owner = 425334382153302017
  Prefix = +
  AltPrefix = null
  MaxSeconds = 0
  NPImages = true
  SongInStatus = false
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.78

Runtime Information:
  Total Memory = 116
  Used Memory = 89

Discord Information:
  ID = 1148488221232201762
  Guilds = 4
  Users = 11
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
Songs added to the queue are linear per-person, but if multiple people are adding the songs, their entries will be sorted such that no single person can hog the queue.
