### ISSUE TITLE
Invalid prefix in channel title

### ISSUE THREAD

**Issue by parapauk** [jagrosh/MusicBot#144]
Hi,

I've set my own prefix to !, but the topic in the channel where the bot is setting the music title says ""Use "$help" for a list of commands..."

**Comment by jagrosh** [comment]
It sounds like someone manually wrote that there, because the bot does not post any such message to channel topics.

**Comment by parapauk** [comment]
Yes it does. It has an option to display the currently playing info in the channel topic.

**Comment by jagrosh** [comment]
Just as an example, here is the topic from my development server:

![image](https://i.imgur.com/S0O2E5y.png)

The part I've highlighted was written manually by me; only the top part (song name/length) is controlled by the bot. The lower portion is not sent nor affected by the bot.
