### ISSUE TITLE
Playing local files searches for online url instead of local

### ISSUE THREAD

**Issue by RKosmik** [jagrosh/MusicBot#1442]
### Bug Description

Using the play command the bot attempts to search online for a URL instead of using the local pathing url. I tried many times using mp3, wav, using different bitrate and such and nothing works.

### Steps to Reproduce

1. Use the play command ie "!!"
2. Paste a local url path to your song ie ""C:\Users\name\Downloads\test.wav""
3. The bot plays a youtube url.

### Expected Result

I want the bot to use my local path url not an online url.

### Debug Output

Using Windows 11
JMusicBot version 0.3.9

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
Try using `/` instead of `\` and make sure there isn't anything else in the command. If that still isn't working, please take a screenshot of the command you are trying to run.

**Comment by RKosmik** [comment]
Hey so I noticed you said not to have anything else in the command and I realized there were comma's in the url. When you right click a file and select "Copy to file path" it automatically adds comma's to the url. So I deleted the comma's and it worked flawlessly. Thank you! I got it working. Cheers and thanks for everything you do!
