### ISSUE TITLE
[Feature Request] [p]stream und Extended Permission system

### ISSUE THREAD

**Issue by MrUnknownDE** [jagrosh/MusicBot#145]
Hi, 

I wanted to ask. Is it actually possible that with [p]play only the Youtube and Soundcloud can be played and with [p]stream the MP3 stream can be played. Oh and will there be an extended Permission system?

Best regards
Johannes

*[p] = Prefix

**Comment by MrUnknownDE** [comment]
"[p]np" is not updated as it is "[p]nowplaying"

*[p] = Prefix

**Comment by jagrosh** [comment]
Setting a maximum time limit in the config will prevent streams from being played. Other than that, I don't see a need to differentiate them when the `play` command can handle songs as well as streams.

If you have more specific suggestions for a permissions system, feel free to open an issue with the detailed suggestion, or join my development server [here](https://discord.gg/0p9LSGoRLu6Pet0k).
