### ISSUE TITLE
[Feature Request] Add config file option: disable/enable channel topic status update

### ISSUE THREAD

**Issue by Poki-Pancake** [jagrosh/MusicBot#1456]
### Is your feature request related to a problem? Please describe.

The bot constantly changes the channel description with the current playing music. Unlike the bot user's status. This feature cannot be turned off.

### What is your ideal solution to the problem?

Provide an option to disable the channel topic status in the config file.

### How would this feature be used?

1. Edit config.txt
2. Find said option
3. Change it to `true` or `false`

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [x] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
> This feature cannot be turned off.

The bot does not attempt to do this if it lacks the `Manage Channel` permission, which it shouldn't have. Also make sure you're not giving the bot `Administrator` as there is no need for it to have that permission either.

Due to how ratelimits work, this feature is going to be entirely removed in the future, so adding a config value for this is also not needed.

**Comment by PHV08** [comment]
> > This feature cannot be turned off.
> 
> The bot does not attempt to do this if it lacks the `Manage Channel` permission, which it shouldn't have. Also make sure you're not giving the bot `Administrator` as there is no need for it to have that permission either.
> 
> Due to how ratelimits work, this feature is going to be entirely removed in the future, so adding a config value for this is also not needed.
actually thats wrong

**Comment by jagrosh** [comment]
Closing as disabling this is already possible, and the entire feature will be removed in the future anyway
