### ISSUE TITLE
Nowpaying command is not working?

### ISSUE THREAD

**Issue by dralex47** [jagrosh/MusicBot#146]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [ ✓] I am running the [latest version][download]: [![Release][release]][download]
- [ ✓] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [ ✓] I have read through the [planned and suggested features][features]

### Issue Type

- [ ✓] Bug Report
- [ ] Feature Request

### Description

I was on a server and i was a staff member but now i am not and when i type in nowpaying it say ![image](https://cdn.discordapp.com/attachments/348290216705916930/419634734663204864/gg.png)
But it works on my own server fine why is this happend?
![image](https://user-images.githubusercontent.com/34045802/36940327-d3305e52-1f38-11e8-8623-cbd3e0994f41.png)
![image](https://cdn.discordapp.com/attachments/348290216705916930/419635898670383116/ffd.png)
![image](https://cdn.discordapp.com/attachments/348290216705916930/419634734663204864/gg.png)

**Comment by dralex47** [comment]
#59

**Comment by jagrosh** [comment]
Does the bot have the Embed Links permission in the channel you're running the command in?

**Comment by dralex47** [comment]
yes

**Comment by jagrosh** [comment]
Can you see if this is fixed as of the [latest release, 0.1.3](https://github.com/jagrosh/MusicBot/releases/latest)

**Comment by jagrosh** [comment]
Closing as this has been untouched for months and the [latest release](https://github.com/jagrosh/MusicBot/releases/latest) overhauls a lot of the now-playing logic.
