### ISSUE TITLE
Bot will join AFK channel and 'play' music

### ISSUE THREAD

**Issue by Amziraro** [jagrosh/MusicBot#147]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [x] I am running the [latest version][download]: [![Release][release]][download]
- [x] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [x] I have read through the [planned and suggested features][features]

### Issue Type

- [x] Bug Report

### Description

I can request the bot to play music for me even when I am in the AFK channel of my server and obviously won't be able to hear anything. 

![Me in AFK with the bot](https://i.imgur.com/zEc57Qy.png)

This is not desired behavior as its pretty useless and prevents other people from using the bot. 

It would be better if the bot would not play music in designated AFK channels, and more generally, not play music in channels where it can't use voice at all.

**Comment by jagrosh** [comment]
It already will not join channels in which it doesn't have permission to play audio, and it will not accept requests for songs from users who are not currently listening (not deafened).

However, there may be special handling on the client end for the AFK channel that might need to be accounted for.
