### ISSUE TITLE
[Bug Report] Music stops after 1 or 2 times of playback in repeat mode

### ISSUE THREAD

**Issue by SouravPrakash5** [jagrosh/MusicBot#1472]
### Bug Description

in console the error is com.sedmelluq.discord.lavaplayer.source.youtubeaudiotrack.processsstatic(youtubeaudiotrack.java:57)
                                    com.sedmelluq.discord.lavaplayer.source.youtubeaudiotrack.processs(youtubeaudiotrack.java:49)

### Steps to Reproduce

Try fixing it by adding loop mode usage in it 

### Expected Result

I was hearing it for some time in first time it occured after first music only then i used play command it joined vc then left instantly with that error. Second time it occured after 3 to 4 hours whiled i looped a single song

### Debug Output

windows 10, jmusicbot 0.3.9

### Additional Info

And Is repeat mode for repeating a song 24/7 or only play 2 times then leave

### Checklist

- [x] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
That's because occassionally JMusicBot 0.3.9 silently fails to play a track & silently removes it from the queue. We're tracking playback issues in #1537 at the moment, and hope to release 0.4.1 soon that resolves this.

I'll close this issue for now, as this very closely relates to #1537
