### ISSUE TITLE
[Bug Report] Songs loops when added by playnext option

### ISSUE THREAD

**Issue by kawior23** [jagrosh/MusicBot#1476]
### Bug Description

song added by playnext command is being played every second song if there is something in the queue from another user

### Steps to Reproduce

1. "User A" loads the playlist by 'play playlist XYZ' which contains 50 songs
2. "User B" wants to play his song so he is using 'playnext [NAME]'
3. Song successfully added to a queue in the first position
4. Song is being played, once finished - bot continues to play the next song from "User A's" playlist but.. (and that's where the error occurs) the song that "User B" requested as 'playnext' from step 2, bot will play AGAIN and it will continue to be played every second song

hopefully, that's makes sense

### Expected Result

Song from 'playnext' being played only once when there is a playlist in the queue already

### Debug Output

n/a

### Additional Info

Feel free to message me if it's still unclear. All in all, love your bot, very good work, appreciate it a lot.
It's being used on 2 community servers (circa 50 people) as a main music bot but that's the glitch users spotted

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
This is because you have repeat mode enabled; when a song ends and repeat mode is enabled, it is put back into the queue as if the first person attempted to play it again. Since this person doesn't currently have any songs, their song is placed second in the queue (since there is only one other person with songs in the queue, and the fair queue system prevents any one user from hogging the queue by having more songs ahead of anyone else).

**Comment by kawior23** [comment]
Thank you for explaining :) yeah repeat mode is on for a playlist with 500+ songs so there is no way of getting around it without turning off repeat mode?
