### ISSUE TITLE
autoplaylist: admin instead of bot owner

### ISSUE THREAD

**Issue by Seklfreak** [jagrosh/MusicBot#148]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [X] I am running the [latest version][download]: [![Release][release]][download]
- [X] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [X] I have read through the [planned and suggested features][features]

### Issue Type

- [ ] Bug Report
- [X] Feature Request

### Description
The autoplaylist feature can only be modified by the bot owner, not the server admins. I think server admins should be able to set an autoplaylist, since it's a server specific feature. Maybe I'm missing something?

**Comment by jagrosh** [comment]
This has been added to the [planned features list](https://github.com/jagrosh/MusicBot/projects/1)
