### ISSUE TITLE
Keeping a backup of the queue in a file

### ISSUE THREAD

**Issue by Shylight** [jagrosh/MusicBot#149]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [x] I am running the [latest version][download]: [![Release][release]][download]
- [x] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [x] I have read through the [planned and suggested features][features]

### Issue Type

- [ ] Bug Report
- [x] Feature Request

### Description

It is unfortunate, but sometimes the bot encounters problems it can't recover from. Losing the entirety of queue in such cases can be rather disheartening to users.

**Comment by jagrosh** [comment]
While I see merit in this idea, I think a more worthwhile goal would be to fix any problems it can't recover from.

**Comment by Shylight** [comment]
Some problems are outside the scope of the bot though. The machine it's running on might require a restart, power outage, etc. I also suspect that the last issue I encountered that led to the queue being lost was caused by Discord itself rather than the bot (but I don't have enough data right now). 

And users get rather sad when losing stuff they queued.

**Comment by jagrosh** [comment]
This is now on the [planned features list](https://github.com/jagrosh/MusicBot/projects/1).
