### ISSUE TITLE
 Suggestion: !clean command

### ISSUE THREAD

**Issue by Bobbysx** [jagrosh/MusicBot#15]
Could we get a command (!clean) that cleans up all the text "spam" the bot leaves after intensive use by multiple users?

**Comment by vitalkanev** [comment]
DJ's can use `!remove ALL` (Replace `!` with you prefix) on the server with the bot to clean queue. No need to add this

**Comment by Bobbysx** [comment]
@jagrosh That would be great.. Thanks!

**Comment by thebeastgamer25** [comment]
@jagrosh was this ever added?

**Comment by jagrosh** [comment]
This is still on the planned features list but has not been added yet.

**Comment by jagrosh** [comment]
Closing this; it is still listed on the [planned features list](https://github.com/jagrosh/MusicBot/projects/1) in the form of auto-deleting users' and the bot's messages.
