### ISSUE TITLE
Make It More Customizable

### ISSUE THREAD

**Issue by phanicowner** [jagrosh/MusicBot#152]
Yes, I know it looks weird but let me explain. for example, make people be able to make the help setting customization. like, in the config.txt there should be an ability to make commands in embed and to add a description to whatever they want so instead of For additional help, contact Kulans#1232. 

We can just put whatever there. maybe, make the playlist and songs more local. for example, make them like accept Put as many mp3. and, then there's a command called w>local start *playlist name* or just in general load one song from there. 

I know this is long but I assure you this will work out great.

**Comment by jagrosh** [comment]
Please use the issue template. Also, this is a very vague suggestion; it would be more helpful if you broke this up into several smaller suggestions with more-specific details.
