### ISSUE TITLE
[Bug Report] Running as a service trough NSSM doesn't work

### ISSUE THREAD

**Issue by adriaN7812** [jagrosh/MusicBot#1522]
### Bug Description

![image](https://github.com/jagrosh/MusicBot/assets/53578027/7a173215-9b4a-4d6f-b01a-e528f1ca758c)

### Steps to Reproduce

Did all the steps from the instuctions

### Expected Result

Expected to work

### Debug Output

.

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
Do you have Java 11 installed, and is it the default Java version?

**Comment by adriaN7812** [comment]
> Do you have Java 11 installed, and is it the default Java version?
![image](https://github.com/jagrosh/MusicBot/assets/53578027/1d332cad-a1fd-4f49-9e4e-5f088e901be2)
And considering the bot works without it being a service i didnt think that could be the issue

**Comment by fossmanbill** [comment]
The provided command in the guide "nssm install JMusicBot java -jar JMusicBot.jar" is lacking. My jar file had a version appended to the end of it, like this: "JMusicBot-0.4.0.jar". You can edit the service by "nssm edit JMusicBot" and replace the values there. Or you could remove the service and add it with the correct command: "nssm install JMusicBot java -jar JMusicBot-0.4.0.jar"

I also changed the working directory part in the nssm edit window, just in case. It was C:\windows or something like that and that felt like that could cause problems. I hope this helps

**Comment by fossmanbill** [comment]
Can you type "nssm edit JMusicBot" and show a screenshot from there?

**Comment by digitalcontemplation** [comment]
>  I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)

I had the same issue before and found this to be my solution:

[chilux00](https://github.com/chilux00) commented [on Oct 29, 2023](https://github.com/jagrosh/MusicBot/issues/1444#issuecomment-1784390871)

>-  Run nssm edit JMusicBot to bring up the GUI for editing the service. You should see three editable text fields pop up.
>- For the first field, "Path", set this to the path of your java.exe. This is probably in your program files so you can find it in your C:\ drive.
>- For the second field "Startup Directory", set this to the path of the working directory folder (i.e the folder where your JMusicBot file is), something like C:\Users\<User Name>\Documents\<Folder Name>
>- For the last field "Arguments", you want to append -jar and set it to the exact path of your music bot .jar file, so something like -jar C:\Users\<User Name>\Documents\<Folder Name>\JMusicBot-0.3.9.jar. If you've renamed your .jar file, change this accordingly.

https://github.com/jagrosh/MusicBot/issues/1444#issuecomment-1784390871

**Comment by adriaN7812** [comment]
Fixed it but don't know exactly whcih change that i made that fixed it.
I changed to Java 11 from Oracle , and did the nssm edit changes.
