### ISSUE TITLE
[Bug Report] 0.4.0 bot joins and disconnects right after

### ISSUE THREAD

**Issue by ka1ko** [jagrosh/MusicBot#1529]
### Bug Description

Hasnt been working for few weeks now. Soundcloud works fine

### Steps to Reproduce

1. Play a youtube song 

### Expected Result

Bot to stay in the channel and play some music

### Debug Output

```
System Properties:
  java.version = 11.0.22
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 11
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 11.0.22+7
  java.specification.version = 11
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.4.0
  Owner = 377071650438381568
  Prefix = ++
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = true
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 727959e9f621fc457b3a5adafcfffb55fdeaa538-SNAPSHOT

Runtime Information:
  Total Memory = 512
  Used Memory = 79

Discord Information:
  ID = 1152300963873423400
  Guilds = 1
  Users = 2
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by Gdebest69** [comment]
I have the same issue

**Comment by meganizer** [comment]
Same issue here

**Comment by ProJakob** [comment]
Same issue

**Comment by ProJakob** [comment]
I was able to fix the issue by going back to 0.3.9, something seems to have changed in 0.4.0 that breaks playback..

**Comment by Seba244c** [comment]
Same issue. My bot worked fine on 0.4.0 for at least a week but now it doesn't work. Changing back to 0.3.8 worked for me

**Comment by kndrckjvr** [comment]
same issue here. reverting from other version is working.

**Comment by Juustar** [comment]
Having the same issue, though the bot does play a small handful of songs first before seemingly skipping through the rest and disconnecting. Reverting to the previous version does seem to work

**Comment by kndrckjvr** [comment]
so in discord they are saying the problem is with the lavaplayer.

**Comment by Springpaw** [comment]
````
System Properties:
  java.version = 22
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 22
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 22+36-2370
  java.specification.version = 22
  os.arch = amd64
  os.name = Windows 11

JMusicBot Information:
  Version = 0.4.0
  Owner = 163452507450769419
  Prefix = !!
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = true
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 727959e9f621fc457b3a5adafcfffb55fdeaa538-SNAPSHOT

Runtime Information:
  Total Memory = 48
  Used Memory = 28

Discord Information:
  ID = 1131635531000840292
  Guilds = 4
  Users = 2
````

adding my debug

**Comment by ka1ko** [comment]
> so in discord they are saying the problem is with the lavaplayer.

Any fix ? Or can we even do something about it ?

**Comment by DenisBae** [comment]
Can confirm,  going back to 0.3.9 fixed it

**Comment by ProJakob** [comment]
Issue seems to be caused by lavaplayer during loading of a YouTube Video, there has probably a change on either end causing it to error out and disconnecting the bot. The issue seems to also be exclusive to YouTube, mpeg streams as well as other sources seem to work perfectly fine.

**Comment by ProJakob** [comment]
> > so in discord they are saying the problem is with the lavaplayer.
> 
> Any fix ? Or can we even do something about it ?

Your best bet right now is avoiding 0.4.0 and instead using 0.3.9 since its the last release that works fine.

**Comment by MrZoyo** [comment]
Have same issue

**Comment by ThePowerOfElectricity** [comment]
Another occurence here. Same issue, same fix.

It's probably best to avoid 0.4.0 for now altogether.

**Comment by MrGundum** [comment]
Same problem here, 0.3.9 works fine

**Comment by clifford64** [comment]
I believe it's an issue on Youtube's end and the version of lavaplayer that is currently being used. It's my understanding that the method lavaplayer was using to access YouTube has broken because of a change on YouTube's end. Updating the lavaplayer dependency to the latest snapshot seems to have fixed the issue for me.

**Comment by TacticalLaptopBag** [comment]
Same problem here, I get no logs about any problems. Bot says it's playing, and shows the correct name of the song, but just joins and then immediately leaves.

Downgrading to 0.3.9, I do not have this problem.

**Comment by ProJakob** [comment]
> I believe it's an issue on Youtube's end and the version of lavaplayer that is currently being used. It's my understanding that the method lavaplayer was using to access YouTube has broken because of a change on YouTube's end. Updating the lavaplayer dependency to the latest snapshot seems to have fixed the issue for me.

That still doesn't explain why downgrading to 0.3.9 fixes the problem since that is also downgrading Lavaplayer

**Comment by clifford64** [comment]
> > I believe it's an issue on Youtube's end and the version of lavaplayer that is currently being used. It's my understanding that the method lavaplayer was using to access YouTube has broken because of a change on YouTube's end. Updating the lavaplayer dependency to the latest snapshot seems to have fixed the issue for me.
> 
> That still doesn't explain why downgrading to 0.3.9 fixes the problem since that is also downgrading Lavaplayer

I believe 0.3.9 uses an older lavaplayer snapshot and 0.4.0 uses a newer lava player snapshot that might affected by the issue. 

Using latest lavaplayer snapshot fixed it for me.

**Comment by siasmj** [comment]
> Same issue here, downgrading to 0.3.9 resolved issue.

Same here as well.

**Comment by Peppie-ZA** [comment]
updating to java 11 fixed it for me
https://adoptium.net/en-GB/temurin/releases/?version=11&package=jre

**Comment by MichailiK** [comment]
For consolidation purposes, we're going to continue tracking this bug in #1537. My [latest comment on that issue](https://github.com/jagrosh/MusicBot/issues/1537#issuecomment-2071810856) has a temporary solution for anyone who can't wait for 0.4.1 to release
