### ISSUE TITLE
Longer reconnect time.

### ISSUE THREAD

**Issue by Boostio9** [jagrosh/MusicBot#153]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [x] I am running the [latest version][download]: [![Release][release]][download]
- [x] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [x] I have read through the [planned and suggested features][features]

### Issue Type

- [ ] Bug Report
- [x] Feature Request

### Description

Allow a long reconnect time when this internet goes. this is an issues with me as my internet goes often and the bot usually stops retying before the internet is back. just make it so i tyres to reconnect for longer

**Comment by jagrosh** [comment]
The bot shouldn't stop retrying, it should repeatedly attempt to reconnect (with longer backoffs each time) until you close it. Also, if you don't have stable internet, you should look into renting a VPS and hosting there.

**Comment by Boostio9** [comment]
it doesnt this is what happens after it retres one or twice 
![capture](https://user-images.githubusercontent.com/31994714/38465966-f3b3fa7e-3b19-11e8-8e09-f7ad42617cc9.PNG)

**Comment by jagrosh** [comment]
When you fill out the issue template, please make sure you actually meet all of the checkboxes. You checked `I am running the latest version` but your screenshot isn't JMusicBot at all, it's some python bot.
