### ISSUE TITLE
[Feature Request] Add a logging file for developers

### ISSUE THREAD

**Issue by walidbouachir** [jagrosh/MusicBot#1531]
### Is your feature request related to a problem? Please describe.

Hello,

I don't know if there's a logging feature for this, but would be great if you add one (saving into a text file for example), just in case something goes wrong, we can check the logging.

Thank you!

### What is your ideal solution to the problem?

Add logging into .txt or .log file

### How would this feature be used?

1. Start the bot
2. Log into file in case of errors

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MrZoyo** [comment]
If you are using bot with command, you can use nohup and output the logging to a specified file.

**Comment by walidbouachir** [comment]
> If you are using bot with command, you can use nohup and output the logging to a specified file.

Would be easier to read from a file rather than linux shell, no?

**Comment by MichailiK** [comment]
I believe the current method of logging to the console is sufficient. We will be adding an option to set a logging level though, so more information gets logged.

**Comment by jagrosh** [comment]
You can set the log level as of 0.4.1 and you could redirect or tee console logs to a file. Technically, you could also open up the jar and change the logback configuration, although I wouldn't recommend doing that. Regardless, I don't think we need any changes for this to be possible.
