### ISSUE TITLE
Suggestion: Addition to the Local Files Playlist Function

### ISSUE THREAD

**Issue by Takiama** [jagrosh/MusicBot#156]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [ x] I am running the [latest version][download]: [![Release][release]][download]
- [ x] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [ x] I have read through the [planned and suggested features][features]

### Issue Type

- [ ] Bug Report
- [X ] Feature Request

### Description
As far as I can tell, your Bot is currently only able to import individual songs via a direct file-path, however this brings about a major inconvenience when trying to import a large amount of separate music, due to having to go through one-by-one. I would greatly appreciate it if the capability to easily load multiple files be included into your software. One way that this might be done would be to make it so that the end-user could specify a folder's file-path, and then every compatible file in that folder would be imported. 
Thanks for this great bot

**Comment by Artuto** [comment]
https://github.com/jagrosh/MusicBot/wiki/Playlists

**Comment by dj3hac** [comment]
Yes please! I have a huge library...

Just being able to set a directory and have the program crawl it and it's sub directories would be great!

**Comment by jagrosh** [comment]
Despite seeming trivial, this is not actually a trivial feature. Handling nested folders, permissions, file types, and configuration each present several new issues to tackle.

At present, I think your best solution would be to run a command-line script from the home folder, maybe something like (if your songs were located in a folder called Songs):
```
ls Songs/*.mp3 > songs.txt
```
And then move that file into the Playlists folder.

**Comment by jagrosh** [comment]
Some of the aforementioned concerns (permissions, file types) are still valid, so I think moving forward the solution to this is to manually generate the playlist. There's a page on the wiki - [Advanced Playlist Generation](https://github.com/jagrosh/MusicBot/wiki/Advanced-Playlist-Generation) - that contains some methods for generating such a playlist. These will work even on large libraries of songs, and is overall a safer method of handling this.
