### ISSUE TITLE
Bot is stuck in defen mode.........................

### ISSUE THREAD

**Issue by captainant43099** [jagrosh/MusicBot#1563]
### Bug Description

.............................. and not able to play any music and i checked my server running the config file and it shows tons of things and somthing taking 600 seconds on googles end 
![Capture](https://github.com/jagrosh/MusicBot/assets/75140166/4044b43c-330d-4236-b1a4-067408c39b39)

### Steps to Reproduce

idk whar this is 

### Expected Result

the bot to say something in discord.

### Debug Output

System Properties:
  java.version = 17.0.11
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 17
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 17.0.11+9
  java.specification.version = 17
  os.arch = amd64
  os.name = Windows 10

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by Random45israndom** [comment]
I also have this exact problem, how do I solve it?
