### ISSUE TITLE
[Feature Request] an embed like the np command but when you add a song

### ISSUE THREAD

**Issue by BlobIsBack** [jagrosh/MusicBot#1572]
### Is your feature request related to a problem? Please describe.

i think the default messages that appears when you add a song is not very pretty

### What is your ideal solution to the problem?

an embed that looks kinda like the nowplaying one

### How would this feature be used?

when you add a song instead of the current message it's a cool embed

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
In JMusicBot, embeds are used for lists and/or interactive elements (like the `search`, `settings` and `queue` commands.) Using an embed for the `play` command wouldn't make much sense. I believe the space an embeds wastes wouldn't be of much benefit for just writing a simple "added something to the queue" message. So I'm confused about what the purpose is to use embeds for the `play` command (or almost any other command really?)

**Comment by BlobIsBack** [comment]
> In JMusicBot, embeds are used for lists and/or interactive elements (like the `search`, `settings` and `queue` commands.) Using an embed for the `play` command wouldn't make much sense. I believe the space an embeds wastes wouldn't be of much benefit for just writing a simple "added something to the queue" message. It makes sense for more complex responses, and we do use embeds in those. So I'm confused about what the purpose is to use embeds for simple responses like the `play` command.

i think it looks good, maybe wiyth the thumbnail it will be even better

**Comment by jagrosh** [comment]
In general we try to avoid excessive embeds, as they take up a lot more space, and they render really poorly in certain modes (compact mode, for example)
