### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by OzoneHelix** [jagrosh/MusicBot#158]
I had wanted to add a suggestion but am unsure how to do so I had wondered if a dice rolling command would be something interesting to add to the bot for example a group of friends maybe playing DND while using the bot and for that time a dice rolling command might be useful to have sorry for not putting this up correctly I didn't know where I could put a proper suggestion

**Comment by jagrosh** [comment]
Only music-related features will be considered. For dice-rolling, I would recommend seeking out a different bot.
