### ISSUE TITLE
Bot won't read config.txt file when starting through systemctl on Ubuntu Server 16.04 LTS

### ISSUE THREAD

**Issue by OrangeFlare** [jagrosh/MusicBot#159]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [X] I am running the [latest version][download]: [![Release][release]][download]
- [X] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [X] I have read through the [planned and suggested features][features]

### Issue Type

- [X] Bug Report
- [ ] Feature Request

### Description

When starting MusicBot through systemctl the bot complains about no API Token being provided even though the config.txt has the API Token Entered

/etc/systemd/system/musicbot.service
```
[Unit]
Description=MusicBot

[Service]
ExecStart=/usr/bin/java -jar /opt/SpotifyChan/spotifychan.jar -nogui
Type=simple
User=root

[Install]
WantedBy=multi-user.target
```
The System Status Displays the following
```
● musicbot.service - MusicBot
   Loaded: loaded (/etc/systemd/system/musicbot.service; enabled; vendor pres
   Active: failed (Result: exit-code) since Mon 2018-05-21 14:00:02 UTC; 4min 55
 Main PID: 4070 (code=exited, status=1/FAILURE)

May 21 14:00:02 OrangeVM2 java[4070]: Bot Token:
May 21 14:00:02 OrangeVM2 java[4070]: Exception in thread "main" java.util.NoSuchElementException
May 21 14:00:02 OrangeVM2 java[4070]:         at java.util.Scanner.throwFor(Scanner.java:862)
May 21 14:00:02 OrangeVM2 java[4070]:         at java.util.Scanner.next(Scanner.java:1371)
May 21 14:00:02 OrangeVM2 java[4070]:         at com.jagrosh.jmusicbot.Config.prompt(Config.java:310)
May 21 14:00:02 OrangeVM2 java[4070]:         at com.jagrosh.jmusicbot.Config.<init>(Config.java:129)
May 21 14:00:02 OrangeVM2 java[4070]:         at com.jagrosh.jmusicbot.JMusicBot.main(JMusicBot.java:91)
May 21 14:00:02 OrangeVM2 systemd[1]: spotifychan.service: Main process exited, code=exited, status=1/FAILURE
May 21 14:00:02 OrangeVM2 systemd[1]: spotifychan.service: Unit entered failed state.
May 21 14:00:02 OrangeVM2 systemd[1]: spotifychan.service: Failed with result 'exit-code'.
```

**Comment by OrangeFlare** [comment]
Quick Update Tried manually running the command "/usr/bin/java -jar /opt/SpotifyChan/spotifychan.jar -nogui"
no issues

**Comment by jagrosh** [comment]
Is there somewhere you could get the full logs? The first thing that the bot logs is the location from which it is attempting to pull the config file.

**Comment by OrangeFlare** [comment]
no Log Files appear to have been generated?
Are they normally in the same dir as the jar file?

**Comment by jagrosh** [comment]
It prints the logs to the console, you'll need to save what gets printed to console somehow.

**Comment by OrangeFlare** [comment]
I have that in the original request
```
May 21 14:00:02 OrangeVM2 java[4070]: Bot Token:
May 21 14:00:02 OrangeVM2 java[4070]: Exception in thread "main" java.util.NoSuchElementException
May 21 14:00:02 OrangeVM2 java[4070]:         at java.util.Scanner.throwFor(Scanner.java:862)
May 21 14:00:02 OrangeVM2 java[4070]:         at java.util.Scanner.next(Scanner.java:1371)
May 21 14:00:02 OrangeVM2 java[4070]:         at com.jagrosh.jmusicbot.Config.prompt(Config.java:310)
May 21 14:00:02 OrangeVM2 java[4070]:         at com.jagrosh.jmusicbot.Config.<init>(Config.java:129)
May 21 14:00:02 OrangeVM2 java[4070]:         at com.jagrosh.jmusicbot.JMusicBot.main(JMusicBot.java:91)
May 21 14:00:02 OrangeVM2 systemd[1]: spotifychan.service: Main process exited, code=exited, status=1/FAILURE
May 21 14:00:02 OrangeVM2 systemd[1]: spotifychan.service: Unit entered failed state.
May 21 14:00:02 OrangeVM2 systemd[1]: spotifychan.service: Failed with result 'exit-code'.
```

**Comment by OrangeFlare** [comment]
Seems to be complaining it can't receive user input in nogui mode because it's running in a background systemctl process

**Comment by jagrosh** [comment]
That's just the error, I need to see everything that was printed to system out

**Comment by OrangeFlare** [comment]
that's all that was printed to the Console Ill keep looking to see if I can find anything else

**Comment by OrangeFlare** [comment]
![image](https://user-images.githubusercontent.com/19276377/40326925-a1fbe9d0-5d06-11e8-9975-3ac4c94eaf53.png)
config.txt is present in the jar's directory
the user that is executing the commands has full access and permissions to said directory

**Comment by jagrosh** [comment]
Just because its in the jar's directory does not mean that it is in the current working directory of the JVM when run

**Comment by OrangeFlare** [comment]
And like I said when I manually type "/usr/bin/java -jar /opt/SpotifyChan/spotifychan.jar -nogui"
it works fine
only when the program is started from systemctl is breaks

**Comment by jagrosh** [comment]
That's why I need the full logs; the first thing that the logs print out is the location that it is attempting to find the config file.

**Comment by OrangeFlare** [comment]
Gimme just one second I'm gonna try something see if it's not spitting out the full logs

**Comment by OrangeFlare** [comment]
Wasn't looking the the correct directory I fixed this issue by adding 2 lines under the service file
```
[Unit]
Description=SpotifyChan

[Service]
WorkingDirectory=/opt/SpotifyChan
RootDirectory=/
ExecStart=/usr/bin/java -jar /opt/SpotifyChan/spotifychan.jar -nogui
Type=simple
User=root

[Install]
WantedBy=multi-user.target
```
If you don't specify the WorkingDirectory and RootDirectory it uses the User's default home which in this case the user 'root' doesn't have a home directory so java was freaking out

**Comment by byeJohn** [comment]
almost 5 years later and this thread just helped me today! thank you
