### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MajorLOLGaming** [jagrosh/MusicBot#160]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [x] I am running the [latest version][download]: [![Release][release]][download]
- [x] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [x] I have read through the [planned and suggested features][features]

### Issue Type

- [ ] Bug Report
- [x] Feature Request

### Description

I would like to see a "stream" feature. For an example: 

> !stream https://www.youtube.com/watch?v=sKIbH-gXmX0

  or

> !play https://www.youtube.com/watch?v=sKIbH-gXmX0

Thanks! 😄

**Comment by MajorLOLGaming** [comment]
That is not what I meant. I am asking for a way to **_stream_** things **_live_**.

**Comment by jagrosh** [comment]
This is already possible, you just use the regular play command with a stream link.
