### ISSUE TITLE
[Bug Report] Please Can I Form Oracle Without Account?

### ISSUE THREAD

**Issue by Bartosz8291** [jagrosh/MusicBot#1606]
### Bug Description

IT'S AN BUG
IM DOWNLOADING FORM MSI
&...
![image](https://github.com/jagrosh/MusicBot/assets/164915721/e57a5bfc-2358-4047-8f12-405e1ffc874d)

### Steps to Reproduce

1. Can I?

### Expected Result

I have been downloading form oracle AND I HAVE DO MAKE AN ACCOUNT AND THIS STUBID ACC VERIFICATION

### Debug Output

![image](https://github.com/jagrosh/MusicBot/assets/164915721/b93ffbb7-c06c-4ebe-9991-36d696813b50)

### Additional Info

![image](https://github.com/jagrosh/MusicBot/assets/164915721/b02a1045-17a9-4e70-a908-d940cd6e4e00)
the image of bug.

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
You only have 3 MB left on your C: Drive. You need to have 639 MB of space free to install Java.

**Comment by Bartosz8291** [comment]
But it's my Sister pc bruh.

śr., 3 lip 2024, 18:25 użytkownik Michaili K ***@***.***>
napisał:

**Comment by Bartosz8291** [comment]
+ 934 KB FORM 86,4 GB

**Comment by Bartosz8291** [comment]
- [ Itried D:\ ] ]
- [ + I. CANT SELECT!!!] ]

**Comment by MichailiK** [comment]
As the JDK Setup says, it requires free disk space on the C: drive. Beyond that, we unfortunately cannot provide further help much with installing Java on your computer. We only provide assistance with configuring & using JMusicBot.

Please create a [new discussion](https://github.com/jagrosh/MusicBot/discussions/new/choose) or join the Discord support server if you need further help with JMusicBot itself.
