### ISSUE TITLE
Volume ducking when a user speaks

### ISSUE THREAD

**Issue by dj3hac** [jagrosh/MusicBot#161]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [x] I am running the [latest version][download]: [![Release][release]][download]
- [x] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [x] I have read through the [planned and suggested features][features]

### Issue Type

- [ ] Bug Report
- [x] Feature Request

### Description

Suggesting a volume ducking feature to automatically reduce the bot volume level to a set point when a user in the same channel speaks, resuming normal volume afterwards.

**Comment by jagrosh** [comment]
Added `Attenuation` to the [suggested features list](https://github.com/jagrosh/MusicBot/projects/1)
