### ISSUE TITLE
[Bug Report]  Not playing YT

### ISSUE THREAD

**Issue by ejmccurrie** [jagrosh/MusicBot#1618]
### Bug Description

Error when trying to play songs from YouTube. 

### Steps to Reproduce

1. Copy song link from YT or YT music
2. Bot does not play.  

### Expected Result

For the song to play. This was working after the 0.2 update then after a day the issue came back. 

### Debug Output

```
System Properties:
  java.version = 11.0.6
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 11
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 11.0.6+10
  java.specification.version = 11
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.4.2
  Owner = 143807253659516928
  Prefix = !!
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 2.2.1

Runtime Information:
  Total Memory = 62
  Used Memory = 41

Discord Information:
  ID = 1125509987490353162
  Guilds = 3
  Users = 4
```

### Additional Info

14.07 20:15:57 [Bot] [19:15:57] [[ERROR]] [AudioHandler]: Track IeppNGh5-V8 has failed to play
14.07 20:15:57 [Bot] com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video is unavailable
14.07 20:15:57 [Bot] at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:61)
14.07 20:15:57 [Bot] at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
14.07 20:15:57 [Bot] at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
14.07 20:15:57 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
14.07 20:15:57 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
14.07 20:15:57 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
14.07 20:15:57 [Bot] at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
14.07 20:15:57 [Bot] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
14.07 20:15:57 [Bot] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
14.07 20:15:57 [Bot] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
14.07 20:15:57 [Bot] at java.base/java.lang.Thread.run(Unknown Source)
14.07 20:15:57 [Bot] [19:15:57] [[ERROR]] [AudioHandler]: Track 8OxwmvjCDLk has failed to play
14.07 20:15:57 [Bot] com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video is unavailable
14.07 20:15:57 [Bot] at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:61)
14.07 20:15:57 [Bot] at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
14.07 20:15:57 [Bot] at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
14.07 20:15:57 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
14.07 20:15:57 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
14.07 20:15:57 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
14.07 20:15:57 [Bot] at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
14.07 20:15:57 [Bot] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
14.07 20:15:57 [Bot] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
14.07 20:15:57 [Bot] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
14.07 20:15:57 [Bot] at java.base/java.lang.Thread.run(Unknown Source)
14.07 20:15:57 [Bot] [19:15:57] [[ERROR]] [AudioHandler]: Track XszYJDWBuYE has failed to play
14.07 20:15:57 [Bot] com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video is unavailable
14.07 20:15:57 [Bot] at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:61)
14.07 20:15:57 [Bot] at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
14.07 20:15:57 [Bot] at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
14.07 20:15:57 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
14.07 20:15:57 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
14.07 20:15:57 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
14.07 20:15:57 [Bot] at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
14.07 20:15:57 [Bot] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
14.07 20:15:57 [Bot] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
14.07 20:15:57 [Bot] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
14.07 20:15:57 [Bot] at java.base/java.lang.Thread.run(Unknown Source)
14.07 20:15:58 [Bot] [19:15:58] [[ERROR]] [AudioHandler]: Track Uj6R9SZ7D9g has failed to play
14.07 20:15:58 [Bot] com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video is unavailable
14.07 20:15:58 [Bot] at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:61)
14.07 20:15:58 [Bot] at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
14.07 20:15:58 [Bot] at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
14.07 20:15:58 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
14.07 20:15:58 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
14.07 20:15:58 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
14.07 20:15:58 [Bot] at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
14.07 20:15:58 [Bot] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
14.07 20:15:58 [Bot] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
14.07 20:15:58 [Bot] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
14.07 20:15:58 [Bot] at java.base/java.lang.Thread.run(Unknown Source)
14.07 20:15:58 [Bot] [19:15:58] [[ERROR]] [AudioHandler]: Track _ZeCEe0ZlHk has failed to play
14.07 20:15:58 [Bot] com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video is unavailable
14.07 20:15:58 [Bot] at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:61)
14.07 20:15:58 [Bot] at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
14.07 20:15:58 [Bot] at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
14.07 20:15:58 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
14.07 20:15:58 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
14.07 20:15:58 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
14.07 20:15:58 [Bot] at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
14.07 20:15:58 [Bot] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
14.07 20:15:58 [Bot] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
14.07 20:15:58 [Bot] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
14.07 20:15:58 [Bot] at java.base/java.lang.Thread.run(Unknown Source)
14.07 20:15:58 [Bot] [19:15:58] [[ERROR]] [AudioHandler]: Track fRBcgjEhAZE has failed to play
14.07 20:15:58 [Bot] com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video is unavailable
14.07 20:15:58 [Bot] at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:61)
14.07 20:15:58 [Bot] at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
14.07 20:15:58 [Bot] at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
14.07 20:15:58 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
14.07 20:15:58 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
14.07 20:15:58 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
14.07 20:15:58 [Bot] at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
14.07 20:15:58 [Bot] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
14.07 20:15:58 [Bot] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
14.07 20:15:58 [Bot] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
14.07 20:15:58 [Bot] at java.base/java.lang.Thread.run(Unknown Source)
14.07 20:15:58 [Bot] [19:15:58] [[ERROR]] [AudioHandler]: Track oyMbj2Zu_74 has failed to play
14.07 20:15:58 [Bot] com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video is unavailable
14.07 20:15:58 [Bot] at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:61)
14.07 20:15:58 [Bot] at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
14.07 20:15:58 [Bot] at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
14.07 20:15:58 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183)
14.07 20:15:58 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109)
14.07 20:15:58 [Bot] at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71)
14.07 20:15:58 [Bot] at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109)
14.07 20:15:58 [Bot] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339)
14.07 20:15:58 [Bot] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
14.07 20:15:58 [Bot] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
14.07 20:15:58 [Bot] at java.base/java.lang.Thread.run(Unknown Source)

When playing a singular link the bot in discord outputs "Error loading: This video is unavailable"

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.2

**Comment by kokofixcomputers** [comment]
I have this issue too!

**Comment by kokofixcomputers** [comment]
okay maybe i have a different issue than yours:

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.

**Comment by AuraofMana** [comment]
> okay maybe i have a different issue than yours:
> 
> com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.

I have the exact same issue. I also tried this on 0.3.9 and 0.4.1. I think YouTube did something and blocked all music.

**Comment by kokofixcomputers** [comment]
> 

oh....... Then my pull request should fix this issue

**Comment by jagrosh** [comment]
"This video is unavailable" means that the video is not available in your country, or requires a sign-in (like explicit content).

**Comment by AuraofMana** [comment]
@kokofixcomputers Should you open up another thread so Jagrosh sees it and merges in your PR or something?

**Comment by jagrosh** [comment]
It's already merged, we haven't made the release yet
