### ISSUE TITLE
[Bug Report] Bot joins and leaves when playing YouTube links

### ISSUE THREAD

**Issue by BlobIsBack** [jagrosh/MusicBot#1625]
### Bug Description

It just joins and leaves, if you need it I will connect to my vps later and send the error message here if there is one

I saw others issue but apparently it was fixed in 0.4.2, not for me

the bot is on the latest version

btw sorry if my English is bad

### Steps to Reproduce

Play YouTube link

See that the bot connects and disconnects

### Expected Result

The music plays

### Debug Output

```
System Properties:
  java.version = 11.0.22
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 11
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 11.0.22+7-post-Ubuntu-0ubuntu220.04.1
  java.specification.version = 11
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.4.2
  Owner = 588754343591936003
  Prefix = !!
  AltPrefix = null
  MaxSeconds = 0
  NPImages = true
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 2.2.1

Runtime Information:
  Total Memory = 49
  Used Memory = 30

Discord Information:
  ID = 1236292430291140619
  Guilds = 2
  Users = 3
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.2

**Comment by MichailiK** [comment]
Is this on a VPS/server? YouTube has banned the majority of the VPS providers. This issue is tracked in #1588. Feel free to enable notifications for that issue for any updates.

**Comment by BlobIsBack** [comment]
I installed cloudflare warp and now it works

**Comment by Am3zingP3P** [comment]
It might be that your VPS provider's ISP have been banned (e.g. Hetzner). There might be two solutions to the problem: 
1. Move the music bot to your own machine, thus the IP is not banned from using YT
2. Move to a more unknown VPS provider, and pray that it works there

I moved providers, and surprisingly that solved it for me

**Comment by jagrosh** [comment]
This may be resolved by the most-recent update, or it may be the 'sign-in' issue. If it's not either of those, feel free to reopen this if you can provide logs.
