### ISSUE TITLE
Pause when no ones listening.

### ISSUE THREAD

**Issue by freddymac48999** [jagrosh/MusicBot#164]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [x] I am running the [latest version][download]: [![Release][release]][download]
- [x] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [x] I have read through the [planned and suggested features][features]

## Issue
Wanting the bot to pause the music whenever someone isn't in the voice channel?
### Issue Type

- [ ] Bug Report
- [x] Feature Request

**Comment by jagrosh** [comment]
This is already on the [planned and suggested features](https://github.com/jagrosh/MusicBot/projects/1) list.
