### ISSUE TITLE
[Bug Report] Command Bug

### ISSUE THREAD

**Issue by Lapius7** [jagrosh/MusicBot#1640]
### Bug Description

音楽をループで流しながらしばらく放置していると一部のコマンド等が効かなくなります。

### Steps to Reproduce

1, 「{prefix}play pl {PlayListName}」コマンドを使用する。
2, 「{prefix}repeat」コマンドを使用する。(既にリピートがオンになっている場合この手順は省いて良い)
3, 1～2時間ほど流し続けます。
4, 「{prefix}np」や「{prefix}play」、「{prefix}stop」などのコマンドが使えなくなります。ただ試した限りでは「{prefix}shutdown」は使えるようです。

(npコマンドでリアルタイムで曲を表示したまま、1～2時間待った時、流れている曲とnpに表示されている内容がずれている時に上記のバグが起きている気がするので、二つのバグは繋がっていると思います)

### Expected Result

コマンドが使用できる。
npコマンドで表示されている曲と実際に流れている曲が同じ。

### Debug Output

コンソールにエラー等は出ません。

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.2f

**Comment by kokofixcomputers** [comment]
My pull request should fix this issue. Just waiting for a new release to come out.
