### ISSUE TITLE
[Feature Request] Add Spotify Playlist Support

### ISSUE THREAD

**Issue by JefferyPlayz** [jagrosh/MusicBot#1656]
### Is your feature request related to a problem? Please describe.

I am unable to add the music I listen to from spotify and instead have to find the same song on YouTube.

### What is your ideal solution to the problem?

To be able to send a link to my spotify playlist and then the bot will add my whole playlist to the queue.

### How would this feature be used?

1. Using the normal `!!p` command but with a spotify playlist link after it.
2. The bot asks you to confirm if you would like to add the whole playlist.
3. If you select yes the bot will add all the songs from the spotify playlist into the queue.

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
Spotify will not be supported as per the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added/#spotify).

**Comment by JefferyPlayz** [comment]
> Spotify will not be supported as per the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added/#spotify).

It would be call tho

**Comment by MichailiK** [comment]
There's currently no interest for us to implement (the heuristics) of finding the equivalent YouTube video from a Spotify track. We believe that it would be unreliable at finding the correct video & thus harm the experience, so we would rather not add & support that in the first place.

**Comment by JefferyPlayz** [comment]
> There's currently no interest for us to implement (the heuristics) of finding the equivalent YouTube video from a Spotify track. We believe that it would be unreliable at finding the correct video & thus harm the experience, so we would rather not add & support that in the first place.

Is there no way to stream the Spotify tracks directly from the Spotify API?
