### ISSUE TITLE
[Feature Request] (Releases) Put the release version into the pom.xml

### ISSUE THREAD

**Issue by eomanis** [jagrosh/MusicBot#1665]
### Is your feature request related to a problem? Please describe.

The version of the Maven artifact produced by the releases' pom.xml files has so far always been "Snapshot".

### What is your ideal solution to the problem?

Since we do have proper releases it would be prudent to put the actual release version number into the pom.xml /project/version node.

That would save me from having to [run the pom.xml through an XSLT that sets the version](https://aur.archlinux.org/packages/jmusicbot).

### How would this feature be used?

Makes it simpler to build a properly versioned Maven artifact.

### Additional Info

This feature request has low priority.

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
This is intentional so that self-built versions do not get confused with the official releases produced by our github actions. We don't provide any support for versions other than the jars provided on the releases page.

**Comment by eomanis** [comment]
Seems like me putting the version in there downstream goes against your intentions.
I guess i'll put "&lt;version&gt;-aur" or something the like when I update the AUR package next time.
