### ISSUE TITLE
[Bug Report] Bot doesn't start

### ISSUE THREAD

**Issue by Fickely** [jagrosh/MusicBot#1667]
### Bug Description

When i try to start the bot it shows a message that says java exception, but when i open from CMD it shows a large message

### Steps to Reproduce

Java 17.0.10

### Expected Result

The bot starts iniciating

### Debug Output

![imagen_2024-08-22_024039399](https://github.com/user-attachments/assets/1f7b8341-8b8a-473a-a2e9-5de320cc8198)
![image](https://github.com/user-attachments/assets/1445b305-7771-4a49-93dd-ec309b2c84b5)

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3

**Comment by MichailiK** [comment]
You are using Java 8 to start JMusicBot. You can check this by typing `java -version`. Make sure you have installed & are starting JMusicBot with Java 11 or above.
