### ISSUE TITLE
Suggestion: Single-repeat command

### ISSUE THREAD

**Issue by iocy** [jagrosh/MusicBot#168]
### Issue Type

- [ ] Bug Report
- [x] Feature Request

### Description

I want the ability to repeat only one song from the queue (that is, "single repeat"). Repeat all songs are useful, but I believe that MusicBot will be even better with this command.

**Comment by jagrosh** [comment]
This has been added to the [Suggested Features List](https://github.com/jagrosh/MusicBot/projects/1#card-13098453)
