### ISSUE TITLE
bots breaking everytime there is a new version

### ISSUE THREAD

**Issue by StinkyTACO** [jagrosh/MusicBot#171]
**### Sorry I was gonna delete the other one**

### Issue Type

- [x] Bug Report
- [ ] Feature Request

### Description

Why is it that every time there is a new version the bots act weird?
they were joining and leaving repeatedly

**Comment by jagrosh** [comment]
This has nothing to do with new versions of the bot, although you should always update to a new version if one is available.

If a bot is repeatedly joining and leaving a voice channel, this is an issue on Discord's end, and you can fix it by changing your server's region in the Server Settings.
