### ISSUE TITLE
Feature Request: MusicBot play Live Stream

### ISSUE THREAD

**Issue by RatingGull27** [jagrosh/MusicBot#172]
### Issue Type

- [x] Feature Request

### Description
can the Musicbot play the Live Stream like YouTube Twitch @jagrosh

**Comment by brockbreacher** [comment]
yes.
[p]play [livestream url]
![screenshot 10](https://user-images.githubusercontent.com/39160777/42751710-4010fb76-88b1-11e8-8d7c-0055907f2fab.png)

**Comment by RobCraftNet** [comment]
yea some here

**Comment by jagrosh** [comment]
Yes, playing live streams is supported, as shown above. If some streams aren't working, I would suggest waiting for the next release and trying with that when it is available.
