### ISSUE TITLE
[Feature Request] Disable available update notification

### ISSUE THREAD

**Issue by cuesta4** [jagrosh/MusicBot#1725]
### Is your feature request related to a problem? Please describe.

Sometimes we have to use unofficial versions of JBot that has fixes not yet available in the main branch. For example, the latest official version does not work for me, but an unnoficial version provided by the community does. The problem is that, since I'm not using the latest official version, the bot sends a message telling there's a new update every time I start it, which is very annoying.

### What is your ideal solution to the problem?

Allow us to disable automatic update messages. Add a check to a config flag before running the "send DM" method.

### How would this feature be used?

Open config file, change "update_reminder" to "false". 

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
`updatealerts` already exists.
```
// By default, the bot will DM the owner if the bot is running and a new version of the bot
// becomes available. Set this to false to disable this feature.

updatealerts=true
```

**Comment by cuesta4** [comment]
Sorry, I did not see this setting. Thanks for the help.
