### ISSUE TITLE
Error When Playing Music

### ISSUE THREAD

**Issue by MajorLOLGaming** [jagrosh/MusicBot#173]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [x] I am running the [latest version][download]: [![Release][release]][download]
- [x] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [x] I have read through the [planned and suggested features][features]

## Issue
Can't search any music at all, only play direct links.
### Issue Type

- [x] Bug Report
- [ ] Feature Request

### Description

When i type !play Queen - Don't Stop Me Now (Official Video) i get ![error](https://user-images.githubusercontent.com/32457983/42938399-7078e154-8b52-11e8-93bd-46ad4233fcbc.PNG)
but when i say !play https://www.youtube.com/watch?v=dQw4w9WgXcQ it works fine.
Here is a full log: [Pastebin](https://pastebin.com/raw/FiQ0Sf8m)

**Comment by jagrosh** [comment]
The [latest release](https://github.com/jagrosh/MusicBot/releases/latest) updates several dependencies, which very likely solves this issue. However, there are any number of factors that could lead to this, so if you still see this after updating, feel free to reopen this issue.
