### ISSUE TITLE
[Bug Report] I keep getting this error, and I think is has something to do with lavalink and lavaplayer but I don't know how to fix it 

### ISSUE THREAD

**Issue by Feirlein** [jagrosh/MusicBot#1733]
### Bug Description

Tried running the bot normally and I'm getting a "please sign in" error
### Additional Info
I tried updating everything and still getting the error
_No response_

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.3

**Comment by MichailiK** [comment]
Duplicate of #1588
