### ISSUE TITLE
This song is not playing

### ISSUE THREAD

**Issue by Adi2008-prog** [jagrosh/MusicBot#1749]
https://music.youtube.com/watch?v=S6DhdT0NAzI

**Comment by xyzakaria** [comment]
i cant have the bot playing song it keeps disconnecting from the vc , the console shows some error , the issue happend more than a month ago

**Comment by MichailiK** [comment]
Likely duplicate of:

- #1588 
- #1682

**Comment by Adi2008-prog** [comment]
So what can I do? Or can u suggest any other app ditto as Vi music?
