### ISSUE TITLE
Feature Request: Config path setup

### ISSUE THREAD

**Issue by TacoboiG** [jagrosh/MusicBot#175]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [x] I am running the [latest version][download]: [![Release][release]][download]
- [x] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [x] I have read through the [planned and suggested features][features]

### Issue Type

- [ ] Bug Report
- [x] Feature Request

### Description

Add a feature to set the path for the config I mean by that when the user doesn't have the config file created it opens a GUI to set the path for it after setting the bot token and owner id because when I want to open multiple bots on my computer I can't open them because one of the bots are having config.txt in the /home/user/config.txt so when it tells me to set the path i write the path for the config file like /home/user/Desktop/config.txt
I'm using (LINUX, UBUNTU)

**Comment by jagrosh** [comment]
This will be available in the next release (no ETA, still in-progress) with a property flag (ex: `-Dconfig=/path/to/configfile.txt`)

**Comment by jagrosh** [comment]
This is now available on the [latest release](https://github.com/jagrosh/MusicBot/releases/latest).
