### ISSUE TITLE
[Bug Report] Error after some time of playing a live stream

### ISSUE THREAD

**Issue by veryredpp** [jagrosh/MusicBot#1755]
### Bug Description

IM USING THIS FORK: https://github.com/TryNotDying/MusicBot/tree/0.4.4
Before rejecting it, the fork only added oauth2 support for youtube, so the error should occur here as well.

The bot leaves the channel after some period of time of playing a live stream

### Steps to Reproduce

1. play [live_url] (the one im using is https://www.youtube.com/watch?v=yXXIUXlYDpQ)
2. wait
3. leaves

### Expected Result

it not leaving and to continue playing

### Debug Output

```
System Properties:
  java.version = 22.0.2
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 22
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 22.0.2+9-70
  java.specification.version = 22
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.4.4
  Owner = 787692633400803369
  Prefix = @mention
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.4.1_353
  JDA-Utilities Version = 3.1.0
  Lavaplayer Version = 2.2.2

Runtime Information:
  Total Memory = 88
  Used Memory = 53

Discord Information:
  ID = 1182081313885397064
  Guilds = 2
  Users = 5
```

### Additional Info

LOGS:

[15:59:50] [INFO] [JMusicBot]: Loaded config from /home/[USER]/Desktop/MUSIC_BOT/config.txt
[15:59:50] [INFO] [Settings]: serversettings.json loaded from /home/[USER]/Desktop/MUSIC_BOT/serversettings.json
[15:59:50] [INFO] [YoutubeOauth2Handler]: YouTube access token refreshed successfully
[15:59:50] [INFO] [JDA]: Login Successful!
[15:59:51] [INFO] [WebSocketClient]: Connected to WebSocket
[15:59:51] [INFO] [JDA]: Finished Loading!
[16:00:56] [INFO] [NativeLibraryLoader]: Native library libmpg123-0: loading with filter com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader$$Lambda/0x0000767d1f366558@2f9bd69c
[16:00:56] [INFO] [NativeLibraryLoader]: Native library connector: loading with filter null
[16:00:56] [INFO] [NativeLibraryLoader]: Native library connector: successfully loaded.

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am using an official release from [the releases page](https://github.com/jagrosh/MusicBot/releases)

### JMusicBot Version

0.4.4 (FORK)

**Comment by veryredpp** [comment]
delete the issue if it doesn't apply for this version, its just that I cant use it without oauth2

**Comment by ALocked1** [comment]
> delete the issue if it doesn't apply for this version, its just that I cant use it without oauth2

There is a more official experimental build in jag's server, found in the pinned messages of #support
> https://discord.gg/jagrosh-147698382092238848

I don't believe we can really provide support for unofficial forks.

**Comment by MichailiK** [comment]
Forks are not supported in this repository.

Do not use OAuth2 anymore. It has been fixed & is being detected by Google.

**Comment by veryredpp** [comment]
> Do not use OAuth2 anymore. It has been fixed & is being detected by Google.

So the normal bot should work without OAuth2 errors from Google?

**Comment by MichailiK** [comment]
0.4.3 is currently broken. Even then, it will depend on if your IP address is blocked/banned.

**Comment by veryredpp** [comment]
> 0.4.3 is currently broken. Even then, it will depend on if your IP address is blocked/banned.

Is it broken due to OAuth2, or is it for some other reason?

**Comment by MichailiK** [comment]
0.4.3 is broken because YouTube have changed their cipher script
