### ISSUE TITLE
Feature to make bot automatically leave when there are no members in the VC

### ISSUE THREAD

**Issue by noahmarshall12** [jagrosh/MusicBot#177]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [x] I am running the [latest version][download]: [![Release][release]][download]
- [x] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [x] I have read through the [planned and suggested features][features]

## Issue
Feature to make bot automatically leave when there are no members in the VC

### Issue Type

- [ ] Bug Report
- [x] Feature Reques

### Description

A feature to make bot leave when no more users are in the VC.

**Comment by jagrosh** [comment]
This is already listed on the [Planned Features List](https://github.com/jagrosh/MusicBot/projects/1)
