### ISSUE TITLE
Youtube Mix Bug/and/or/Feature Request?

### ISSUE THREAD

**Issue by UnstableCodeScarlet** [jagrosh/MusicBot#179]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [X ] I am running the [latest version][download]: [![Release][release]][download]
- [X(Not my bot, runs fine otherwise) ] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [X ] I have read through the [planned and suggested features][features]

### Issue Type

- [X? ] Bug Report
- [ X?] Feature Request

### Description

I was originally going to suggest Youtube Mix functionality, but I saw in this issue you said you already added it.
https://github.com/jagrosh/MusicBot/issues/81

So Instead I guess this is a bug report, as it detects normal playlists to load additional but not youtube mix itself...

**Comment by jagrosh** [comment]
This sounds like it could be a change in the API on youtube's part; hopefully this will be fixed in the next release due to dependency updates.

**Comment by jagrosh** [comment]
Is this resolved as of the [latest release](https://github.com/jagrosh/MusicBot/releases/latest)?

**Comment by jagrosh** [comment]
Closing as this has been untouched for months and should already be fixed; feel free to re-open if you are still experiencing this issue.
