### ISSUE TITLE
Bot should leave the channel if nobody is listening

### ISSUE THREAD

**Issue by silasary** [jagrosh/MusicBot#182]
## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [x] I am running the [latest version][download]: [![Release][release]][download]
- [x] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [x] I have read through the [planned and suggested features][features]

### Issue Type

- [ ] Bug Report
- [x] Feature Request

### Description

We often have users load up long playlists - Full OSTs, for example - then leave the voice channel an hour into their 6 hour playlist.

Currently, this will leave the bot streaming for several hours with nobody listening.  Which is a huge waste of bandwidth for the bot's host.

The bot should automatically stop and leave the channel if this situation occurs.

**Comment by jagrosh** [comment]
This is already on the [planned features list](https://github.com/jagrosh/MusicBot/projects/1#card-4483529). Normally I would welcome a PR for this, but:
* This feature is not necessarily trivial; the action should only take place if there is nobody in the channel for some minimum length of time (ie one person listening alone accidentally disconnects shouldn't end up with the bot insta-clearing their songs)
* A lot of the internals are currently being rewritten, which might be beneficial for the addition of this feature once those are finished
