### ISSUE TITLE
Feature Request: Add uptime command

### ISSUE THREAD

**Issue by xSolidFigure** [jagrosh/MusicBot#184]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [x] I am running the [latest version][download]: [![Release][release]][download]
- [ ] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [x] I have read through the [planned and suggested features][features]

### Issue Type

- [ ] Bug Report
- [x] Feature Request

### Description

This feature should be added imo. I want people to know how long my music bot has been running for.

**Comment by jagrosh** [comment]
This information is already available at the very bottom of the output of the `about` command; the date and time of the last restart is included.
