### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by am3yar0ra** [jagrosh/MusicBot#19]
Your new release says you added an option to play the playlist but how do we do that ??

**Comment by jagrosh** [comment]
`play playlist <name>`
for example, if you have a playlist called "myplaylist.txt, `play playlist myplaylist`

**Comment by jagrosh** [comment]
Also, for non-issue questions, please join my [support server](https://discord.gg/0p9LSGoRLu6Pet0k)
I'll add a page to the wiki with full command reference soon as well.
