### ISSUE TITLE
[Feature Request] Skip the 'Loading Config' Message

### ISSUE THREAD

**Issue by mimela** [jagrosh/MusicBot#192]
[download]: https://github.com/jagrosh/MusicBot/releases/latest
[release]: https://img.shields.io/github/release/jagrosh/MusicBot.svg
[setup]: https://github.com/jagrosh/MusicBot/wiki/Setup
[rpi]: https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi
[features]: https://github.com/jagrosh/MusicBot/projects/1

## General Troubleshooting

Please check off these steps before suggesting a feature or reporting a bug:

- [*] I am running the [latest version][download]: [![Release][release]][download]
- [*] I have followed all instructions on the [setup page][setup] (and if applicable, [Raspberry Pi][rpi])
- [ ] I have read through the [planned and suggested features][features]

### Issue Type

- [ ] Bug Report
- [*] Feature Request

### Description

I want to skip the message for Loading which is displayed first. (Use Google Translate)

**Comment by jagrosh** [comment]
Can you provide a screenshot of which message you are describing?

**Comment by mimela** [comment]
![ws000063](https://user-images.githubusercontent.com/45594089/49685701-44215200-fb2b-11e8-861d-4e556e50ef54.JPG)
