### ISSUE TITLE
[Feature Request] Now playing on channel description

### ISSUE THREAD

**Issue by Dzeikob** [jagrosh/MusicBot#195]
**Is your feature request related to a problem? Please describe.**
We love the bot in our server and especially the now playing visuals and it being able to live update itself. We tried pinning the now playing chat but it stops live updating whenever a new !!np command is used (I assume?).

**Describe the solution you'd like**
It would be great if there's an external command which tells the bot to start updating channel description the same way as it does the current !!np feature, I will link a picture below for reference.

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. Go to the channel where you would like your channel description to update.
2. Use command (e.g !!togglechannelupdate) to enable/disable the feature.

**Additional context**
Image of the idea implementation: https://imgur.com/IQ3WjXw

**Have you confirmed that this idea is not already described here?**
Yup

**Comment by jagrosh** [comment]
If you use the `settc` command, and give the bot the Manage Channel in the channel you set, the bot will update the channel topic to list whatever song is currently playing. Putting the playback bar (showing the current time) is not possible in the channel topic due to ratelimits.

**Comment by Dzeikob** [comment]
Oh gotcha, appreciate your quick answer.
