### ISSUE TITLE
[Bug Report] Weird titles from some youtube videos

### ISSUE THREAD

**Issue by EarsKilla** [jagrosh/MusicBot#197]
Bot showing some video title with probably wrong encoding.

**To Reproduce**
1. Run with `java -Dnogui=true -jar JMusicBot-0.2.1.jar`
2. Do a command `play https://youtu.be/cry-QrppFOA`

**Expected behavior**
Expected: `Added Чеченский Гей-лев из Грозного (11:20) to begin playing(edited)`
Actual: `Added Ð§ÐµÑÐµÐ½ÑÐºÐ¸Ð¹ ÐÐµÐ¹-Ð»ÐµÐ² Ð¸Ð· ÐÑÐ¾Ð·Ð½Ð¾Ð³Ð¾ (11:20) to begin playing(edited)`

**Version Info:**
 - Operating System: `Debian GNU/Linux 8 (jessie)` / `Linux version 3.16.0-4-686-pae (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.51-2 (2017-12-03)`
 - JMusicBot Version: 0.2.1
 - Java version: 1.8.0_121

**Additional context**
Video where this happening https://youtu.be/cry-QrppFOA
But part of videos works fine. For example https://youtu.be/4bQEnW3eU5g

**Comment by MichailiK** [comment]
This issue is stale, and Cyrillic letters seem to now be displayed correctly. If it isn't the case, simply reply & I'll re-open this issue.
