### ISSUE TITLE
[Discussion] Migration to Java 11

### ISSUE THREAD

**Issue by Oelus** [jagrosh/MusicBot#204]
Any plans to migrate the bot from Java 8 to Java 11?

https://www.oracle.com/technetwork/java/java-se-support-roadmap.html

**Comment by GiantTreeLP** [comment]
There is no need to specifically target Java 11.
The bot already works with Java 11 out of the box.
As long as it runs there without any issues, there is no need to change anything about that.

**Comment by Oelus** [comment]
> There is no need to specifically target Java 11.
> The bot already works with Java 11 out of the box.
> As long as it runs there without any issues, there is no need to change anything about that.

Didn't know that was the case, thank you for clarifying.
If this works with fine with Java 11, this can be closed. @jagrosh

**Comment by Sanduhr32** [comment]
Newer Java Versions should be backwards compatible until Java 1.5 (afaik).
Also you can close the issue yourself.

**Comment by Oelus** [comment]
> Newer Java Versions should be backwards compatible until Java 1.5 (afaik).
> Also you can close the issue yourself.

Never knew that, thanks for sharing.
