### ISSUE TITLE
[Bug Report] YouTube Auto-Generated Videos Don't Play

### ISSUE THREAD

**Issue by torres126** [jagrosh/MusicBot#205]
**Describe the bug**
Playing an auto-generated song from YouTube provokes an error and doesn't play anything. 

**To Reproduce**
1. Find an auto-generated song on YouTube (it'll say it's auto-generated in the description, [When Doves Cry](https://youtu.be/oTUSeac7IuQ) is an example) 
2. Do a command '!play (song URL)' 
3. See error

**Expected behavior**

The song plays, but instead an error occurs and nothing plays. 

**Screenshots**

![screenshot_20190113-123333](https://user-images.githubusercontent.com/43215253/51085357-8bed5780-172f-11e9-89b6-ba57da4eaed4.jpg)

**Version Info (please complete the following information):**
 - Operating System: all, this has affected everyone regardless of browser
 - JMusicBot Version: 1.9.7 (I do not own the bot)

**Comment by jagrosh** [comment]
The screenshot you've provided is not JMusicBot...

**Comment by torres126** [comment]
Hm? This is the repo linked by the bot...my bad, sorry!
