### ISSUE TITLE
[Bug Report] Music is played while being interrupted at about 2 second intervals

### ISSUE THREAD

**Issue by Satoki101** [jagrosh/MusicBot#209]
**Describe the bug**
A phenomenon in which music is interrupted and reproduced occurs repeatedly for a moment.　

**To Reproduce**
1. Run with `JMusicBot-0.2.1-Windows.jar`
2. Do a command  `!!play <Any URL or keyword>`

**Expected behavior**
Expected: Music will play without interruption.
Actual    : Music is played while being interrupted at intervals of several seconds.

**Screenshots**
There is no screen shot.

**Version Info (please complete the following information):**
 - Operating System: [Windows10 64bit]
 - JMusicBot Version: [JMusicBot-0.2.1]
 - Java Version: [1.8.0_201]

**Additional context**
Some people may sound without problems, but I did not improve.
I tried to erase it once again, download it again, try restarting the PC, check whether Java version is old, but it did not recover.
As much as possible, I checked whether the same question has already been issued, but I may be missing because I am using Google Translate. I am sorry if I missed it.

**Comment by jagrosh** [comment]
A few questions:
- What is your internet speed (upload & download)?
- Are you connecting to Discord on the same computer/network that you are running the bot on?
- Does the music play without interruptions for only you, or do others in the channel with the bot also hear the interruptions?

**Comment by Satoki101** [comment]
- Upload is 94.29 Mbps and download is 93.16 Mbps.
- I am connecting with the same computer / network as running the bot.
- I also played the first one without any problems, but recently it has been played back on an intermittent basis.
Although others seem to be played seamlessly rarely, it will be played with almost no problem.

**Comment by jagrosh** [comment]
A few things I would try:
- Reset your home router/modem
- Change the Voice Region of the Discord Server
- Decrease the bit rate of the Voice Channel you are playing music in

**Comment by Proxymiity** [comment]
Using the bot on the same computer Discord is running on is maked as not compatible on certain self-hosted bots.
You can run the bot on the same computer you're on, but not vor voice activities like music.

> Upload is 94.29 Mbps and download is 93.16 Mbps.

Check if your computer's processor is used. If you can't solve your problem, then, I don't know how to help.

I have a Core i5 on a Mac Mini that runs the bot and I don't have any problem.
![](http://i.proxymiity.fr/img/TeamViewer_2019-03-05_00-19-43.png)
![](http://i.proxymiity.fr/img/TeamViewer_2019-03-05_00-21-13.png)

**Comment by jagrosh** [comment]
This was almost certainly a hardware or connection issue; there's not really anything in the bot that should cause this. If this is still a problem in a newer release, feel free to open a new issue with updated details.
