### ISSUE TITLE
[Feature Request] Shared queue

### ISSUE THREAD

**Issue by SpeedouTM** [jagrosh/MusicBot#210]
**Is your feature request related to a problem? Please describe.**
My feature request already exists but I would suggest a new way to work.

**Describe the solution you'd like**
When someone is playing a music (position "0") and the same person have jukeboxed another song ( position "1"), if another user want to jukebox a song his song is in position 2, it should be 1 because the other user is already playing the song position 0. For me the priority should work like this.

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. User 1 is playing a song (pos. 0)
2. User 1 added another song to the queue (pos. 1)
3. User 2 added a song to the queue (pos.1) and the song of User 1 must be pos.2

**Have you confirmed that this idea is not already described here?**
Yes.

**Comment by jagrosh** [comment]
The FairQueue system already inserts the music fairly, much like you described; the only difference is that the currently-playing song is not taken into account. I have no plans to change this as the FairQueue shouldn't need to check external locations (like what is currently playing).
