### ISSUE TITLE
[Feature Request] Translate the Bot to Other Language

### ISSUE THREAD

**Issue by extremeHubGit** [jagrosh/MusicBot#212]
I discovered the bot recently and found it incredible, I installed it and configured it. When I finished I really enjoyed his functions but I realized that there was no one file that allowed me to translate the bot to my language.
Would there be any way for you to add the files with the English sentences so that I could translate them into my language?
(Brazilian Portuguese)

**Comment by jagrosh** [comment]
This is already on the [planned features list](https://github.com/jagrosh/MusicBot/projects/1). Please check that list before submitting an issue, and please use the issue template.
