### ISSUE TITLE
Feature: Commands Shortcut

### ISSUE THREAD

**Issue by TacobiG** [jagrosh/MusicBot#213]
I would love to see a command that shortcut the commands you got as like "<prefix>shortcut <command> <shortcut>" or "<prefix>setsh <command> <shortcut>" for example: "xsetsh play p"
now when i type <prefix>p it starts music 💃

**Comment by jagrosh** [comment]
In the future, please use the feature request template. As for this suggestion, its an interesting concept, although it would almost certainly be set up in the config file, not via command, as the command list gets loaded at startup.

**Comment by ExpeeLive** [comment]
I'd love to see this added! I'd love to change the prefix so I can set it as [+] the same as the rest of my commands

**Comment by jagrosh** [comment]
You already can change the prefix....

**Comment by ExpeeLive** [comment]
wait... I couldn't find it anywhere. what's the command?

**Comment by jagrosh** [comment]
It's not a command, you can set the prefix in the [config](https://github.com/jagrosh/MusicBot/wiki/Example-Config)

**Comment by Craumix** [comment]
https://github.com/jagrosh/MusicBot/issues/228
same but i would recommend some default shortcuts...

**Comment by jagrosh** [comment]
Adding aliases for commands is now possible as of release 0.2.6
