### ISSUE TITLE
[Bug Report] serversettings.json not created

### ISSUE THREAD

**Issue by tjeufoolen** [jagrosh/MusicBot#215]
**Describe the bug**
After restarting, changing folder permissions and trying to set a text channel or dj role it won't create a serversettings.json file.

**Version Info (please complete the following information):**
 - Operating System: Ubuntu 18.0.4
 - JMusicBot Version: 0.2.2

**Additional context**
I have already tried:
`chown discord:discord *` on the entire folder its contents.
and
`chmod 755 JMusicbot-0.2.2-linux.jar`
But it doesn't seem to create the file.

**Comment by jagrosh** [comment]
Is there any console/log output when you set a setting?

**Comment by tjeufoolen** [comment]
Nvm..
Already figured it out after I made the issue.
I had chowned all folder contents but not the actual folder itself, my bad.
Sorry for bothering!
