### ISSUE TITLE
[Feature Request] Playing songs from folder 

### ISSUE THREAD

**Issue by SiE98** [jagrosh/MusicBot#219]
May its possible playing music from folder in playlist
Eg I have 200 mp3 files and place in playlist all 200 lines with filename is terrible ass-pain )) 

I guess it possible make play from eg c:\musicforbot\*.* ?

**Comment by jagrosh** [comment]
That will not be added due to potential security issues, as well as being generally confusing to use for users.

It is trivial to create a playlist from existing folder(s):
Windows (PowerShell): `dir -r | % {$_.FullName} > myplaylist.txt`
Linux (Bash): `find "$(pwd)" > myplaylist.txt`
