### ISSUE TITLE
[Bug Report] bot can't connect to VIP servers on partnered server

### ISSUE THREAD

**Issue by AnimeHasFallen** [jagrosh/MusicBot#220]
**Describe the bug**
When trying to get the bot to connect in voice on VIP servers it just constantly disconnects and reconnects to the channel.

**To Reproduce**
1. Run with on linux generic 
2. Use a VIP voice server on discord
3. Use the play command any way to try and connect

**Expected behavior**
Connects to the channel and stays

**Screenshots**
![IMG_20190413_160545](https://user-images.githubusercontent.com/22727024/56085420-8542af00-5e08-11e9-8dc4-5bc9e07c010d.jpg)

**Version Info (please complete the following information):**
 - Operating System: Rasberian 9.6 stretch
 - JMusicBot Version: 0.2.2 & 0.2.1

**Additional context**
It connects and works just fine on the non VIP voice servers.

**Comment by jagrosh** [comment]
This is an issue on Discord's end that I have no control over. From experience, I've found that the "VIP" voice servers tend to have more issues for more people than the regular ones, and wouldn't recommend using them.
