### ISSUE TITLE
[Feature Request] Ability to set NoGui in config so you don't have to start the bot with the parameter every time

### ISSUE THREAD

**Issue by Oelus** [jagrosh/MusicBot#221]
Be able to tet NoGui in config so you don't have to start the bot with parameter (`-Dnogui=true`) every time.
Thanks.

**Comment by OwnaDash** [comment]
Oelus in what O.S. are you running the bot?

**Comment by jagrosh** [comment]
This won't be added because the gui setting needs to be set before the config is loaded (so error messages can be shown correctly)

**Comment by Oelus** [comment]
> Oelus in what O.S. are you running the bot?

Running the bot on CentOS 7.5



> This won't be added because the gui setting needs to be set before the config is loaded (so error messages can be shown correctly)

Quite inconvenient having to use this setting every time when starting the bot.
Oh well. 😄
