### ISSUE TITLE
[Feature Request] Rejoin channels after restart

### ISSUE THREAD

**Issue by Oelus** [jagrosh/MusicBot#222]
**Is your feature request related to a problem? Please describe.**

When I want to restart the musicbot, I have it in a few personal servers. Whenever I restart the bot, I have to manually put it back into every channel.

**Describe the solution you'd like**

Would it be possible to make the bot rejoin channels after a restart?

**Comment by jagrosh** [comment]
This is already possible. Simply set a vc channel for the bot (`setvc`) and an autoplaylist (`autoplaylist`) and the bot will join the channel and begin playing from the playlist when it starts up.
