### ISSUE TITLE
Missing artifact com.jagrosh:JDA-Utilities:jar:1.1

### ISSUE THREAD

**Issue by SRLJustin** [jagrosh/MusicBot#23]
Hi,

New to this Maven project stuff, I've imported the project into Eclipse as a Maven project, it's downloaded most of the dependencies but i'm getting this error/problem:

> Missing artifact com.jagrosh:JDA-Utilities:jar:1.1
> The container 'Maven Dependencies' references non existing library 'C:\Users\justin\\.m2\repository\com\jagrosh\JDA-Utilities\1.1\JDA-Utilities-1.1.jar'
> 

I've had a look around but I can only find the 1.0 version of JDA-Utilities and if I try to import that I then get more errors in Eclipse

The reason why I'm trying to compile my own is because I'd like to add some custom commands to the bot

Any tips to get this fixed?

**Comment by TheMonitorLizard** [comment]
This is the music bot, not JDA-Utilities.
You can go here for any questions about JDA-Utilities:
https://github.com/jagrosh/JDA-Utilities/

**Comment by jagrosh** [comment]
The bot is not designed to be edited. The code is open source for other users to see how things work, but I do not provide support for editing it yourself, sorry.
