### ISSUE TITLE
[Bug Report] Bot can't create config file

### ISSUE THREAD

**Issue by SakuraAngel** [jagrosh/MusicBot#231]
**Describe the bug**
I followed the instructions, and When it told me to put in the bot token and It came up with a error message (It's in the documents section in a folder with nothing else)
**To Reproduce**
I really don't know how to reproduce it
**Expected behavior**
For it to work and to operate normally 
**Screenshots**

**Version Info (please complete the following information):**
 - Operating System: Windows 10 64x bit
 - JMusicBot Version: 0.2.2

**Additional context**
![image](https://user-images.githubusercontent.com/51038197/58523658-59e70a00-8193-11e9-8c1c-4956348813f4.png)

**Comment by Sanduhr32** [comment]
It clearly has no right to write files there. And clearly you do not add programs in the systems os folder. Just program files (x86) or custom paths

**Comment by Craumix** [comment]
It seems like you are running the .jar file as admin user, wich then sets the execution path to **C:\Windows\System32**.
Try running by double-clicking the .jar file or press **Windows-key + R** then run:
`cd "C:\Your\Path\To\Jar\File"`
and
`java -jar YourJarFile.jar`.

**Comment by Sanduhr32** [comment]
Nah and isn't the fault either. That won't help. He has to relocate the jar file to a directory where the user is having read/write access and not just read access.

**Comment by jagrosh** [comment]
Can you share the full path to where you have the jar file located?

**Comment by Craumix** [comment]
For example the Downloads folder..

@Sanduhr32 I doubt that he copied the .jar file to system32, this is just the defualt path if you run as admin...

**Comment by SakuraAngel** [comment]
![image](https://user-images.githubusercontent.com/51038197/58672787-9a22c580-8316-11e9-846a-e7152613373d.png)

**Comment by jagrosh** [comment]
Can you try running it from a regular folder, not a OneDrive folder?

**Comment by SakuraAngel** [comment]
![image](https://user-images.githubusercontent.com/51038197/58735404-48d30e80-83c8-11e9-9c7b-067c8a704853.png)
![image](https://user-images.githubusercontent.com/51038197/58735495-92235e00-83c8-11e9-9adf-0ed0e559db70.png)

**Comment by SakuraAngel** [comment]
The first time, It didn't recognize the Config file, so i deleted it and see if it would create it, but it didn't.

**Comment by Sanduhr32** [comment]
How do you run it? Double clicking it?
Try opening a cmd / powershell at that path.
**Win Key + R** cmd / powershell & **cd (/D if cmd)** *path of documents*
CMD: `java -jar JMusicBot-0.2.2.jar`
PSH: `java -jar .\JMusicBot-0.2.2.jar`

**Comment by SakuraAngel** [comment]
I opened it using Java at first, It was working normally. Then it said it couldn't create a config file, I don;t know what happened really.

**Comment by SakuraAngel** [comment]
Your Run command works, Thank you!
