### ISSUE TITLE
Add a 'nogui' command

### ISSUE THREAD

**Issue by sabactani** [jagrosh/MusicBot#234]
It is not necessary to have that white gui when you're running the bot through the terminal, so you could really add a nogui option, like the minecraft server has. Shouldn't be hard doing, but i am not capable of as i can't program.

**Comment by jagrosh** [comment]
This is already possible, simply specify `-Dnogui=true` as one of the java parameters when running from the command lind

**Comment by Zotac101** [comment]
I am currently using it like this :-
" java -jar JMusicBot-0.3.9.jar -Dnogui=true"

Still I have this error :- 

[13:20:21] [ERROR] [JMusicBot]: Could not start GUI. If you are running on a server or in a location where you cannot display a window, please run in nogui mode using the -Dnogui=true flag.


However the program still works,its in a Ubuntu server .

**Comment by Zotac101** [comment]
Ahh ic thanks , the error message is gone.

Though I was wondering and benefits of passing this command on a server based machine ? Since it auto defaults to gui !
