### ISSUE TITLE
[Feature Request] Allow dj/tc/vc to be set in config

### ISSUE THREAD

**Issue by peterthehan** [jagrosh/MusicBot#236]
**Is your feature request related to a problem? Please describe.**
It is annoying having to set dj, tc, and/or vc if the bot is ever rebooted. Allow the bot to load these from config.

**Describe the solution you'd like**
On bot start up, if the settings are preset in config, they should be loaded up.

**Describe the basic flow/steps of using this feature**
How this feature would be used:
In config, user can map guild id(s) in a one-to-many relationship for:
1. dj role ids
2. text channel ids
3. voice channel ids

User can create these rules for as many guilds as they want to preset.

**Have you confirmed that this idea is not already described here?**
https://github.com/jagrosh/MusicBot/projects/1
Yes. Found something for consideration https://github.com/jagrosh/MusicBot/projects/1#card-5217438 that this should also take into account.

**Comment by jagrosh** [comment]
It sounds like you're running the bot without the right permissions or from a restricted directory, because these things should be saved to serversettings.json whenever you change them.
