### ISSUE TITLE
[Feature Request] Allow DJ or higher to bulk remove another user's songs from the playlist

### ISSUE THREAD

**Issue by peterthehan** [jagrosh/MusicBot#237]
**Is your feature request related to a problem? Please describe.**
Sometimes a user (whether by accident or maliciously) adds many songs to an existing playlist and leaves without removing them. To my knowledge, without the user themselves using `remove all`, there's no way to bulk remove their songs aside from `stop`-ing the entire playlist or `forceskip`-ing every entry. This is bad UX for DJs.

**Describe the solution you'd like**
Allow DJs to use a more powerful version of `remove` by having a mention parameter.
e.g. `remove @user all` or `remove all @user` (second seems better).

**Describe the basic flow/steps of using this feature**
Described above.

**Have you confirmed that this idea is not already described here?**
Yes

**Comment by jagrosh** [comment]
DJs can `skipto` a specific song to skip over a selection of songs without clearing the entire queue.

That being said, this might be a useful feature, although it would be confusing to overlap DJ functionality with a non-DJ command, so following existing command naming, maybe `forceremove`
