### ISSUE TITLE
Version 0.2.3 won't launch

### ISSUE THREAD

**Issue by EchoesNetwork** [jagrosh/MusicBot#238]
Hello,

My bot (running MusicBot 0.2.2) went down a couple of days ago and I looked at my VPS and noticed it needed to be updated. I downloaded both the universal and linux versions of `JMusicBot-0.2.3.jar`. Neither of them will run, even with the `-Dnogui=true` flag when launching. They both produce the following error:
```java
Exception in thread "main" java.lang.IllegalArgumentException: Name may not be blank
at net.dv8tion.jda.core.utils.Checks.notBlank(Checks.java:70)
at net.dv8tion.jda.core.entities.Game.listening(Game.java:216)
at com.jagrosh.jmusicbot.utils.OtherUtil.parseGame(OtherUtil.java:78)
at com.jagrosh.jmusicbot.BotConfig.load(BotConfig.java:88)
at com.jagrosh.jmusicbot.JMusicBot.main(JMusicBot.java:76)
```
`javac -version` produces `1.8.0_212`. I'm fairly sure that running JDK and not OpenJDK, because 0.2.2 worked for me without issue, and I haven't made any modifications to my system's Java installation since. This is the only Java program running on that machine.  System is Ubuntu 18.04.02 LTS. Hope I've provided all the necessary background; any help would be appreciated. Thanks!

**Comment by jagrosh** [comment]
What is the `game =` line in your config file?

**Comment by EchoesNetwork** [comment]
> What is the `game =` line in your config file?

It's set to this:
`game = "Listening to"`

**Comment by jagrosh** [comment]
You left the actual name of the game blank. You need to set it to something like:
```
game = "Listening to some cool music"
```
