### ISSUE TITLE
[Bug Report] can't play a song

### ISSUE THREAD

**Issue by Thoogui** [jagrosh/MusicBot#239]
**can't play a song**
When i start a song and i wait it end, i can't start a new.

**To Reproduce**
1. Start a song
2. Wait it end
3. Start a new

**Expected behavior**
Can't play another, a message appear
AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://www.youtube.com:443: Connection timed out (Read failed)

**Screenshots**
![image](https://user-images.githubusercontent.com/23406894/59708472-1d905200-9205-11e9-93b9-676b4dc5d8e3.png)

![image](https://user-images.githubusercontent.com/23406894/59708610-66480b00-9205-11e9-8c5f-069015b2bd9c.png)

**Version Info (please complete the following information):**
 - Operating System: debian last version
 - JMusicBot Version: last version

**Comment by jagrosh** [comment]
It looks like your connection is unstable, or YouTube has blocked your host, as your requests to YouTube are timing out.

**Comment by Thoogui** [comment]
ive ask to my host, they don't block anything and they told me that the connection is good

**Comment by Sanduhr32** [comment]
YouTube might block your host, not your host YouTube.

**Comment by jagrosh** [comment]
This appears to be a problem with your host; if you have further information, feel free to reopen this issue
