### ISSUE TITLE
[Bug Report] Bot can't play livestream

### ISSUE THREAD

**Issue by Lite90** [jagrosh/MusicBot#240]
**Describe the bug**
Bot can't play livestream feed. Bot not playing anything.

**To Reproduce**
!play <livestream URL>

**Expected behavior**
Bot used to able to play livestream URL

**Version Info (please complete the following information):**
 - Operating System: Windows 10 64bit
 - JMusicBot Version: 0.2.3

**Additional context**

**Comment by jagrosh** [comment]
Can you provide an example of a livestream link that you are trying to play?

**Comment by Lite90** [comment]
try !play http://playerservices.streamtheworld.com/api/livestream-redirect/987FMAAC.aac?tdtok=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImZTeXA4In0.eyJpc3MiOiJ0aXNydiIsInN1YiI6IjIxMDY0IiwiaWF0IjoxNTYxNDcwMDE4LCJ0ZC1yZWciOmZhbHNlfQ.8_2nTkQMvxSCWnWrFxiMo7aYr-eU5QOJo0ce4VLGj5I
