### ISSUE TITLE
Bot configuration window

### ISSUE THREAD

**Issue by Z3USS** [jagrosh/MusicBot#25]
Would be to create 2 versions of the Bot so to speak, a "normal" to hoped in a vps talves do not know and another for the person to be able to use on the computer in a simplified and more intuitive way

![image](https://cloud.githubusercontent.com/assets/20386917/26039690/5bef22f4-38f4-11e7-8727-43b34c7749d8.png)

**Comment by jagrosh** [comment]
Looks like you already have the other version in your screenshot, and it would be a lot of work for me to re-create it, so you can just use the version that already exists. (You can run both versions on a single bot anyway).

**Comment by jagrosh** [comment]
I believe that the image you have linked is for the music player found here: https://github.com/BlackScarx/DiscordMusicPlayer2. You can use that music player if you want that feature.
