### ISSUE TITLE
[Feature Request] autojoin and autoplay on startup

### ISSUE THREAD

**Issue by TheTou** [jagrosh/MusicBot#250]
**Is your feature request related to a problem? Please describe.**
Currently you have to manually join the bot into a voice channel and start playing some music. 

**Describe the solution you'd like**
There should be an option for the bot to automatically join a voice channel and play the default playlist on startup.

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. (Re)start the bot
2. Automatically join the default voice channel, if set in serversettings.json
3. Play the default_playlist, if set in serversettings.json

**Comment by jagrosh** [comment]
This is already the case. If you use `setvc` and `autoplaylist` in a server, when the bot starts it will automatically connect to the VC channel and begin playing the autoplaylist.

Also, do not edit serversettings.json manually; use the commands within the server.

**Comment by TheTou** [comment]
Wasn't obvious to me from the documentation, thanks. Works as expected.

**Comment by andraekaaa** [comment]
![Screenshot_20231010-144232_Termius](https://github.com/jagrosh/MusicBot/assets/71745652/70572e12-df61-423b-9c06-4fad06fa3892)
![IMG-20231010-WA0009](https://github.com/jagrosh/MusicBot/assets/71745652/25a7aa42-fb98-4d8a-8cd0-9ff4e90cc57c)
![Screenshot_20231010-141523_Discord](https://github.com/jagrosh/MusicBot/assets/71745652/9f1ef006-65e0-47e2-9ee4-0623ae851391)

Im sorry my English is bad. 
I need help with !autoplaylist.

**Comment by andraekaaa** [comment]
> ![Screenshot_20231010-144232_Termius](https://user-images.githubusercontent.com/71745652/273816537-70572e12-df61-423b-9c06-4fad06fa3892.png) ![IMG-20231010-WA0009](https://user-images.githubusercontent.com/71745652/273816546-25a7aa42-fb98-4d8a-8cd0-9ff4e90cc57c.jpg) ![Screenshot_20231010-141523_Discord](https://user-images.githubusercontent.com/71745652/273816551-9f1ef006-65e0-47e2-9ee4-0623ae851391.png)
> 
> Im sorry my English is bad. I need help with !autoplaylist. -edit. Shutdown not work Im also new in linux Im not progamer Sorry if it bothers you Thank You. My bot in desktop/botfolder

Hello im sorry, the Bot was work. I have 1 digit excess on the owner ID. Thank You.
