### ISSUE TITLE
[Bug Report] I'm opening a song no sound

### ISSUE THREAD

**Issue by glapnak** [jagrosh/MusicBot#251]
**I'm opening a song no sound**
I turn on the song shows it plays but no sound

**To Reproduce**
1. start a song
2. shows music plays
3. no sound

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/53314996/61913029-84abcf80-af44-11e9-8517-18f3c2bb1fdc.jpg)

**Version Info (please complete the following information):**
 - Operating System: [windows 10 pro last version]
 - JMusicBot Version: [last version]

**Comment by jagrosh** [comment]
Can you provide more information, including:
- exact java version
- exact jmusicbot version
- which jmusicbot jar you are running
- any logs from the console after attempting to start a song

Also have you checked:
- if other people can hear the bot?
- if you can hear other people or other bots?

**Comment by misharyb** [comment]
i have the same issue, when i change the volume to up or down the sound just disappeared

**Comment by jagrosh** [comment]
Changing the volume is a separate issue, and it means that you are not using 64-bit java or are not using the correct version of the bot for your operating system.

Closing this issue as not enough information has been provided to debug this.

**Comment by whinis** [comment]
I now have this issue as well. Everyone on Desktop version of Discord cannot hear the bot after 3-4 songs played and restarting the bot did not fix it. Mobile users could hear the bot.

I managed to fix this by disconnecting from the voice channel and reconnecting so I believe this may be an odd discord bug.
