### ISSUE TITLE
playlist error on loading tracks from a specific path.

### ISSUE THREAD

**Issue by greenmaskenergy** [jagrosh/MusicBot#254]
i run allot of multiple instances hosted on my pc across multiple servers with the idea of sharing the same playlist folder

this are the bots
![879755f4a147ccc361ac8b4629975368](https://user-images.githubusercontent.com/26696231/62169535-c663be00-b328-11e9-89c0-42929d711aeb.png)

the folder structure is as followed:

![141eb5a7d312d6febd1b9dbed57a8597](https://user-images.githubusercontent.com/26696231/62170324-54d93f00-b32b-11e9-8434-5533e6a407de.png)

![2ee900c424e2b9c28d398ab164e50633](https://user-images.githubusercontent.com/26696231/62170193-e5634f80-b32a-11e9-9109-66f6e86f1603.png)

inside the last folder of BOT9 is the shared playlist folder so BOT9.config path to playlist = "playlists"

as BOT6.config = "Bravo/Chalie/Delta/playlists"
cause there inside of eachother they work but when i do like bot 2,3,4,5,1 they have seperate folder and need to go a directory back like this "../Alpha/Bravo/Charlie/Delta/playlists"

it works i tested it with !playlists they show up bet when i load them with !play playlist playlist name they load and give an error it only started to show up after adding bot 2 ,3 4 5 1 so my bed is it has somthing to do with the ../ directory path but the strange part is unaffected bots like Bot1 that do not have to go back a directory stopped working to so i have no clue ? 

this is what happens when i load it 
![d3eb88ee205eabf38ba94e0686946730](https://user-images.githubusercontent.com/26696231/62170209-f0b67b00-b32a-11e9-8d11-865e78fdcd25.png)

and this is the result 
![c67cdd77d2c7395557c7a89ff36f7ba8](https://user-images.githubusercontent.com/26696231/62170212-f7dd8900-b32a-11e9-8f72-c760c5f653fe.png)

even manual trying
 "!play https://www.youtube.com/watch?v=dy-5efgUncY" 
give a failed loading track respond
 but using 
"!play roby fayer ready"
 does work it all did work one day earlier O_O

do i encounter som kind of limitition where it started to break all bots or somthing else i have no clue ty for taking the time

with regards,
GreenMaskEnergy

ps bot version
![dbc9238b1c6a84a5663c56e165b0c445](https://user-images.githubusercontent.com/26696231/62170639-653de980-b32c-11e9-80fa-bb436894985e.png)

**Comment by Sanduhr32** [comment]
Now let's get funky and try /../<path> or the full path so it not being relative.

**Comment by greenmaskenergy** [comment]
ok did some more reasons it has nothing to do with the path its works file ../ to go back a directory should not be a problem it has to do with or youtube or some faulty code i dont know but a playlist i created like 2 days ago stopped working if i try to load it again now that playlist looks like this 
------------------------------------https://www.youtube.com/watch?v=dy-5efgUncY
https://www.youtube.com/watch?v=LBr7kECsjcQ&list=RDdy-5efgUncY&index=5
https://www.youtube.com/watch?v=U0fk5L1ifbo&feature=youtu.be&list=RDdy-5efgUncY
https://www.youtube.com/watch?v=J-_tv7Y0DAo
https://www.youtube.com/watch?v=Az-mGR-CehY
https://www.youtube.com/watch?v=lJkEF0_QigU
https://www.youtube.com/watch?v=kXptPzKNMq4
https://www.youtube.com/watch?v=bsENfTmAdeI
https://www.youtube.com/watch?v=WNeLUngb-Xg
https://www.youtube.com/watch?v=Z6L4u2i97Rw
https://www.youtube.com/watch?v=CxnaPa8ohmM
https://www.youtube.com/watch?v=0XFudmaObLI
https://www.youtube.com/watch?v=5_hRB0Kj1eo
https://www.youtube.com/watch?v=tcHJodG5hX8
https://www.youtube.com/watch?v=24C8r8JupYY
https://www.youtube.com/watch?v=W9P_qUnMaFg
https://www.youtube.com/watch?v=S19UcWdOA-I
https://www.youtube.com/watch?v=Ccsh_-Cucl4
---------------------------------------------------
i tried removing the youtube part and keeping all after v= still nothing but here comes the wear part!!!!!

if i play an old playlist that still work looks like this 
----------------------------------------------------------
https://www.youtube.com/watch?v=Rvikr0TaPCU
https://www.youtube.com/watch?v=450p7goxZqg
https://www.youtube.com/watch?v=pRfmrE0ToTo
https://www.youtube.com/watch?v=trS2nrkN0_k
https://www.youtube.com/watch?v=LkIWmsP3c_s
https://www.youtube.com/watch?v=pln7NWRA1dE
https://www.youtube.com/watch?v=PdGi5g2eatk
https://www.youtube.com/watch?v=6RzR0zvubhw
I9LimwJ2GmQ
DRmHjDzVbRs
Fw0R0b2r6pE
18obFY29_T8
HwKOojr-xMA
https://www.youtube.com/watch?v=5sWjlEvCbWU&list=PL32NUlSaKmm3gGasEh3aSTwf9knF8VbBy
https://www.youtube.com/watch?v=WXSYsjMNMJc&list=PLFkPkV-lLKuZrfoC-ADkyyzJmMBPXp_03
shuffle
https://www.youtube.com/watch?v=wIJq1vPbdGM&list=RDnm1RBFvwxcs&index=29
https://www.youtube.com/watch?v=nJSdYlAFKqA&list=RDnm1RBFvwxcs&index=27
----------------------------------------------------
its plays them all and now the weirdest if i merge the not working under the playlist that works here above it all works then the playlist is bigger like this:

https://www.youtube.com/watch?v=__CRWE-L45k&list=RD__CRWE-L45k&start_radio=1
https://www.youtube.com/watch?v=5sWjlEvCbWU&list=RD5sWjlEvCbWU&start_radio=1
https://www.youtube.com/playlist?list=PL32NUlSaKmm0kxNY4j1bM-ex9Z6nBVV-Y
https://www.youtube.com/watch?v=Rvikr0TaPCU
https://www.youtube.com/watch?v=450p7goxZqg
https://www.youtube.com/watch?v=pRfmrE0ToTo
https://www.youtube.com/watch?v=trS2nrkN0_k
https://www.youtube.com/watch?v=LkIWmsP3c_s
https://www.youtube.com/watch?v=pln7NWRA1dE
https://www.youtube.com/watch?v=PdGi5g2eatk
https://www.youtube.com/watch?v=6RzR0zvubhw
I9LimwJ2GmQ
DRmHjDzVbRs
Fw0R0b2r6pE
18obFY29_T8
HwKOojr-xMA
https://www.youtube.com/watch?v=5sWjlEvCbWU&list=PL32NUlSaKmm3gGasEh3aSTwf9knF8VbBy
https://www.youtube.com/watch?v=WXSYsjMNMJc&list=PLFkPkV-lLKuZrfoC-ADkyyzJmMBPXp_03
shuffle
https://www.youtube.com/watch?v=wIJq1vPbdGM&list=RDnm1RBFvwxcs&index=29
https://www.youtube.com/watch?v=nJSdYlAFKqA&list=RDnm1RBFvwxcs&index=27
dy-5efgUncY
LBr7kECsjcQ
U0fk5L1ifbo
J-_tv7Y0DAo
Az-mGR-CehY
lJkEF0_QigU
kXptPzKNMq4
bsENfTmAdeI
WNeLUngb-Xg
Z6L4u2i97Rw
CxnaPa8ohmM
0XFudmaObLI
5_hRB0Kj1eo
tcHJodG5hX8
24C8r8JupYY
W9P_qUnMaFg
S19UcWdOA-I
Ccsh_-Cucl4
shuffle



how is that even possible what am i not seeing so to the point if i try to load the 18 tracks dat dont work first it does not work but if i load them in an other playlist after some other songs it works how is that who has a clue???
[Aworkingplaylist.txt](https://github.com/jagrosh/MusicBot/files/3451748/Aworkingplaylist.txt)
[Merged and working.txt](https://github.com/jagrosh/MusicBot/files/3451749/Merged.and.working.txt)
[Not working.txt](https://github.com/jagrosh/MusicBot/files/3451750/Not.working.txt)

**Comment by Sanduhr32** [comment]
Yeah well youtube does some changes like discord to their voice api

**Comment by greenmaskenergy** [comment]
so its just normal that it works when merged with an other one and not if playing alone ? i can't believe that

**Comment by Sanduhr32** [comment]
Yep. It's a miracle that it kind of works.

**Comment by greenmaskenergy** [comment]
well screw youtube then fking content creators with demonitizing and now breaking the site

**Comment by jagrosh** [comment]
The youtube loading issue should be fixed in the next release; also please remember to keep conversation civil and on-topic.
