### ISSUE TITLE
[Bug Report] Almost all YT links won't load

### ISSUE THREAD

**Issue by Ad-Blokker** [jagrosh/MusicBot#255]
**Describe the bug**
Due to some changes in the YouTube API the library used by this music bot ("Lavaplayer") can't fetch details from YouTube videos. This results in not adding the song.

> :no_entry_sign: Error loading track.

Lavaplayer has been updated to 1.3.19, Please update the library used in this program.

**To Reproduce**
play "someyoutubelink"

**Expected behavior**
Add the song to the queue

**Screenshots**
![](https://i.imgur.com/EeZ2qF7.png)

**Version Info:**
 - Operating System: Windows Server 2012 R2
 - JMusicBot Version: 0.2.3

**Additional context**
https://github.com/sedmelluq/lavaplayer/blob/master/CHANGELOG.md

**Comment by Sanduhr32** [comment]
You can use ![](image link) for embedding them.

**Comment by jagrosh** [comment]
This will be fixed in the next release
