### ISSUE TITLE
[Feature Request] Spotify

### ISSUE THREAD

**Issue by shetos126** [jagrosh/MusicBot#258]
**I hope I can play songs from Spotify in the next update**

**Comment by jagrosh** [comment]
Playing from Spotify is not possible. Instead, consider using an online playlist converter to convert a spotify playlist to a youtube playlist.

**Comment by codetheweb** [comment]
@jagrosh a quick search through the issues yields a lot of similar requests; would it be possible to have a function that auto converts a Spotify album/playlist/song to the equivalent YouTube source?

**Comment by jagrosh** [comment]
Searching spotify is (as far as I know) not possible without an API key. I won't be adding features that require keys (except a Discord bot token). Additionally, not all songs that are available on Spotify are available on YouTube. 

If there were a way to see the contents of a spotify playlist without any additional API keys, I would consider adding some feature related to this.

**Comment by codetheweb** [comment]
Ok, I understand - thank you for the response.  (Although having users [create Spotify API keys](https://developer.spotify.com/dashboard/applications) is fairly trivial. 🤷‍♂)

**Comment by jagrosh** [comment]
It may seem trivial to someone who is familiar with how authentication and API keys work, but for the average user of this software (many of which are international and may not have English as a native language for following the instructions I provide), having an entire separate series of steps just to get an integration working would be very complicated and confusing.
