### ISSUE TITLE
suggestion: shuffle for playlist

### ISSUE THREAD

**Issue by ChimCuriosity** [jagrosh/MusicBot#26]
hello i was wondering if you could make playlists shuffle so everytime you start a playlist it doesnt always be same song order all the time?

**Comment by shikhir-arora** [comment]
Unless I'm missing something - you can just use the shuffle command after loading the playlists. Do you mean autoplay? Either way, you should be able to do `{prefix}shuffle` after loading the playlist to do that.

**Comment by oyath** [comment]
Adding onto this, if it hasn't been suggested I think having the option to have the autoplaylist shuffle would help it out a little bit, it would make just afking in the music rooms generally more enjoyable

**Comment by jagrosh** [comment]
I've been theory-crafting some different ways to handle shuffling the autoplaylists. A couple of my ideas:
1. Put something inside the playlist file (like a `#shuffle=true`) to indicate that it should be shuffled
2. Have a per-guild or global setting to shuffle autoplaylists
3. Just always shuffle autoplaylists
I personally like option 1 the best; what are others' thoughts?

**Comment by oyath** [comment]
Well, because the playlists support urls for entire youtube playlists would adding a shuffle in the playlist file just shuffle those playlists or the entire contents of the playlist? This might be a kind of dumb question but i'm having trouble picturing it

**Comment by jagrosh** [comment]
This is available as of build [`0.0.6`](https://github.com/jagrosh/MusicBot/releases/latest). You can add `#shuffle` or `//shuffle` as a single line within a playlist file, and all songs are shuffled after loading (yes, youtube playlists have their songs shuffled as well).
