### ISSUE TITLE
[Bug Report] !play doesnt always work

### ISSUE THREAD

**Issue by RaymondSchnyder** [jagrosh/MusicBot#260]
**Describe the bug**
Since the newest version 0.2.4, !play doesnt always work and needs a restart to "fix" it.

**To Reproduce**
1. Run Bot
2. Run it for a while
3. At a certain point, maybe after days of runtime, !play stops working

**Expected behavior**
!play should always work.

**Screenshots**
Screenshots dont help in this case.

**Version Info (please complete the following information):**
 - Operating System: [Linux 64bit]
-  Java Version OpenJDK 8u221
 - JMusicBot Version: [0.2.4]

**Additional context**
This started in the newest version 0.2.4.
I looked around in the commits from 0.2.3 to 0.2.4 (i know a bit of java myself) and found no commit which could be the cause to this issue.

**Comment by jagrosh** [comment]
How does the command stop working? Can you share logs from the console for what happens when you try to play a song?

**Comment by RaymondSchnyder** [comment]
I would like to share logs, but nothing happens.
What happens:
1. i type !play song
2. musicbot finds the song, puts it into queue (queue is empty before)
3. It wont start playing, pausing / resuming doesnt do anything.
4. It stays that way till i restart the bot (container)

Sadly the logs give no clue why this happens, is it possible to see debug logs maybe?

**Comment by jagrosh** [comment]
What kinds of songs are you trying to play (youtube/soundcloud/local files/streams)? Does the same thing happen when trying a different type of song (for example, if youtube songs stop working, do local files work)? Does the nowplaying bar stay at 0:00 or does it advance?

To enable the debug logs, you'll need to open up the jar and edit the logback.xml file; I'll try to work out an easy way to set this up in a future release.

**Comment by RaymondSchnyder** [comment]
> 
> 
> What kinds of songs are you trying to play (youtube/soundcloud/local files/streams)? Does the same thing happen when trying a different type of song (for example, if youtube songs stop working, do local files work)? Does the nowplaying bar stay at 0:00 or does it advance?
It were youtube and soundcloud songs.
I never tried local files, im putting some local files on the server, if it happens again.

> To enable the debug logs, you'll need to open up the jar and edit the logback.xml file; I'll try to work out an easy way to set this up in a future release.
Okay nice to know, could you note that in the wiki somewhere?

The issue stopped occurring/disappeared after i rebuilded the dockerimage with the same dockerfile a few days ago.

I will reopen this issue if it happens again, but it is unlikely, i guess it was just a temporary "bug".

**Comment by jagrosh** [comment]
I do want to note that there is no official docker support at this time; if you're seeing strange behavior, always try running one of the downloadable jars from the releases page.
