### ISSUE TITLE
[Bug Report] AAC(m4a) Play issue

### ISSUE THREAD

**Issue by Anko777** [jagrosh/MusicBot#263]
**Describe the bug**
When AAC play, sound pitch is so slow.

**Version Info (please complete the following information):**
 - Operating System: MacOS Mojave 10.14.6
 - JMusicBot Version: 0.2.4
 - Music files: AAC 320k CBR **48.0kHz**

**Comment by jagrosh** [comment]
Which java version are you running? Also, is the sound playing slowly, is the pitch low, or both?

**Comment by Anko777** [comment]
>Which java version are you running? 

Java 8 Update 221

>Also, is the sound playing slowly, is the pitch low, or both?

pitch low

**Comment by Sanduhr32** [comment]
Sounds normal to me. Seems to be fixed.

**Comment by MichailiK** [comment]
This issue is stale. Additionally, AAC audio seems to be playing fine as of writing. If this isn't the case, simply reply & I'll reopen this issue.
