### ISSUE TITLE
Can't play mp3

### ISSUE THREAD

**Issue by gurin3** [jagrosh/MusicBot#266]
Even if the downloaded mp3 music is played, "Error loading: Unknown file format." Is displayed or a youtube video plays.
<img width="279" alt="無題" src="https://user-images.githubusercontent.com/54358522/63428961-c9e3f400-c453-11e9-9014-c98b0b4cd1e8.png">

**Comment by gurin3** [comment]
The URL of the downloaded location does not respond, but m4a and ogg react but no sound
<img width="476" alt="無題" src="https://user-images.githubusercontent.com/54358522/63429535-488d6100-c455-11e9-8c6b-330335df05e3.png">

**Comment by Sanduhr32** [comment]
Have you tried placing a file where u start the bot? then try ./file.mp3
I'm unsure if it plays windows paths like that or not. Maybe the common way of noting unix paths works.

**Comment by jagrosh** [comment]
It looks like the mp3 file might be corrupted or not actually that format, as playing locally or via URL should both work. Also, are there any logs that get posted to the console when you try to play this file?

**Comment by gurin3** [comment]
I get the same error with mp3 files from different sites
Console shows error
By the way, it works normally in youtube url
Used site https://maoudamashii.jokersounds.com/list/bgm10.html
![image](https://user-images.githubusercontent.com/54358522/63668013-c1ebd180-c810-11e9-95dc-8e5dbc020572.png)

**Comment by jagrosh** [comment]
Which Java version are you using?

**Comment by gurin3** [comment]
Done
It seems that the version was not up to date
thank you very much
