### ISSUE TITLE
[Feature Request] add a lang translate

### ISSUE THREAD

**Issue by TwerkRekt** [jagrosh/MusicBot#274]
**Is your feature request related to a problem? Please describe.**
No just suggestion

**Describe the solution you'd like**

**Describe the basic flow/steps of using this feature**
How this feature would be used:
maybe add a lang.txt for translate bot

**Additional context**

**Have you confirmed that this idea is not already described here?**
https://github.com/jagrosh/MusicBot/projects/1

**Comment by jagrosh** [comment]
[Duplicate of an existing planned feature](https://github.com/jagrosh/MusicBot/projects/1#card-3994842)
