### ISSUE TITLE
[Bug Report] Issues when server shuts down

### ISSUE THREAD

**Issue by MetrixYT** [jagrosh/MusicBot#277]
**Describe the bug**
Whenever a server gets shut down on discords end "due to a temporary outage" and then gets put back up, the bot still thinks its in the voice channel.

**To Reproduce**
1. Invite the bot to a voice channel
2. Figure out some way to create a server outage

**Expected behavior**
I would like the bot to detect that there is a server outage, and then leave and join the server again, or have a command to do that.

**Screenshots**
N/A

**Version Info (please complete the following information):**
 - Operating System: Windows 10
 - JMusicBot Version: 0.2.3

**Comment by Sanduhr32** [comment]
This is kind of intended because it never receives a disconnect signal. How would it know to disconnect?

**Comment by MetrixYT** [comment]
I also mentioned that there could be a command for it, there didn't seem to be a way to solve this aside from restarting the bot

**Comment by jagrosh** [comment]
If the `stop` command doesn't solve this, then there is not really any possible solution implementable here. Also, you listed version 0.2.3; please test on the latest version before reporting a bug.
