### ISSUE TITLE
Play a song .. skip it .. play it again bot wont run

### ISSUE THREAD

**Issue by mohad666** [jagrosh/MusicBot#279]
**Describe the bug**
got a 3 bots in the same server 

if your run first one then skipped it ... (bot leaves channel ) >> then try to play again a song it enters the channel but didnt play the music .

**To Reproduce**

if your run first one then skipped it ... (bot leaves channel ) >> then try to play again a song it enters the channel but didnt play the music .

**Version Info (please complete the following information):**
 - Operating System: linux centos 64x 
 - JMusicBot Version:  0.2.5

**Comment by Sanduhr32** [comment]
Any Console log?

**Comment by mohad666** [comment]
Hey again thanks for such a quick response.
Ended up the issue is discord related not only ur bot got that...most of
music bots did that as well ...

Once u get in and out from a channel couple of time there will be no voice
(Stay in channel=false)

Ended it up to solve the issue make it =  true . So even if u skip wont
leave channel
