### ISSUE TITLE
[Feature Request] Spotify URL Compatible

### ISSUE THREAD

**Issue by TsuboiKlein** [jagrosh/MusicBot#280]
**Is your feature request related to a problem? Please describe.**
This is not a problem. Just a simple feature request.

**Describe the solution you'd like**
The bot can manage Spotify links, and play music through the spotify track/playlist URL. 

**Describe the basic flow/steps of using this feature**
How this feature would be used:
If i use the **[prefix]play spotify URL** command, play the music. 

**Additional context**
Like this:
https://i.imgur.com/0WpJOKt.jpg

**Have you confirmed that this idea is not already described here?**
https://github.com/jagrosh/MusicBot/projects/1

**Comment by jagrosh** [comment]
Unfortunately this is not possible, spotify's API is not open and they don't allow stuff like bots to stream from their service.
