### ISSUE TITLE
[Bug Report] Can't hear anything with .play after .stop

### ISSUE THREAD

**Issue by codetheweb** [jagrosh/MusicBot#284]
**Describe the bug**

I'm not entirely sure if this is a fixable issue or not, may be related to https://github.com/jagrosh/MusicBot/issues/119.  However, doing something similar with [Rythm](https://rythmbot.co/) works just fine.

If you're in a voice channel and use `.play` to start a song, then disconnect the bot with `.stop`; subsequent `.play` commands result in the bot connecting to the VC but being silent until you disconnect / reconnect on the VC.

The bot is only on one server.

**To Reproduce**
1. Run `.play music`
2. Run `.stop`
3. Run `.play music`

**Expected behavior**

I should be able to hear the bot when it reconnects.

**Version Info (please complete the following information):**
 - Linux, Docker
 - Java 1.8.0_221 (server edition)
 - JMusicBot Version: 0.2.5

(I tried running on Windows without Docker as well with the same result.)

**Comment by jagrosh** [comment]
This is a Discord bug, unrelated to JMusicBot.

**Comment by codetheweb** [comment]
Ok, do you happen to know how Rythm works around it then?  Doing something similar (`!play music` / `!disconnect` / `!play music`) with it works fine.

**Comment by codetheweb** [comment]
Might be related: https://github.com/DV8FromTheWorld/JDA/issues/1068.
