### ISSUE TITLE
[Feature Request] direct links support | Spotify -> Youtube

### ISSUE THREAD

**Issue by Dragonblitz10** [jagrosh/MusicBot#288]
**Is your feature request related to a problem? Please describe.**
this is not really an issue but often enough i want to play songs i have an direct link to or its on spotify.

**Describe the solution you'd like**
I would either have support for spotify (which searches for them on youtube) or allow direct links to work and allow bot owners to disable/enable that to protect themselves.

**Describe the basic flow/steps of using this feature**
How this feature would be used:
user runs prefix play https://directlink.com/song.mp3 and the bot will play the song 

**Have you confirmed that this idea is not already described here?**
Yes

Thank you for making an easy self-host music bot and I wish you the best of luck

**Comment by jagrosh** [comment]
Direct links to mp3s and other supported formats already work.

Spotify cannot be supported, as their API is not open without an API key, and features requiring additional keys will not be added.

**Comment by Dragonblitz10** [comment]
alright i read the other issues too about it, i was also going to comment that would it be possible to add it as a disabled module and let those who know how to use it? or is that still under additional keys will not be added?

**Comment by jagrosh** [comment]
If it's a listed feature, and requires additional keys, people will get confused. I don't want to add features that are difficult or confusing to use, as it means that I have to spend even more time writing detailed documentation (time that could be spent improving the existing features).

**Comment by Dragonblitz10** [comment]
alright I just wanted to make sure if it would ever be added but thank you for the quick response, do you have a discord server?

**Comment by jagrosh** [comment]
My development server can be found [here](https://discordapp.com/invite/0p9LSGoRLu6Pet0k)
