### ISSUE TITLE
[Feature Request] Unique game status per discord server even if there needs to be 2 bots

### ISSUE THREAD

**Issue by johncsuti** [jagrosh/MusicBot#295]
**Is your feature request related to a problem? Please describe.**
Nope just trying to use the bot on more then one server and i can only set the game once for the entire bot

**Describe the solution you'd like**
Changing the game status per server under the serversettings.json

**Describe the basic flow/steps of using this feature**
How this feature would be used:
configuration like it is now

**Have you confirmed that this idea is not already described here?**
https://github.com/jagrosh/MusicBot/projects/1
Yes

**Comment by jagrosh** [comment]
Yeah, creating a second bot is the only practical solution here. Normally you can't have a different status in different servers. The exception would be doing some funky sharding, but even that might not even be possible with some servers (and the math is tricky, making the bot join a new server would mean it would have to reconnect entirely, and it would have to connect twice at every startup just to get the server list and do a bunch of math to figure out which shards to start).

**Comment by johncsuti** [comment]
So i would need to run 2 instances of the bot in order to change the game status?

**Comment by MichailiK** [comment]
Yep. 2 separate instances that run 2 separate bots.

**Comment by johncsuti** [comment]
> 
> 
> Yep. 2 separate instances that run 2 separate bots.

i was afraid of that

**Comment by johncsuti** [comment]
Although i do wonder if i can run the bot off google's free cloud options... hmm
