### ISSUE TITLE
[Bug Report] Changing Bot Volume Crashes Entire Bot

### ISSUE THREAD

**Issue by DarkTerrorWolf** [jagrosh/MusicBot#298]
**Describe the bug**
When I type into Discord (calling key)volume (any volume number that isn't 100) The bot stops laying music and the console log is overloaded with errors

**To Reproduce**
run the bot and ask it to change the volume to 5 and have to bot play music or change it while the bot is playing music.
**Expected behavior**
the bot to get quieter or louder depending on what the last volume number was

**Screenshots**
![JagroshCrash1](https://user-images.githubusercontent.com/56730822/67103498-190b8400-f17a-11e9-9f3f-4e90973ebaf8.PNG)
![JagroshCrash2](https://user-images.githubusercontent.com/56730822/67103501-1a3cb100-f17a-11e9-8ec4-567dac7fa25f.PNG)

**Version Info (please complete the following information):**
 - Operating System: Windows 10 1903
 - JMusicBot Version:0.2.5
- Java Version:1.8.0

**Comment by jagrosh** [comment]
You're running this on 32-bit java. You must use 64-bit.
