### ISSUE TITLE
[Bug Report] No songs want to play now.

### ISSUE THREAD

**Issue by VanillaChan6571** [jagrosh/MusicBot#299]
**Describe the bug**
Bot unusable :/

**To Reproduce**
1. Run command !play song
2. Errors and plays no music

**Expected behavior**
Play The Music

**Version Info (please complete the following information):**
 - Operating System: Windows 10 Pro
 - JMusicBot Version: 0.2.5

**Additional context**
https://hastebin.com/iquxilimez.rb

**Comment by jagrosh** [comment]
You're being ratelimited by youtube.

**Comment by VanillaChan6571** [comment]
How would I fix this?

**Comment by jagrosh** [comment]
Host from a different IP, and make sure that you don't have any other bots trying to access youtube from that same IP

**Comment by VanillaChan6571** [comment]
Fixed. Changed IP's
