### ISSUE TITLE
AWS

### ISSUE THREAD

**Issue by BottyRBLX** [jagrosh/MusicBot#30]
How would one run the bot on AWS? I've tried and failed.

**Comment by BottyRBLX** [comment]
anyone?

**Comment by Matthww** [comment]
Tried and failed. Errors?

**Comment by aliasfalse** [comment]
^^ What precise problems have you had? I've run it on Digital Ocean with great success.

**Comment by jagrosh** [comment]
Feel free to re-open this issue if you have more information about what you've tried and has failed.
