### ISSUE TITLE
[Bug Report] When i try to change the volume the bot stops.

### ISSUE THREAD

**Issue by silenta00** [jagrosh/MusicBot#300]
**Describe the bug**
when i ever try to change the volume voice or try to do the repeat for the bot it makes a new file called serversettings.json and the bot never play  any song until i delete the file and run it again
**To Reproduce**
1. Run with '...'
2. Do a command '....'
3. Some other step '....'

**Expected behavior**
i think it should be normal to change the volume to whatever i want or do any command without any issues like this 
**Screenshots**
https://gyazo.com/887b45d1f5164ae3111d348fa3102ba1 --that's the 3rd file comes when i try to change something
https://gyazo.com/e0cfb920f988cdb1a77b33a66cbe56fe   --here's the file when i open it

**Version Info (please complete the following information):**
 - Windows 64bit
 - JMusicBot-0.2.5-Windows.jar

**Additional context**
i wish u could help me with this problem i'm not sure 100% if it's a bug for me only or for everyone else , but in the past my friends used to download ur versions and everything was perfect .

**Comment by jagrosh** [comment]
You're running 32-bit java. Install and use 64-bit java.
