### ISSUE TITLE
[Feature Request] Need Spotify integration. 

### ISSUE THREAD

**Issue by jvelasq** [jagrosh/MusicBot#302]
**Is your feature request related to a problem? Please describe.**
I tried to play a spotify playlist and it would pull a random video from youtube.

**Describe the solution you'd like**
to be able to copy a spotify playlist and be able to get the correct song to play.

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. Copy spotify playlist.
2. Paste with play command.
3. Bot pulls song from spotify 
OR
4. Bot pulles song name and searches youtube for song.

**Have you confirmed that this idea is not already described here?**
https://github.com/jagrosh/MusicBot/projects/1

No request about spotify has been made.

**Comment by jagrosh** [comment]
Please search closed pull requests as well; a spotify integration is not possible.

**Comment by DarkTerrorWolf** [comment]
My good sir. If minecraft can run on java since 2003. im positive you can make a spotify (OR COPY ONE "Hint hint, hudge nudge") and make it work.

**Comment by jagrosh** [comment]
If you take a look at the existing closed issues it is explained in more detail why it won't be added.

**Comment by jvelasq** [comment]
I have a different music bot that can play songs from spotify, So this is possible.
