### ISSUE TITLE
[Bug Report] YouTube playback no longer working

### ISSUE THREAD

**Issue by redblade7** [jagrosh/MusicBot#304]
**Describe the bug**
As of at least 10/23/2019, YouTube links are no longer playing.

Discord shows an error: ":no_entry_sign: Error loading track."

Here is an example stdout:

> [07:58:54] [ERROR] [DefaultAudioPlayerManager]: Error in loading item https://www.youtube.com/watch?v=EbDxn89TdZc
> com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading information for a YouTube track failed.
>         at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
>         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:233)
>         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadFromUrlWithVideoId(YoutubeAudioSourceManager.java:323)
>         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadFromMainDomain(YoutubeAudioSourceManager.java:260)
>         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadNonSearch(YoutubeAudioSourceManager.java:330)
>         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:189)
>         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:128)
>         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437)
>         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419)
>         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218)
>         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>         at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
>         at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: java.io.IOException: Invalid status code for video page response: 429
>         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.getTrackInfoFromMainPage(YoutubeAudioSourceManager.java:364)
>         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:201)
>         ... 14 common frames omitted

Occasionally I would see this message in stdout as well, not sure if it is related:

> [08:01:06] [WARN] [AudioWebSocket]: Failed to establish websocket connection: NOT_SWITCHING_PROTOCOLS - The status code of the opening handshake response is not '101 Switching Protocols'. The status line is: HTTP/1.1 503 Service Unavailable
> Closing connection and attempting to reconnect.

**To Reproduce**
1. Run JMusicBot
2. Play a YouTube link

**Expected behavior**
The YouTube link should play properly instead.

**Version Info (please complete the following information):**
 - Operating System: [Slackware 14.2 64-bit (running on a VPS)]
 - JMusicBot Version: [v0.2.5 (JMusicBot-0.2.5-Linux.jar)]
 - Java Version: [AdoptOpenJDK v11.0.4, later updated to v11.0.5]

**Additional context**
N/A

**Comment by jagrosh** [comment]
`Caused by: java.io.IOException: Invalid status code for video page response: 429`

429 means YouTube is ratelimiting you. This is a thing YouTube has recently started enforcing more strictly, and unfortunately there is no "fix" for this besides waiting it out (don't attempt to load anything from YouTube for several days) or hosting from a new location (host on a different IP address).
