### ISSUE TITLE
[Feature Request] Add YouTube Music support (music.youtube.com)

### ISSUE THREAD

**Issue by KortyBoi** [jagrosh/MusicBot#315]
**Is your feature request related to a problem? Please describe.**
_No, I only get the error saying the bot can't play from said domain._

**Describe the solution you'd like**
_I would like to suggest running this command to play music from YouTube Music
[p]play https://music.youtube.com/watch?v=x[&list=x]
And let it ask to play the playlist, but maybe hopefully only music instead of other videos (if possible)_

**Describe the basic flow/steps of using this feature**
_[p]play https://music.youtube.com/watch?v=x[&list=x]_

**Have you confirmed that this idea is not already described here?**
https://github.com/jagrosh/MusicBot/projects/1
_Yes_

**Comment by johncsuti** [comment]
That would have to do with lava player as this discord bot uses it to pull data from youtube or SoundCloud. Maybe you should try asking them. I don’t see it mentioned anywhere in there code either.

**Comment by jagrosh** [comment]
Yep, this would be a feature of lavaplayer, so you'll need to request it on [the lavaplayer repository](https://github.com/sedmelluq/lavaplayer).
