### ISSUE TITLE
[Feature Request] Remove skip vote

### ISSUE THREAD

**Issue by PhyizziX** [jagrosh/MusicBot#317]
In the config file or in server setting you should be able to enable or disable and customise vote skipping for example
Voteskipping = true/false
Votesneeded = 4

I just hate having the voting option especially if there's only a couple people in the server and they're busy or just don't want to have to tab out of a game or all skip a song if you want to skip a song cause you put the wrong song on

**Comment by jagrosh** [comment]
You can always skip songs that you added; the vote is only among the people that did not add the song. Additionally DJs and admins can always forceskip songs. If you'd like to request a change to the voting system, please use the feature request template.
