### ISSUE TITLE
[Feature Request] Change voting system

### ISSUE THREAD

**Issue by PhyizziX** [jagrosh/MusicBot#319]
**Is your feature request related to a problem? Please describe.**
So I have multiple playlists set up and auto playlists setup, I've noticed when people want to skip the auto playlist song they require votes and if someone puts on songs and then goes afk or leaves and someone else wants to skip it they can't without votes so they end up just killing the bot and using another one which makes having this point irrelevant 

**Describe the solution you'd like**
My discord server personally does not like the voting system and has disabled it on all previous bots I would like to be able to remove the option for voting and just make it so that there's no DJ role or any of that nonsense

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. Set something VoteSkipEnabled = true/flase
2. Run some command 'hey Alexa voteskip off/on yes/no'

**Additional context**
We have called our bot Alexa and use the prefixes Alexa and hey Alexa for the meme so that's why I said that above

**Have you confirmed that this idea is not already described here?**
https://github.com/jagrosh/MusicBot/projects/1
Yes I can find it anyone right now we're just using another bot to look for someone using the skip command and then adding votes or just force skipping

**Comment by jagrosh** [comment]
For the record, you can set the DJ role to @ everyone, and then anyone can `forceskip` (and use all the DJ commands). This might be a reasonable alternative until more voting options are available.

**Comment by RyanL-29** [comment]
Can have any voting system just having number of user vote and skip. That not using the user ration in the channel. Just enough rote can skip. Or can let us to change the skip ratio

Skip ratio 0.2

**Comment by MichailiK** [comment]
A `setskip` command has been implemented (<https://github.com/jagrosh/MusicBot/commit/c4de816c7cb98ba36ef969018f61d6372239b5e6>) and comes with the next release, version 0.3.6. This command allows you to set the percentage of people wanting to skip the song. In your case, you can do `setskip 0` to allow anyone to skip the track immediately.
