### ISSUE TITLE
Other Languages

### ISSUE THREAD

**Issue by pedroricardo** [jagrosh/MusicBot#32]
The bot should have a translation function for other languages like pt-br for example !!

**Comment by jagrosh** [comment]
This is something I plan to add eventually

**Comment by jagrosh** [comment]
Full translation support is on the [https://github.com/jagrosh/MusicBot/projects/1](https://github.com/jagrosh/MusicBot/projects/1), and will be available shortly after full translation support is added to JDA-Utilities
