### ISSUE TITLE
How to add something to the Bots about command or an other command.

### ISSUE THREAD

**Issue by Spacelord09** [jagrosh/MusicBot#320]
Hey!

How can I add something to the "about" or other command(s)?

**Comment by jagrosh** [comment]
Modifying the output of commands, and adding additional commands, is not a native feature of JMusicBot.

**Comment by Spacelord09** [comment]
@jagrosh I can edit the sources and build my own version. But I need some informations to find the coresponding files to edit.

**Comment by Spacelord09** [comment]
@jagrosh I can edit the sources and build my own version. But I need some informations to find the coresponding files to edit.

**Comment by Spacelord09** [comment]
> Modifying the output of commands, and adding additional commands, is not a native feature of JMusicBot.

@jagrosh I can edit the sources and build my own version. But I need some informations to find the coresponding files to edit.

**Comment by jagrosh** [comment]
Like it says on the readme, and like I've replied, no support will be provided for attempting to edit the bot yourself.
