### ISSUE TITLE
[Feature Request] Lyrics source.

### ISSUE THREAD

**Issue by HexaMetrics** [jagrosh/MusicBot#323]
Lyrics sources do not find music. Could you add ksoft as lyrics source? Ksoft is the best.

Thank you. 

Ksoft.si

**Comment by jagrosh** [comment]
The source you suggested, ksoft, does not appear to have an open (unauthenticated) API. Do you have an example of a song that you were not able to find on one of the existing lyrics sources?

**Comment by HexaMetrics** [comment]
Yeah,
https://www.youtube.com/watch?v=-hMj_-F7Gus

Song name: Yıldız Tilbe - Şivesi Sensin Aşkın

I tried A-Z Lyrics with Genius and MusicMatch, but it doesn't find it.

Would you try it? Thanks!

**Comment by HexaMetrics** [comment]
My musicbot version: 0.2.6

**Comment by jagrosh** [comment]
Can you run the `debug` command and paste the output here?

**Comment by jagrosh** [comment]
Closing as this has been unanswered for several months
