### ISSUE TITLE
Emoji Error

### ISSUE THREAD

**Issue by LogischerJonasHD** [jagrosh/MusicBot#328]
If it try to put in my own emoji's, that are available on my server, into the config.txt file the bot will just write the text down for example: :hype:
Can this be fixed? It would be amazing!
![image](https://user-images.githubusercontent.com/58107194/69477713-e0e70900-0de9-11ea-80df-da13f99d6568.png)

**Comment by Sanduhr32** [comment]
`:hype:` gets replaced by your discord client to their internal structure thats used. Just use their internal format for custom emotes `<:name:id>`.
Add an `a` before the first colon if your emote is animated.

**Comment by LogischerJonasHD** [comment]
@sanduhr32 can you give an example, I do not know how to do it! And thx for the answer

**Comment by Djinnistorm** [comment]
> 
> 
> @Sanduhr32 can you give an example, I do not know how to do it! And thx for the answer
@LogischerJonasHD 
For my emote called :jackAyaya: here is what I would use:
`success = "<:jackAyaya:530317492371980289>"`
For my animated emote :IllyaFreakout: I would add an a beforehand, like this:
`warning = "<a:IllyaFreakout:627591954137350175>"`
You need to get the id number of the emote in question using the developer tools inspector or something, google it.

**Comment by Sanduhr32** [comment]
Enabling developer mode or opening the image link of the emote in the browser also works.

**Comment by jagrosh** [comment]
You can easily see the full text of the emote by typing `\:emote:` and copying everything that prints out. You need to include this full text in the config, in quotes, as shown in a previous comment.

![image](https://user-images.githubusercontent.com/12754382/69717381-f609b380-10d9-11ea-90b4-2ecfd769cdf2.png)
