### ISSUE TITLE
AutoPause 

### ISSUE THREAD

**Issue by pedroricardo** [jagrosh/MusicBot#33]
The music should stop or the bot could automatically disconnect when the bot is alone on a voice channel!

**Comment by jagrosh** [comment]
This will likely be a config option in the future, something like `whenempty=X` where X can be `nothing`, `pause`, or `stop`

**Comment by pedroricardo** [comment]
perfect

**Comment by pedroricardo** [comment]
Do you have a forecast for when the autopause function will be available?

**Comment by jagrosh** [comment]
I don't have an ETA on this feature yet, because it is a bit more involved to handle the different cases. I'm also closing this now because it's on the [planned features list](https://github.com/jagrosh/MusicBot/projects/1)

**Comment by xeranas** [comment]
I only see pause command on features list while ticket was about disconnecting or pause music when bot is alone on a voice channel. Do I miss some configuration regarding of auto pause?

**Comment by jagrosh** [comment]
https://github.com/jagrosh/MusicBot/projects/1#card-4483529
