### ISSUE TITLE
[Feature Request] bot uptime command

### ISSUE THREAD

**Issue by RootAndroid58** [jagrosh/MusicBot#332]
**Is your feature request related to a problem? Please describe.**
simply show how much time is the bot online

**Describe the solution you'd like**
like : I have been online for: 0 days, 20 hours, 19 minutes, 42 seconds.

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. enter the command p.uptime
2. bot displays the output

**Additional context**
-

**Have you confirmed that this idea is not already described here?**
Yes (i guess)

**Comment by MichailiK** [comment]
There's "Last restart" at the bottom of the about command. Perhaps this is what you're looking for?
![image](https://user-images.githubusercontent.com/39029839/76148116-65148200-60a3-11ea-87f1-ae13650fa61c.png)

**Comment by jagrosh** [comment]
After additional consideration, I don't think a separate command for this is needed, as it was noted that the information can be found in the contents of the `about` command.
