### ISSUE TITLE
[Bug Report] Trouble connecting to WebSocket

### ISSUE THREAD

**Issue by midspam** [jagrosh/MusicBot#333]
**Describe the bug**
The bot(0.2.6) has been working perfectly fine few days ago. Suddenly bot does not appear online after starting .jar file. It's not invisible. When given commands the bot does not response. Console shows multiple times of reconnecting to WebSocket. Config.txt was not touched before the bug.

**To Reproduce**
1. Start up .jar file and wait a few minutes.

**Expected behavior**
Bot does not appear online and console states repeated attempts of connecting and reconnecting.

**Screenshots**
![0Cucbk6](https://user-images.githubusercontent.com/55208669/70380528-cbee9780-190a-11ea-8a82-f9dac1da2fa4.png)

**Debug Info**
Windows 10
JMusicBot Version: v0.2.6

**Comment by jagrosh** [comment]
[Discord is currently undergoing API issues and latency](https://status.discordapp.com/)
