### ISSUE TITLE
[Bug Report] Error loading: This video may be inappropriate for some users.

### ISSUE THREAD

**Issue by Flinvoltx** [jagrosh/MusicBot#336]
**Describe the bug**
Attempting to play some songs from YT results in "Error loading: This video may be inappropriate for some users."

**To Reproduce**
Try to play any video from YT which has age restriction without beeing signed in.
Example: https://www.youtube.com/watch?v=qy1zbbosiTQ

**Debug Info**
System Properties:
  java.version = 1.8.0_231
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 1.8.0_231-b11
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Windows 7

JMusicBot Information:
  Version = 0.2.6
  Owner = 260797067977293824
  Prefix = /
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = true
  StayInChannel = false
  UseEval = false
  UpdateAlerts = false

Dependency Information:
  JDA Version = 3.8.3_464
  JDA-Utilities Version = 2.1.5
  Lavaplayer Version = 1.3.25

Runtime Information:
  Total Memory = 97
  Used Memory = 28

Discord Information:
  ID = 482226618832781313
  Guilds = 1
  Users = 12

**Comment by jagrosh** [comment]
This appears to be standard behavior for an age-restricted videos; even on youtube itself you can't view those videos without logging in.

**Comment by ehsawyer** [comment]
@jagrosh Sorry to ressurect a "dead thread" but I've been having the same issue on 0.2.6. I tried switching back to 0.2.5 and I could once again load those YouTube videos.

**Comment by hartmannaf** [comment]
The problem seems to be gone for me with the latest version.
