### ISSUE TITLE
[Feature Request] Restart bot command 

### ISSUE THREAD

**Issue by RootAndroid58** [jagrosh/MusicBot#339]
**Is your feature request related to a problem? Please describe.**
A simple restart bot command for multiple owners which will restart the bot instead of going to web server and restarting there

**Describe the basic flow/steps of using this feature**
How this feature would be used: suppose prefix is p.
1. p.restart 
2. return message to dm to owner that bot restarted successfully 

**Additional context**
-

**Have you confirmed that this idea is not already described here?**
IDK

**Comment by jagrosh** [comment]
This is not possible, as the bot can't easily (nor should it) control its surrounding environment. Consider instead writing a script that runs the bot in a loop, and then use the shutdown command to restart it.
