### ISSUE TITLE
[Bug Report] Youtube Live play error Lavaplayer

### ISSUE THREAD

**Issue by RootAndroid58** [jagrosh/MusicBot#341]
**Describe the bug**
Lavaplayer is giving me error while playing live songs 

here is the log file https://pastebin.com/0rc2k51d

**To Reproduce**
1. play any live song from youtube 
2. does nothing 
3. and nothing 

**Expected behavior**
Should play the song 

**Debug Info**
https://pastebin.com/0rc2k51d

**Additional context**
none

**Comment by louis921222** [comment]
I’ve been experiencing this problem for a while now too, but I just tried it again and it seems to be working now c:

**Comment by MichailiK** [comment]
This issue is stale, and YouTube livestreams work as of writing. If playback issues arise again, open a new issue.
