### ISSUE TITLE
[Feature Request] custom stauts

### ISSUE THREAD

**Issue by thetechguy-cpu** [jagrosh/MusicBot#343]
**Is your feature request related to a problem? Please describe.**

no.

**Describe the solution you'd like**

something like: customStatus= custom status here in the config.txt. 

**Describe the basic flow/steps of using this feature**

How this feature would be used:
1. type customStatus= custom status E.G: customStatus= music!
2. Run the bot. The custom status should be seen in discord now. 

**Have you confirmed that this idea is not already described here?**
https://github.com/jagrosh/MusicBot/projects/1
yes.

**Comment by jagrosh** [comment]
This is already possible, just set the `game` (the displayed text) and/or `status` (online/idle/dnd/invisible) field in the [config file](https://github.com/jagrosh/MusicBot/wiki/Example-Config). Alternatively, you can use the [setgame command](https://github.com/jagrosh/MusicBot/wiki/Full-Command-Reference#setgame-game) and [setstatus command](https://github.com/jagrosh/MusicBot/wiki/Full-Command-Reference#setstatus-status) to set the game and status temporarily.

**Comment by thetechguy-cpu** [comment]
no what I mean is the new custom status that discord released. without the playing: before it.

**Comment by jagrosh** [comment]
That is not possible for bots

**Comment by thetechguy-cpu** [comment]
ah. ok
