### ISSUE TITLE
ERROR POM.xml

### ISSUE THREAD

**Issue by pedroricardo** [jagrosh/MusicBot#35]
When trying to compile the bot's source code in netbeans, it gave an error in maven.
I tried to solve more not to get, could of majudar ??

**Comment by TheMonitorLizard** [comment]
You are not supposed to compile the source code, and you will not recieve any help doing so.
If you want to run the bot, follow the setup instructions correctly.

**Comment by pedroricardo** [comment]
I am Brazilian and I have a BR server in discord, since there are no bots of songs in Portuguese, I decided to translate JMusicbot to make life easier for my community. That was the only reason I wanted to do this! But by the way I will not have help from you! OK!

**Comment by thetruestarr1337** [comment]
why we have src, when we SHOULDNT compile it? i dont get it.. i just wanted to remove the invite link the bot send in help.

**Comment by jagrosh** [comment]
You can compile if you want. However, I will not provide any support for self-compiling. I provide executables and support/feature requests/bug reports.
