### ISSUE TITLE
Bot continues to post text even when permissions are revoked

### ISSUE THREAD

**Issue by Terry-Kusunoki-Martin** [jagrosh/MusicBot#351]
I created the bot and only provided it permissions to "connect" and "speak", I did not give it any other permissions.  However, the bot continues to post responses in the text channel when issued commands.  I don't see anything in the documentation about silencing the bot.  Is this expected behavior?

**Comment by jagrosh** [comment]
Maybe you gave it Administrator, or have some other permissions error. This doesn't seem like it relates to the bot specifically; bots can't bypass the permissions they are given.
