### ISSUE TITLE
[Bug Report] Error in playback of

### ISSUE THREAD

**Issue by PremiereSetups** [jagrosh/MusicBot#355]
When trying to play anything from youtube I get the following error message. The bot will still join but no sound will come out.

https://hastebin.com/qehecutanu.rb

1. Run with /play ANYTHING

**Expected behavior**
The music bot should join and start playing music

**Screenshots**

**Debug Info**
https://hastebin.com/ikubuhaciv.coffeescript

**Comment by jagrosh** [comment]
Duplicate of #305
