### ISSUE TITLE
np command issue

### ISSUE THREAD

**Issue by meltedprocessor** [jagrosh/MusicBot#358]
running m!np to show now playing starts a now playing entry in text channel but frequently stops working.

Bot is running on a single core OVH VPS, audio playback of mp3 files hosted on another VPS via playlist is working fine and doesn't stop with good sound quality.

**Comment by jagrosh** [comment]
At the time you posted this, Discord was having outages, so that was the likely cause. If you continue to have this issue when Discord isn't having outages, please open a new issue and use the bug report template.
