### ISSUE TITLE
Playlist loading really slow

### ISSUE THREAD

**Issue by wanabrar** [jagrosh/MusicBot#37]
I have a bunch of playlist around 500-1200 songs in a single text file, and I must say the bot does take a while to start playing the first song. Like 5-15minutes. Anyway to slow down the waiting time?

**Comment by Matthww** [comment]
Same here. And it's not that the cpu maxes out or something or if I'm already playing music and queue a playlist it stutters.

**Comment by wanabrar** [comment]
It might be related to how the bot checks all the songs first before playing the playlist? Would be nice if it checks one at a time rather than all of them, so I don't have to wait a long time for it to work.

**Comment by Matthww** [comment]
I think its checking if they are all valid. And then downloads the first song

**Comment by Matthww** [comment]
869 songs takes about 8 minutes to load.

**Comment by jagrosh** [comment]
Yes, this is a known issue. The reason this happens is because it loads all songs before playing any. I have a couple ideas that I've been theory-crafting about a good solution (all related to internal things).

**Comment by wanabrar** [comment]
Nice. Well if anything reply it here I guess. I love the bot, and it does everything that I need, just the playlist is taking a while to load which is a bit of an issue, besides that good work dude. I love it

**Comment by jagrosh** [comment]
Can you see if this issue is resolved as of the [latest release (0.0.7)](https://github.com/jagrosh/MusicBot/releases/latest)?

**Comment by Matthww** [comment]
Almost instant WOW

**Comment by jagrosh** [comment]
Just like loading songs one-by-one, it takes time to load music. However, the recent change made it so that it begins playing from the playlist immediately instead of waiting for the entire list to load before playing.
