### ISSUE TITLE
How can i stop the bot from generating invite links that any user can use to invite to their server?

### ISSUE THREAD

**Issue by surenzxx** [jagrosh/MusicBot#375]
I want the bot to only be inviteable by the discord invite link. This is because I don't want other users adding my bot instance to their servers. Please advise.

**Comment by 9636513321703325854** [comment]
Why do you closed this? I also need that option, that the invite link is invisible.

**Comment by MichailiK** [comment]
It's already a feature. It depends on your "Public Bot" settting for your application
![firefox_2021-11-30_21-59-01](https://user-images.githubusercontent.com/39029839/144127292-b95a45d1-4b75-4922-9d68-80a2045eb440.png)

**Comment by 9636513321703325854** [comment]
Thanks, I didn't know that!
