### ISSUE TITLE
[Feature Request] User Pause&resume

### ISSUE THREAD

**Issue by iNaruse** [jagrosh/MusicBot#378]
Please listen to a lot of commands to use Pause & Resume even if you are not a DJ!

Reason:
You should continue to listen to the song unless a non-DJ user can't Pause or Resume and cringe in the call room.

(Translator)

**Comment by Sanduhr32** [comment]
What?

**Comment by iNaruse** [comment]
Pause Resume function that can be used by general users

**Comment by Sanduhr32** [comment]
Thanks for speaking english with me.

**Comment by jagrosh** [comment]
Please use the feature request template.
