### ISSUE TITLE
[Feature Request] Add spotify as one of the sources.

### ISSUE THREAD

**Issue by thetechguy-cpu** [jagrosh/MusicBot#379]
**Is your feature request related to a problem? Please describe.**
Sometimes, we would like to play songs from spotify.
**Describe the solution you'd like**
Someone could type !play [Spotify link] to play the song or playlist from spotify.
**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. Type in !play [Spotify link]
2. the bot will now play that song/playlist.
**Additional context**

**Have you confirmed that this idea is not already described here?**
https://github.com/jagrosh/MusicBot/projects/1
yes.

**Comment by jagrosh** [comment]
This is not possible as it would require an additional API key to read spotify lists, and spotify music can't be streamed via a Discord bot either so it would just be attempting to match titles from youtube anyway (which is unreliable at best).

**Comment by thetechguy-cpu** [comment]
but how can Groovy bot do it?

**Comment by Hax165** [comment]
I feel like it is simply a nice feature to just yoink the share link from spotify and have the bot just play it, which has a 9/10 success rate with other bots in my experience. I don't see the problem if you just keep the spotify part optional. This would actually be huge for me.

**Comment by jagrosh** [comment]
The link can't be read without a Spotify API key, and I won't be adding features that require additional API keys
