### ISSUE TITLE
[Feature Request] General user Pause&resume

### ISSUE THREAD

**Issue by iNaruse** [jagrosh/MusicBot#388]
**Is your feature request related to a problem? Please describe.**
Normal users can't pause and resume, and it's inconvenient because the song doesn't end playing unless you leave the room

**Describe the solution you'd like**
Pause & resume for general user rights

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1.If the normal user who played the song enters Pause & Resume
2. The song is paused or played

**Have you confirmed that this idea is not already described here?**
Has confirmed

**Comment by jagrosh** [comment]
Subset of #390
