### ISSUE TITLE
Suggestion: Leave Server - Command

### ISSUE THREAD

**Issue by Virus5947** [jagrosh/MusicBot#39]
Something like: **[prefix]leaveserver [serverid]**
--
Found out, that it's somehow possible with JDA: `jda.getGuildById(The ID after the command).leave();`

Would be useful, if you don't have Permissions to kick the Bot.

**Comment by jagrosh** [comment]
This is possible by enabling the `eval` command in the config. Here are a few evaluations that may be helpful:
`eval jda.guilds` - prints the list of guilds the bot is connected to
`eval jda.getGuildById("ID").leave().queue()` - leaves the guild with the id ID
