### ISSUE TITLE
[Feature Request] play spotify links

### ISSUE THREAD

**Issue by AtomicGaming666** [jagrosh/MusicBot#392]
just want it to play spotify likes 
like this and stuff 
https://open.spotify.com/track/12mGwph2YzDIlChtq3EdXP
and the playlist ones

**Comment by jagrosh** [comment]
This is not possible as it would require an additional API key to read spotify lists, and spotify music can't be streamed via a Discord bot either so it would just be attempting to match titles from youtube anyway (which is unreliable at best).

**Comment by AtomicGaming666** [comment]
ok thats cool thx for the heads up

**Comment by Elantic** [comment]
Hi, the Groovy music bot does the same, you can use the play command with Spotify links and it will search for the song on YouTube. You said that this would be unreliable but I disagree, I never had Groovy select the wrong song on YouTube, I did one time have it say that an equivalent song could not be found and it skips to the next song.

**Comment by jagrosh** [comment]
This is still impossible without a spotify api key, and as stated before I won't be adding features that require additional api keys.
