### ISSUE TITLE
[Bug Report] VEVO video won't play

### ISSUE THREAD

**Issue by Loadriku** [jagrosh/MusicBot#393]
**Describe the bug**
Any video marked by VEVO won't play. I tried several of them, none worked. My server is localized in France, and I checked many videos that played. Some of them are :
- https://www.youtube.com/watch?v=TLV4_xaYynY
- https://www.youtube.com/watch?v=c_BcivBprM0
- https://www.youtube.com/watch?v=XbGs_qK2PQA
- https://www.youtube.com/watch?v=UDfAdHBtK_Q
I did these tests also on Clarity bot on the dev discord server. Same result.

**To Reproduce**
1. Do a command '@bot play [link of a video marked by VEVO]'
2. See. The bot can have multiple behavour : Won't join in voice channel, will come and leave 1sec after, will display a ":no_entry_sign: Error loading: The uploader has not made this video available in your country." or ":no_entry_sign: Error loading: This video is not available."

**Expected behavior**
The music should play.

**Debug Info**
System Properties:
  java.version = 11.0.6
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 11
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 11.0.6+10-post-Ubuntu-1ubuntu118.04.1
  java.specification.version = 11
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.2.8
  Owner = 175659684601135105
  Prefix = @mention
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = true
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 3.8.3_464
  JDA-Utilities Version = 2.1.5
  Lavaplayer Version = 1.3.46

Runtime Information:
  Total Memory = 31
  Used Memory = 26

Discord Information:
  ID = 699671995477917767
  Guilds = 1
  Users = 108

**Additional context**
There is multiple instances of MusicBot running at the same time (to get 3 bots in one server). It shouldn't bother (3 API tokens, run well together, tried with only one bot active ...).

**Comment by Adi3000** [comment]
Hello, for information : not related by JMusicBot : I've opened chrome from my French server, those video are not available by this way.
I'm trying to find a proxy and test it both way (chrome and JMusicBot : with `-Dhttp.proxy` or `-Dhttps.proxy` options) If it's working I'll make a documentation here. If not (if lavaplayer not using classic connection), I'll debug to open an Issue for Lavaplayer or Jmusicbot (whether it related to one or the another)

**Comment by jagrosh** [comment]
I think the error message the bot displays is relatively self-explanatory; the video you're trying to play isn't available in whatever country you're hosting the bot in. You could try using a proxy as mentioned, but this is not a bug in the bot.
