### ISSUE TITLE
Doesn't run on Raspberry Pi

### ISSUE THREAD

**Issue by TimLeder** [jagrosh/MusicBot#40]
Hey
I have no problems running the bot on my windows machine, however i can't install it on my raspberry pi. I think this is caused by problems with installing JDK 1.8 on raspberry pi. The line "sudo add-apt-repository ppa:webupd8team/java" outputs "Error: could not find a distribution template for Raspbian/jessie". Obviously the referred repository doesn't support the newest Debian Jessie Image. Could you try to find a repository with jessie support?

**Comment by jagrosh** [comment]
I'll look when I get a chance, but sadly I don't have a pi to test with. If you find a repository, or just alternate setup instructions, please let me know so I can add it to the rpi setup page.

**Comment by TimLeder** [comment]
OK so I found the problem: The newest version of Raspbian Jessie selects OpenJDK 1.7 as the standard version of JDK. If you want the bot to work you will have to execute these commands:

`sudo apt-get update`
`sudo update-alternatives --config java`
Select Oracle JDK 1.8
`sudo update-alternatives --config javac`
Select Oracle JDK 1.8
`java -jar /path/MusicBot-X.Y.Z.jar -nogui`
The WebUp8 command is no longer necessary.

**Comment by jagrosh** [comment]
Added these instructions to https://github.com/jagrosh/MusicBot/wiki/Installing-JDK1.8, and referenced that page from https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi, thanks!
