### ISSUE TITLE
Lavaplayer again broken?

### ISSUE THREAD

**Issue by MrUnknownDE** [jagrosh/MusicBot#403]
Version: 0.2.8
JDA: openjdk version "11.0.6" 2020-01-14
Youtube-DL: 2020.03.24
System: Debian 10

Playback from a YouTube livestream stops after 5 seconds.

Console:
![https://77-ec.pw/TuQU6/ReBUFabe91.png](https://77-ec.pw/TuQU6/ReBUFabe91.png/raw)

**Comment by Sanduhr32** [comment]
`![]()` will embed the image in markdown.

**Comment by jagrosh** [comment]
This may be a duplicate of #405, although it is hard to tell without debug info
