### ISSUE TITLE
[Bug Report]  YOUTUBE LIVE does not play properly

### ISSUE THREAD

**Issue by yuchan2215** [jagrosh/MusicBot#405]
Uses Google Translate.
**Describe the bug**
No sound comes out when playing YouTube Live.
If you use the "nowplaying" command, the song name will be displayed.
There are no errors on the console.
![image](https://user-images.githubusercontent.com/38094366/81470702-2e83f080-9227-11ea-8a6b-b0654f9851e2.png)
![image](https://user-images.githubusercontent.com/38094366/81470730-57a48100-9227-11ea-8dbb-e7d24e9586ff.png)

**Comment by louis921222** [comment]
I’ve been experiencing this problem for a while now too, but I just tried it again and it seems to be working now c:

**Comment by MichailiK** [comment]
Closing stale & already fixed issue. If it happens again, open a new issue.
