### ISSUE TITLE
Remove Hetzner dissuasion from wiki

### ISSUE THREAD

**Issue by Dougley** [jagrosh/MusicBot#406]
[The wiki](https://github.com/jagrosh/MusicBot/wiki/24-7-Hosting#hetzner) lists Hetzner as completely unusable, however [Hetzner's IP ranges are unblocked since August 2019](https://cdn.discordapp.com/attachments/631132590820163595/645324492607848448/Screenshot_20190819-182714.png). I've tested this myself with JMusicBot and Lavalink instances and everything worked as expected. Since the ranges are no longer blocked, there's no reason why Hetzner should continue to be listed as unusable.

**Comment by jagrosh** [comment]
Wiki has been updated
