### ISSUE TITLE
[Bug Report] Volume Command Bug

### ISSUE THREAD

**Issue by TacoboiG** [jagrosh/MusicBot#407]
**Describe the bug**
Whenever I run the command "vol" the bot says that the volume has reduced but then the bot stop playing music and if i tried to let the bot leave the channel or stop it it leaves but then when i wants to play the bot again it will join and leave immediately.

**To Reproduce**
1. Run with '...'
2. Do a command '....'
3. Some other step '....'

**Expected behavior**

**Screenshots**

**Debug Info**
Newest version. 0.2.8
**Additional context**

**Comment by jagrosh** [comment]
If the bot doesn't play when you change the volume, you aren't using 64-bit java. Additionally in the future, please include the output of your debug command when making a report.
