### ISSUE TITLE
Linux (Ubuntu, CentOS, Fedora, etc)

### ISSUE THREAD

**Issue by marioandluigi878** [jagrosh/MusicBot#41]
Just wondering if this would work with Linux not the RPi but like Ubuntu, CentOS, etc as the reason why I am asking this I would be hosting the bot from a vps and can't really run anything on my end 24/7

**Comment by TheMonitorLizard** [comment]
Fairly certain you can run this on a Linux VPS
You'll still need to have [JDK1.8 installed](https://github.com/jagrosh/MusicBot/wiki/Installing-JDK1.8) and you'll need to be fairly versed in how to upload files to the VPS correctly, but it is possible.
If I recall correctly, you'll also need to run the thing with the `-nogui` flag (IE: `java -jar /path/to/MusicBot-X.Y.Z.jar -nogui`).

**Comment by jagrosh** [comment]
Yes, this works on all of those platforms. I personally have run it on Windows, Debian, and Ubuntu, but it supports many more.

**Comment by marioandluigi878** [comment]
ok sweet just wanted to make sure before I attempted to try it
