### ISSUE TITLE
Bot is leaves the channel instantly after asking a music

### ISSUE THREAD

**Issue by Hir0kee** [jagrosh/MusicBot#42]
When we search for a song, or use directly the !play command, the bot join the channel but leaves instantly...

**Comment by jagrosh** [comment]
What version are you running?
What platform are you running on?

**Comment by Hir0kee** [comment]
I'm running on the last version of the bot (0.0.7), with Raspbian  (with JDK 1.8 installed). All the commands are working, but yeah the bot keeps leaving

**Comment by jagrosh** [comment]
Did you follow the additional steps for Raspberry Pi from the wiki?

**Comment by DelKatey** [comment]
I recently experienced this issue myself. You most likely did not have the libconnector.so file added to the .jar file.

**Comment by jagrosh** [comment]
@Hir0kee can you confirm or deny that following the additional steps from https://github.com/jagrosh/MusicBot/wiki/JMusicBot-on-Raspberry-Pi solve the issue?

**Comment by jagrosh** [comment]
Feel free to re-open this if this is still happening with the latest version.

**Comment by MichailiK** [comment]
@varunbhatnagar99 see #1537

**Comment by varunbhatnagar99** [comment]
@MichailiK thanks a lot for the reply, Will downgrade to this version!
