### ISSUE TITLE
Suggestion: Forward command

### ISSUE THREAD

**Issue by TheOnlyPixels** [jagrosh/MusicBot#43]
Can you add a command that allows a DJ to fast forward the music? For example, you can do (command prefix)forward 1:00, and the song will be fast forwarded by 1 minute.

**Comment by jagrosh** [comment]
This is already on the planned features list: https://github.com/jagrosh/MusicBot/projects/1

**Comment by jagrosh** [comment]
(closing because this is on the planned features list)
