### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by phanicowner** [jagrosh/MusicBot#44]
![image](https://user-images.githubusercontent.com/29747687/28255405-68d29d36-6a84-11e7-8197-f9cb0c409329.png)
for the music bot i suggest you add something where u can join the servers and know the servers that its in. something like this: https://cdn.discordapp.com/attachments/336308100887871488/336309249598685185/unknown.png
and like or like this: https://cdn.discordapp.com/attachments/240154911449284620/336207124256260097/unknown.png
so if people are curious to know where their bots are going or where there bots are at. they can know :3. should be np eh.

you know, like the partycrasher command in which you can join the servers its in. :3

**Comment by Matthww** [comment]
This is a music bot made for simplicity. If you want join and leave messages there are plenty of bots out here that do the same

**Comment by jagrosh** [comment]
You can do this via the `eval` command now. A list of connected guilds is also on the [planned features list](https://github.com/jagrosh/MusicBot/projects/1)
