### ISSUE TITLE
[Feature Request] Invite the bot to your server Command

### ISSUE THREAD

**Issue by TheFatalKiller** [jagrosh/MusicBot#446]
**Is your feature request related to a problem? Please describe.**
No invite command

**Describe the solution you'd like**
A command that is for example [p]invite and it comes up with two links, one with the bots basic needed permissions and one with administrator privileges. 

**Describe the basic flow/steps of using this feature**
How this feature would be used:
To the help command put it below ping, about, settings 
The new help cmd would be. ping, about, invite, settings. 
The user runs the [p]invite command and it gives back the invite link with the bots name and the host of the bot. 

**Additional context**

**Have you confirmed that this idea is not already described here?**
https://github.com/jagrosh/MusicBot/projects/1

**Comment by jagrosh** [comment]
There is already a link provided in the `about` command if you've set your bot to public. Also, since unverified bots will be limited to 100 servers in the future, this doesn't seem like a useful feature to add.
