### ISSUE TITLE
[Bug Report] Command prompt issues

### ISSUE THREAD

**Issue by Adoven132** [jagrosh/MusicBot#453]
**Describe the bug**
When I run the jar file, with a config file present, through an editor like jGrasp it runs fine but when I run the jar file through the command prompt with "java -jar [file path]" it will not use the prefix i set in the config.txt and it is also only using the bot token of the original bot, i tried placing a new token in and it didn't use it. and does not recognize any serversetting.json files.
this is the exact thing i place in the command prompt "java -jar D:\MusicBot\JMusicBot-0.2.9.jar"

**Debug Info**
[debug_information.txt](https://github.com/jagrosh/MusicBot/files/4867436/debug_information.txt)

**Comment by Sanduhr32** [comment]
Try running the specific WIndows of it, if it makes a difference. Bare in mind that the files need to be in the same location where you run the command from.

**Comment by jagrosh** [comment]
The bot displays where it is looking for the config file when it starts up; you need to edit that file or set a specific one with `-Dconfig=/path/to/config.txt`
