### ISSUE TITLE
No search results found for any music

### ISSUE THREAD

**Issue by ThreeLineSolutions** [jagrosh/MusicBot#454]
No search results found for any music when I use the play command.

**Comment by iRealKsA** [comment]
Me too

**Comment by DJEnderblue** [comment]
I third this

**Comment by djsmithuk** [comment]
Updating the pom.xml file to use a newer version of larval-layer 1.3.50 then compile, worked for myself

**Comment by DJEnderblue** [comment]
> Updating the pom.xml file to use a newer version of lavaplayer 1.3.50 then compile, worked for myself

could you explain this? or give me the finished java file? I am not so tech experienced to do it myself

**Comment by Sanduhr32** [comment]
Building JMusicbot yourself is not supported. Always use the official releases on github.
This issue also is a duplicate of #443.

**Comment by jagrosh** [comment]
Duplicate of #443
