### ISSUE TITLE
[Bug Report] Alternate prefix and custom playlistsfolder triggers actions twice

### ISSUE THREAD

**Issue by MattElekHarris** [jagrosh/MusicBot#456]
**Describe the bug**
Using an alternate prefix seems to trigger certain actions twice. This issue only seems to occur when using a custom playlistsfolder path. Using the main prefix, it works as expected, however when using the alternate prefix it gives error upon interacting with playlists, but it still displays, loads, and interacts with playlists. It also seems to create two queues, and sometimes uses on or the other, and even overwrites the current one to start playing the other one. Everything works as expected when using the primary prefix, and on the second bot without the custom playlistsfolder, both prefixes work fine.

**To Reproduce**
1. Run with an alternate prefix, as well as a custom relative playlist path, in my case "../MusicBot/Playlists"
2. Interact with the bot using the alternate prefix

**Expected behavior**
The bot should work the same with or without an alternate prefix and custom relative playlist path, and shouldn't double trigger

**Screenshots**
![discord_issue](https://user-images.githubusercontent.com/27528960/86537439-96308200-bede-11ea-8181-866a9b406440.png)

**Debug Info**
```
System Properties:
  java.version = 11.0.7
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 11
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 11.0.7+10-post-Debian-3deb10u1
  java.specification.version = 11
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.2.10
  Owner = 277570933055815680
  Prefix = !!
  AltPrefix = minecraft
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 3.8.3_464
  JDA-Utilities Version = 2.1.5
  Lavaplayer Version = 1.3.50

Runtime Information:
  Total Memory = 102
  Used Memory = 44

Discord Information:
  ID = 669328621974061067
  Guilds = 1
  Users = 76
```

**Additional context**
I'm running two bots and using the same playlist folder for both of them. I can always just create a symlink, but i wanted to use the builtin functionality if I could

**Comment by jagrosh** [comment]
You're running both instances on the same bot; if you want to use two bots you need to use two different bot tokens.
