### ISSUE TITLE
[Feature Request] Autojoin. Auto join channel by ID in config, and begin playing playlists automatically.

### ISSUE THREAD

**Issue by ImmortalAmpharos** [jagrosh/MusicBot#458]
**Is your feature request related to a problem? Please describe.**
No

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. Set channel ID in config
2. Set playlists to automatically play
3. Bot will automatically join the channel at startup and begin playing playlists

**Have you confirmed that this idea is not already described here?**
https://github.com/jagrosh/MusicBot/projects/1
Yes.

**Comment by jagrosh** [comment]
This already exists; see the `autoplaylist` and `setvc` commands.
