### ISSUE TITLE
NullPointerException is being thrown while quering certain videos

### ISSUE THREAD

**Issue by 1337Steven1337** [jagrosh/MusicBot#459]
**Describe the bug**
The bot fails to load certain tracks

**To Reproduce**
Play i.e. ".play euphoric hardstyle mix 2020"

**Expected behavior**
It should play the first mix that pops up, it does work with direct links and other queries. But it appears to fail with certain queries.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/11975814/86623441-e8969f00-bfc1-11ea-8c0a-f3b5daaf0efb.png)

**Debug Info**
See screenshot

**Additional context**
This started happening after the update to 0.2.10.

**Comment by 1337Steven1337** [comment]
Seems to be related with lavaplayer, waiting for them to update.

**Comment by Sanduhr32** [comment]
A lavaplayer update still would require an update compiled by jagrosh.
Bugs on self compiled versions arent supported.
