### ISSUE TITLE
[Bug Report] Music bot sends an update message when it is already up-to-date.

### ISSUE THREAD

**Issue by AlexIsOK** [jagrosh/MusicBot#461]
**Describe the bug**
Music bot sends an update message when it is already up-to-date.

**To Reproduce**
Load the bot with the enable update notifications on.

**Expected behavior**
The bot does not send an update message since it is using the latest version.

**Screenshots**
[Screenshot](https://alexisok.dev/12ca71bae172bfdf1239.png)

**Debug Info**
`Linux ubuntu-srv 5.4.0-33-generic #37-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux`\
Ubuntu version 20.04 x64.  Everything else on the server is running smoothly.

**Additional context**
I tried using both the jars for both Linux and cross-platform.  I realise I can just turn it off but it might be an inconvenience for others.

**Comment by Sanduhr32** [comment]
Are you sure you have the 0.2.10 version?

**Comment by jagrosh** [comment]
Based on your screenshot, you're currently running version 0.2.9, but 0.2.10 is available, so you're not using the most up-to-date version.

**Comment by AlexIsOK** [comment]
@jagrosh I have updated, I downloaded the official JAR from the GitHub page on both the linked one and finding it myself.

**Comment by jagrosh** [comment]
You may have downloaded the new jar but you are still running the old one.

**Comment by AlexIsOK** [comment]
Not exactly sure why, but the old JAR was being used even after it was removed.  I had to shred the old file and remove it, then download and rename the new one.  Looks like that fixed it...
