### ISSUE TITLE
Twitch not working

### ISSUE THREAD

**Issue by GrieVeR-13** [jagrosh/MusicBot#464]
Playing stream from Twitch not working, 410 error responce (lavaplayer)

**Comment by sannoob** [comment]
Yes, It's Lavaplayer Issue, I think maybe twitch api is updated

[my lavaplayer twitch issue](https://github.com/sedmelluq/lavaplayer/issues/500)

**Comment by jagrosh** [comment]
Please use the bug report form and include debug info and logs when reporting an issue.
