### ISSUE TITLE
volume and youtube search doesnt work

### ISSUE THREAD

**Issue by Pele12324** [jagrosh/MusicBot#465]
**Describe the bug**
When i type =volume 90 or less the bot will just leave and when i try typing =play darude sandstorm, it wont find the song but when i paste the link then it will work.

**Comment by Sanduhr32** [comment]
1) You need to have 64bit java installed & selected as the default binary for java.
2) You have to use 0.2.10 for having a working YouTube search afaik

**Comment by jagrosh** [comment]
As stated, you are likely using an outdated version of the bot or an incorrect java version. Regardless, please use the bug report form with debug info in the future, as there isn't enough information in your description to find the cause of the problem.
