### ISSUE TITLE
[Bug Report] Unexpected downloaded content.

### ISSUE THREAD

**Issue by Zhai90** [jagrosh/MusicBot#466]
When I downloaded the music bot ver. 0.2.10, in the folder, wasn't those 3 things that should be in there, instead, this showed up: [
![image](https://user-images.githubusercontent.com/57015971/87595879-3fd0f980-c6bd-11ea-92b7-f75394f3559d.png) same happened with the version 0.2.9. This didn't happen when I first downloaded the file, in 2019.

**Comment by jagrosh** [comment]
Don't open the jar in winrar, open it with java.
