### ISSUE TITLE
[Bug Report] Play command not working

### ISSUE THREAD

**Issue by Neffenicous** [jagrosh/MusicBot#468]
**Describe the bug**
when using the !play command, the bot joins the channel, but fails to lookup the song

**To Reproduce**
1. !play <song name>

**Expected behavior**
Expecting it to play the song loaded from youtube like it used to

**Screenshots**
:no_entry_sign: Error loading track.

**Debug Info**
```
System Properties:
  java.version = 1.8.0_252
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 1.8.0_252-b09
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.2.10
  Owner = 230100425704079361
  Prefix = !
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 3.8.3_464
  JDA-Utilities Version = 2.1.5
  Lavaplayer Version = 1.3.50

Runtime Information:
  Total Memory = 93
  Used Memory = 35

Discord Information:
  ID = 728489664532447245
  Guilds = 1
  Users = 6
```

**Additional context**
Jul 18 18:01:37 jagrosh.madness startBot.sh[10962]: [18:01:37] [INFO] [JDA]: Finished Loading!
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]: [18:01:52] [ERROR] [DefaultAudioPlayerManager]: Error in loading item ytsearch:Motzart
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:237)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:226)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at java.lang.Thread.run(Thread.java:748)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]: Caused by: java.lang.RuntimeException: java.lang.NullPointerException
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:57)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:74)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:254)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:220)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:34)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:188)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:127)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         ... 6 common frames omitted
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]: Caused by: java.lang.NullPointerException: null
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.tools.DataFormatTools.durationTextToMillis(DataFormatTools.java:91)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.extractPolymerData(YoutubeSearchProvider.java:161)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.lambda$polymerExtractTracks$0(YoutubeSearchProvider.java:149)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at java.util.ArrayList.forEach(ArrayList.java:1257)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.polymerExtractTracks(YoutubeSearchProvider.java:148)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.extractSearchResults(YoutubeSearchProvider.java:94)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:71)
Jul 18 18:01:52 jagrosh.madness startBot.sh[10962]:         ... 14 common frames omitted

**Comment by TheFatalKiller** [comment]
Having same exact issue, on two bots.

**Comment by mythiccal** [comment]
same issue, fixes for a few minutes then returns.

**Comment by jagrosh** [comment]
Closing this as a newer version has been release, and if an issue similar to this still exists, it is likely a different issue.
