### ISSUE TITLE
[Feature Request]  Spotify Integration (Adding songs using Spotify Links)

### ISSUE THREAD

**Issue by PawelGamer** [jagrosh/MusicBot#471]
Hi,
I would like to request a very useful feature which is adding songs using Spotify links, using Spotify Developer app ID
![image](https://user-images.githubusercontent.com/34751988/88547787-7ba18280-d01e-11ea-8298-81f53aca7fde.png)
![image](https://user-images.githubusercontent.com/34751988/88547941-b2779880-d01e-11ea-9986-feb6954b743f.png)

It's very useful thing and it will make your bot even better
Regards,
PawelGamer

**Comment by Sanduhr32** [comment]
In the past spotify support was often suggested.
As you see yourself you need a client id and an application at the developers dashboard. This is not suitible as "easy setup" for most users.
The same applies for no YouTube client ID option / setting, which is the cause that many people get 429s from youtube.

**Comment by jagrosh** [comment]
Spotify support won't be added for a number of reasons:
- Spotify doesn't allow streaming for bots, so the audio couldn't come from Spotify anyway
- Looking up the songs in a Spotify playlist would require an additional API key
- Finding "matching" songs from a Spotify playlist via YouTube is very unreliable and is better done by hand anyway

**Comment by Claw256** [comment]
Hi, I understand that implementing a Spotify integration would not be possible, but what about a system that automatically converts Spotify playlists/links into YouTube links, just like how Groovy bot does it?

**Comment by jagrosh** [comment]
> Hi, I understand that implementing a Spotify integration would not be possible, but what about a system that automatically converts Spotify playlists/links into YouTube links, just like how Groovy bot does it?

This would still require a spotify api key, so it won't be added.

**Comment by Claw256** [comment]
> > Hi, I understand that implementing a Spotify integration would not be possible, but what about a system that automatically converts Spotify playlists/links into YouTube links, just like how Groovy bot does it?
> 
> This would still require a spotify api key, so it won't be added.

Ah ok, thanks anyway.
