### ISSUE TITLE
[Feature Request] DJ-only mode option

### ISSUE THREAD

**Issue by vico93** [jagrosh/MusicBot#474]
I wished there was an option to make basic commands (like play, stop) only available to DJs (similar to Rythm's `djonly` setting). I play to make a listen-only radio with a predefined playlist and i want to prevent other members to mess around with the tracklist.

Thanks in advance!

**Comment by jagrosh** [comment]
This can currently be achieved by using `settc`, pointing to a channel that nobody (or only admins) have access to.

**Comment by jagrosh** [comment]
Closing as the solution described above should work for most people. This also seems like a subset of #390
