### ISSUE TITLE
Bot fails to search for songs correctly

### ISSUE THREAD

**Issue by Sgtpanda** [jagrosh/MusicBot#48]
For some reason, I've just experienced an issue where the bot couldn't find any youtube song, but could after a restart, first time I've noticed this so not sure if it's a recurring issue or not. 

See below screenshot:

![discordcanary_2017-07-20_15-23-50](https://user-images.githubusercontent.com/4738742/28422370-b615d95e-6d5f-11e7-935c-2f27b9df36f0.png)

**Comment by jagrosh** [comment]
Are you using the latest version?

**Comment by jagrosh** [comment]
This appears to be the same issue as https://github.com/sedmelluq/lavaplayer/issues/45

**Comment by Sgtpanda** [comment]
Thanks, I was not using the latest version, was one version down, have sorted that out. I will comment on that issue if it happens again.

**Comment by Matthww** [comment]
Any news on this?

**Comment by Sgtpanda** [comment]
Apparently, https://github.com/sedmelluq/lavaplayer/pull/53 fixed it, so the dependencies just need updating I think.

**Comment by jagrosh** [comment]
The dependencies were updated for the latest release, so this should be fixed.

**Comment by jagrosh** [comment]
Feel free to re-open this issue if it is not fixed by newer releases.
