### ISSUE TITLE
[Bug Report] Can't play music on a Windows Server?

### ISSUE THREAD

**Issue by ForyxCraft** [jagrosh/MusicBot#487]
**Describe the bug**
The MusicBot can't play music when running on a Windows Server 2019

**To Reproduce**
1. Run bot on a Windows Server 2019 over RDP
2. try to play music

**Expected behavior**
The Bot should play music.

**Screenshots**
https://cdn.flawcra.cc/7/DATA/311002029854780568/311920610631921783/b4cdcb860279db1380.png
https://cdn.flawcra.cc/6/DATA/753180775456718769/221092032395666245/unknown.png

**Debug Info**
```
System Properties:
  java.version = 1.8.0_241
  java.vm.name = Java HotSpot(TM) Client VM
  java.vm.specification.version = 1.8
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 1.8.0_241-b07
  java.specification.version = 1.8
  os.arch = x86
  os.name = Windows Server 2019

JMusicBot Information:
  Version = 0.2.10
  Owner = 120916662001074176
  Prefix = fcm!
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = false

Dependency Information:
  JDA Version = 3.8.3_464
  JDA-Utilities Version = 2.1.5
  Lavaplayer Version = 1.3.50

Runtime Information:
  Total Memory = 23
  Used Memory = 18

Discord Information:
  ID = 736998145434583084
  Guilds = 5
  Users = 329
```

Here is the Console Output: [JMusicBot_WindowsServerLog.txt](https://github.com/jagrosh/MusicBot/files/5115030/JMusicBot_WindowsServerLog.txt)

**Comment by ForyxCraft** [comment]
Here is the Console Output: [JMusicBot_WindowsServerLog.txt](https://github.com/jagrosh/MusicBot/files/5115030/JMusicBot_WindowsServerLog.txt)

**Comment by jagrosh** [comment]
JMusicBot does not support 32-bit Windows, only 64-bit Windows. If your server is 64-bit, make sure to install 64-bit Java.
