### ISSUE TITLE
Playlist of local files fails to load

### ISSUE THREAD

**Issue by Terry-Kusunoki-Martin** [jagrosh/MusicBot#488]
**Describe the bug**
I tried creating a playlist of local files.  When I use the command to play the playlist, I am met with the error message "No tracks were loaded!" for all tracks. 

**To Reproduce**
1. Create playlist1.txt with local file paths
2. Run command '!play playlist1 '

**Expected behavior**
When entering the command to play these files individually, they play just fine.  The error only happens when collating all the !play commands into a .txt file and playing it as a playlist.  I made sure that the playlist txt is saved as UTF-8 as well.

**Debug Info**
System Properties:
  java.version = 13.0.2
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 13
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 13.0.2+8
  java.specification.version = 13
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.2.10
  Owner = 223665818058096640
  Prefix = !
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 3.8.3_464
  JDA-Utilities Version = 2.1.5
  Lavaplayer Version = 1.3.50

Runtime Information:
  Total Memory = 40
  Used Memory = 12

Discord Information:
  ID = 675648287134580746
  Guilds = 1
  Users = 7

**Comment by jagrosh** [comment]
Can you upload the playlist file? Also, keep in mind the syntax to play a playlist is `play playlist <name>`, so if you have a file `playlist1.txt`, the command would be `play playlist playlist1`

**Comment by Terry-Kusunoki-Martin** [comment]
Yes, I was entering the command correctly.  I receive a response from the bot in discord saying every track failed to load.  
Attached is the playlist file. [playlist.txt](https://github.com/jagrosh/MusicBot/files/5129988/playlist.txt)

**Comment by jagrosh** [comment]
All of the lines of this playlist start with `!play`; they should just be the path of the track (as per the example playlist)
