### ISSUE TITLE
600 song limit

### ISSUE THREAD

**Issue by oyath** [jagrosh/MusicBot#49]
Is this a hard limit on the bot or something, my autoplaylist only pulls from the first 600 of a youtube playlist i've created and any time i queue the playlist it only adds the first 600 songs. Any way to get this increased? Also searching for songs doesn't work it seems

**Comment by jagrosh** [comment]
The 600 limit is enforced by an underlying library; I think I can remove that. As for searching, that's a known bug with the underlying library and I can't do anything to fix it until the library has a solution; in the meantime you can just restart the bot and the searching issue should go away.

**Comment by Definitemars** [comment]
Hi there, 

Just updated my bot to 0.4.0 today and i'm finding that it caps out at 560 songs on youtube playlists. Have there been any fixes since the above question? Thank you.

**Comment by Juustar** [comment]
> Hi there,
> 
> Just updated my bot to 0.4.0 today and i'm finding that it caps out at 560 songs on youtube playlists. Have there been any fixes since the above question? Thank you.

having the same issue here. had several youtube playlists at exactly 999 songs to avoid going over the old limit, but now i cant load the entire playlist. would prefer to find a fix than have to remake all my playlists

**Comment by jagrosh** [comment]
We switched to a different fork of lavaplayer for this update; I'll investigate what may have changed and see if I can resolve it for 0.4.1

**Comment by jagrosh** [comment]
Until then (or just for anyone wanting to make extremely-large playlists), you could make multiple youtube playlists and put them in a local playlist file.

**Comment by jagrosh** [comment]
Will be a settable value in 0.4.1
