### ISSUE TITLE
[Bug Report] Title Here

### ISSUE THREAD

**Issue by ItzAbra** [jagrosh/MusicBot#490]
how can i do to put my bot 24/7 online?

**Expected behavior**

**Screenshots**

**Debug Info**
Please run the `debug` command and paste it here or upload it as an attachment. If you cannot run the command, please provide information about your system such as operating system version, JMusicBot version, etc.

**Additional context**

**Comment by jagrosh** [comment]
Please see [this page on the wiki](https://github.com/jagrosh/MusicBot/wiki/24-7-Hosting) for hosting options

**Comment by Sanduhr32** [comment]
https://github.com/jagrosh/MusicBot/wiki/24-7-Hosting
