### ISSUE TITLE
Editing  language

### ISSUE THREAD

**Issue by quadews** [jagrosh/MusicBot#491]
how can i edit bot language 

etc:
Added Billie Eilish, Khalid - lovely (03:21) to begin playing
to
Oynatılıyor Billie Eilish, Khalid - lovely (03:21) başlayacak 
thanks..

**Comment by Sanduhr32** [comment]
Changing the language is a planned feature. It's currently impossible to change the language.

**Comment by jagrosh** [comment]
This is already on the planned features list
