### ISSUE TITLE
[Bug Report] Failed to load track: Band information not found on the Bandcamp 

### ISSUE THREAD

**Issue by Speak2Erase** [jagrosh/MusicBot#493]
**Describe the bug**
The bot can't play songs from bandcamp anymore. 

**To Reproduce**
Run a command trying to play any bandcamp song or soundtrack
**Expected behavior**
Bot just plays the music.

**Screenshots**
https://i.imgur.com/IfyMLt8.png

**Debug Info**
```
System Properties:
  java.version = 1.8.0_261
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 1.8.0_261-b12
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.2.10
  Owner = 351871502460649485
  Prefix = ^
  AltPrefix = *
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 3.8.3_464
  JDA-Utilities Version = 2.1.5
  Lavaplayer Version = 1.3.50

Runtime Information:
  Total Memory = 196
  Used Memory = 40

Discord Information:
  ID = 713069493475344414
  Guilds = 3
  Users = 246
```
**Additional context**
This is a recent problem that just started today.

This happens on other bots as well.

**Comment by redbrain** [comment]
I'm having this issue too, on Moosic bot. Each bot utilises Lavaplayer for getting audio so it could be upstream.

**Comment by redbrain** [comment]
It appears to be a known issue with lavaplayer after the newest update to Bandcamp: https://github.com/sedmelluq/lavaplayer/pull/518

**Comment by MichailiK** [comment]
The upstream issue has been closed last year. Playing Bandcamp music is working as of writing.
