### ISSUE TITLE
[Feature Request] Add a config option to allow the bot to accept commands from other bots.

### ISSUE THREAD

**Issue by FOGC123** [jagrosh/MusicBot#496]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. Set something '...'
2. Run some command '...'
3. Other steps or related info '...'
4. ...

**Additional context**

**Have you confirmed that this idea is not already described here?**
https://github.com/jagrosh/MusicBot/projects/1

**Comment by jagrosh** [comment]
This won't be added, as it is generally bad practice for a bot to listen to other bots, and usually there is some other underlying reason why this would be wanted (and thus it would be better to just make that improvement instead of layering bots).
