### ISSUE TITLE
Add a clear command

### ISSUE THREAD

**Issue by Weischbier** [jagrosh/MusicBot#5]
If a playlists is queued up but there's a need to clear it there's only the option to remove one by one with the remove command. Kind of tedious and exhausting work.

**Comment by jagrosh** [comment]
Anyone who has the specified "DJ" role can use the `skipto` command to skip forward multiple songs in the queue, or the `stop` command to completely clear it. I'll put a command to remove all of a user's own songs on the suggested features list and consider it (or how to achieve a similar result).

**Comment by Weischbier** [comment]
Ahhh okay, thanks for that explanation.

**Comment by jagrosh** [comment]
As of release 0.0.3, users can now `remove all` to remove all songs that they added
DJs can as always still use skipto and/or stop to remove parts or clear the queue entirely
