### ISSUE TITLE
[Feature Request] Configurable Timeout Timer

### ISSUE THREAD

**Issue by Ynd21** [jagrosh/MusicBot#502]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to set a configurable time in the txt file that allows me to time the bot out of a voice channel if that time limit has been reached. This would allow bot operators to save bandwidth costs on hosts, not have the bot idling/staying in the channel all the time, and discord users not having the bot join/leave every time a song completes but someone forgot to add a new song to the playlist. 

**Describe the solution you'd like**
Inside the config file set a time value that will disconnect the bot from the voice channel if nothing has been playing for X minutes/queue has been empty for X minutes

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. Set a time value in your config txt file
2. Users add 3-4 songs to queue 
3. After X time idle/no playlist, bot disconnects from voice chat automatically 

**Additional context**
I know the option to keep the bot in the channel exists and -stop will disconnect it, however I believe setting a timeout value would be beneficial as 

**Have you confirmed that this idea is not already described here?**
Yes

**Comment by jagrosh** [comment]
This is already on the planned feature list
