### ISSUE TITLE
[Issue] When I run the jar file, it makes config.txt in the windows folders.

### ISSUE THREAD

**Issue by Dragonizedpizza** [jagrosh/MusicBot#507]
When I run the jar file, it makes config.txt in the windows folders. It made one in System32 and C:\Windows . I'm not sure how to host this on Heroku either.

**Comment by jagrosh** [comment]
You can set the config file location by running the jar directly (double-clicking) instead of Open With.
Hosting on Heroku is not supported.

**Comment by Dragonizedpizza** [comment]
> You can set the config file location by running the jar directly (double-clicking) instead of Open With.
> Hosting on Heroku is not supported.

Is there any other way of hosting other than on my PC? @jagrosh

**Comment by Dragonizedpizza** [comment]
Also, can I give the bot a streaming status?
