### ISSUE TITLE
[Issue] Can I automate the hosting? Like use websites like repl.it or something.

### ISSUE THREAD

**Issue by Dragonizedpizza** [jagrosh/MusicBot#508]
Can I automate the hosting? I want to host it on websites like repl.it or or glitch. 
Also, is there any way I can make the status to a streaming status?

**Comment by Proxymiity** [comment]
You can already set a streaming status using `setgame streaming <twitch username> <game/stream name>`.
What do you mean by 'hosting'? You can host the bot on nearly any hosting provider

**Comment by Sanduhr32** [comment]
@Proxymiity they probably meant how to host the bot (without paying a price).

**Comment by Proxymiity** [comment]
Well as long as the hosting provider can run Java on the machine it should be okay?

**Comment by Dragonizedpizza** [comment]
@Proxymiity @Sanduhr32 any examples?

**Comment by Proxymiity** [comment]
You could try using DevOps on Heroku for example, but I don't know if this will work.

**Comment by jagrosh** [comment]
"Free" hosting is either not actually free, or doesn't provide sufficient permissions or resource availability to run JMusicBot.
