### ISSUE TITLE
Bot thinks no music is playing when it plays

### ISSUE THREAD

**Issue by TheIndra55** [jagrosh/MusicBot#51]
I came across this bug after playing a livestream for 7 hours

```
TheIndra - today at 11:42
.play http://vip-icecast.538.lw.triple-it.nl/WEB02_MP3

GehoorStreler2000 [BOT] - today at 11:42
:notes: Added Unknown title (LIVE) to begin playing(gewijzigd)
```

After 7 hours someone else tried the queue command and it showed 
`:no_entry_sign: There must be music playing to use that!`
But there was still music playing...

Also we tried play a new song, it added to the queue but when using
.queue it still showed that there was no music playing

Also skip doesn't work because the bot thinks there is no music playing

**Config**
```

token=6mBm1TmGVk.DncD8KRG7SDmg4uThahanorandomlettergenerator9smq026nTB

owner=241225897389064192

prefix=.

game=Skype installer

//success=🎶
//warning=💡
//error=🚫

//help=cmds

noprogressintopic=true
```

Device: Raspberry PI
OS: Raspbian

**Comment by TheIndra55** [comment]
**Update:**
Today i suddenly saw the bot was stopped playing music, When playing a new song and trying .queue it still said it was not playing music 

When trying the bot in another server it works fine

**Comment by isteria** [comment]
It happens quite often to me when a playlist with multiple songs is queued or a stream radio is played. The bot stops responding to commands so the only option is to shut it down and restart. A !restart command would be a nice option since the owner is not always available to restart the bot by shutting it down.

**Comment by Tankernn** [comment]
I have the same issue. Though, since I use systemd to manage the bot process I just set it to always automatically restart on shutdown. This means that `!shutdown` restarts the bot.

**Comment by jagrosh** [comment]
A `restart` command isn't really possible because the JVM needs to exit. Just run the bot in a loop script (or manage the process like @Tankernn does) and use `shutdown` to restart the bot.

Also, can you confirm that this is still happening on the latest version (0.0.9)?

**Comment by Tankernn** [comment]
Oh, sorry. I didn't see the new release. I'm still running 0.0.8, will update now. Thanks!

**Comment by jagrosh** [comment]
Feel free to re-open this if it still occurs in newer releases, although it should be fixed.
