### ISSUE TITLE
[Bug Report] The files shown in setup are not there in the .zip

### ISSUE THREAD

**Issue by XtremeUdayan** [jagrosh/MusicBot#513]
**Describe the bug**

**To Reproduce**
1. Run with '...'
2. Do a command '....'
3. Some other step '....'

**Expected behavior**

**Screenshots**

**Debug Info**
Please run the `debug` command and paste it here or upload it as an attachment. If you cannot run the command, please provide information about your system such as operating system version, JMusicBot version, etc.

**Additional context**

**Comment by jagrosh** [comment]
As the releases page says, don't download the zip file, you need to download the prebuilt jar.
