### ISSUE TITLE
[Bug Report] Can't change anything about the bot

### ISSUE THREAD

**Issue by Redd6606** [jagrosh/MusicBot#518]
Whenever I go into notepad or notepad++ and change something, it doesn't work. For example I try to change the alias of play, it doesn't work

**Comment by MichailiK** [comment]
There are several reasons why changing the config may not work & I believe it's better that we track down the cause on Discord.
Could you come to [jagrosh's server](https://discord.gg/0p9LSGoRLu6Pet0k) and ping me in the #support channel? (Michaili#0406)

**Comment by jagrosh** [comment]
This sounds like a configuration issue, not a bug. Try deleting your config file and then editing the one that the bot generates at startup (it tells you where it creates it).
