### ISSUE TITLE
[Feature Request] Deafen itself

### ISSUE THREAD

**Issue by kubo6472** [jagrosh/MusicBot#519]
**Is your feature request related to a problem? Please describe.**
Bandwidth saving

**Describe the solution you'd like**
Adding config option to deafen itself.
e.g. https://groovy.zendesk.com/hc/en-us/articles/360042923932-Why-does-Groovy-deafen-itself-

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. boolean config option: deafen_itself=true/false
2. bot would deafen itself to save bandwidth
3. default to true

**Additional context**
Config option

**Have you confirmed that this idea is not already described here?**
- [x] https://github.com/jagrosh/MusicBot/projects/1

**Comment by jagrosh** [comment]
Unless Discord's API has changed recently, that article is not accurate and deafening is performed clientside, so there is no change in bandwidth (bots "deafening" is purely a visual change).

**Comment by kubo6472** [comment]
Afaik at least the server deafening voice state can be performed by the bot itself. Tried looking, but haven't found anything to back their claims, so I asked...

**Comment by jagrosh** [comment]
If they or anyone else can share documentation provided by Discord that this is the case, I'd be happy to reopen this issue.

**Comment by kubo6472** [comment]
Deal! Thank you for your time at least :)

**Comment by kubo6472** [comment]
I asked the discord support

> Hi, please, I'd like some "official" or direct statement, that this musicbot server deafening itself does actually have any effect on the bandwidth it uses: https://groovy.zendesk.com/hc/en-us/articles/360042923932-Why-does-Groovy-deafen-itself-

Official response from their engineering team:

> Hello,
> 
>  thank you for your patience.
> 
>  To answer your question: Yes, it has an impact and helps us save bandwidth in voice channels.
> 
>  Unfortunately, we cannot provide you with any more information.  But please let us know if you have any further questions about the app!  :)

**Comment by Ignaciox** [comment]
can +1 this. It actually does save bandwidth  @jagrosh
