### ISSUE TITLE
Allow Spotify Links (Not With Spotify Integration)

### ISSUE THREAD

**Issue by doublehelix457** [jagrosh/MusicBot#524]
Hello,

Ive seen many requests on spotify integration and I'm aware that it isnt feasible. However, I request that spotify playlist links be converted to youtube links and then played automatically. Would be super handy

**Comment by jagrosh** [comment]
That would still require a Spotify API key (to read the playlist), so it won't be added.

**Comment by kwu23** [comment]
Hi John, could this be added as a feature where the user can optionally add their own Spotify key to the config file?
