### ISSUE TITLE
how to make the bot pick up local media

### ISSUE THREAD

**Issue by Jokermama** [jagrosh/MusicBot#526]
I'm completely clueless as to how i make the pick up local media i tried a few things but nothing is working it not mentioned either how to make it pick local music please someone help :P

**Comment by jagrosh** [comment]
Local media can be played via either full or relative path (ie `play /folder/path/to/song.mp3`)

**Comment by Jokermama** [comment]
for anyone with the same issue
1. Create a playlist with command
A new text file will appear
2. Select all music file right click and copy path(s)
3. direct paste those in the text file that auto-generated
woala now run the play playlist command
