### ISSUE TITLE
[Bug Report] Broken bot when over 100 servers

### ISSUE THREAD

**Issue by Proxymiity** [jagrosh/MusicBot#529]
**Describe the bug**
When passing 100 servers, the bot won't start and will be stuck in "Loading", even if the bot is verified.

**To Reproduce**
1. Add the verified bot to 100 or more servers
2. Start or restart the bot
3. The bot is stuck in the "Loading..." state

**Expected behavior**
The bot should login correctly or at least throw an error in the console.

**Screenshots**
//about command:
![image](https://i.iya.at/chrome_8LhCm5.png)
console output:
![image](https://i.iya.at/Termius_fRDMrY.png)

**Debug Info**
<details>
  <summary>Debug info</summary>

```
System Properties:
  java.version = 1.8.0_272
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 1.8.0_272-8u272-b10-0+deb9u1-b10
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.2.10
  Owner = 278230133176008704
  Prefix = //
  AltPrefix = ..
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = false

Dependency Information:
  JDA Version = 3.8.3_464
  JDA-Utilities Version = 2.1.5
  Lavaplayer Version = 1.3.50

Runtime Information:
  Total Memory = 143
  Used Memory = 38

Discord Information:
  ID = 512030715332919348
  Guilds = 0
  Users = 1
```

</details>

**Additional context**
The bot only reply to commands used in DM by the owner itself, and shows 0 text channels, voice channels, servers, users...

**Comment by jagrosh** [comment]
2 things:
1. JMusicBot does not support running on verified bots, as verification should only be for bots you've written and thoroughly understand
2. All versions of JMusicBot are currently broken; the only solution is to wait until the next version is release, 0.3.1
