### ISSUE TITLE
[Feature Request] Loop playlist over and over again

### ISSUE THREAD

**Issue by Comstepr** [jagrosh/MusicBot#535]
**Is your feature request related to a problem? Please describe.**
Loop playlist over and over again

**Describe the solution you'd like**
Loop playlist over and over again (tunes!loop)

**Describe the basic flow/steps of using this feature**
Type tunes!loop and loop a playlist over and over again

**Additional context**

**Have you confirmed that this idea is not already described here?**
Yes

**Comment by Comstepr** [comment]
Sorry, I don't think I'm doing this right? I think this is implemented. How do I do it?

**Comment by revali2008** [comment]
Ask this in his discord server using the suggestion command.

**Comment by jagrosh** [comment]
You can either:
1. Queue up a playlist, and then enable repeat mode, or
2. Set an autoplaylist
