### ISSUE TITLE
Bot online

### ISSUE THREAD

**Issue by Redd6606** [jagrosh/MusicBot#537]
Is there any way I can keep the bot offline? Because if I shut down my Laptop/PC then it will automaticly go offline

**Comment by MichailiK** [comment]
You clearly have a big misunderstanding of how bots work.

Imagine it like this: A bot is like an invisible, automatic Discord window. If you close Discord, you go offline, right? That's the same for bots, so you need some computer to keep this invisible Discord window running.

Check out the Wiki page for [24/7 Hosting](https://github.com/jagrosh/MusicBot/wiki/24-7-Hosting)
