### ISSUE TITLE
[Suggestion] Add an option to disable now playing in channel topic altogether

### ISSUE THREAD

**Issue by TheRandomMelon** [jagrosh/MusicBot#54]
Hi,
I manage bots in my friend's Discord server.

I'd like to suggest that we add an option (in config.txt) to allow the option to disable Now Playing in the channel topic altogether. 

I'm sure a lot of people would like this option as well.

**Comment by jagrosh** [comment]
Just don't give it the Manage Channel permission in that channel

**Comment by TheRandomMelon** [comment]
ok thanks!
