### ISSUE TITLE
[Bug Report] Java Error

### ISSUE THREAD

**Issue by apererecadavizinhatasentadanaminhavara** [jagrosh/MusicBot#541]
![image](https://user-images.githubusercontent.com/73714431/97739212-4cd3f600-1abe-11eb-83b0-6cb2e1c34b2d.png)

![image](https://user-images.githubusercontent.com/73714431/97739232-58272180-1abe-11eb-8860-ccd8228e971c.png)

I was creating a bot, I configured everything just right and this error appears, I'm already using the most updated version that has 64 bit of Java, and continues with this error, since the big text box, I don't know how to explain

if you can help me i appreciate

**Comment by jagrosh** [comment]
First, you need to enclose anything with an exclamation point in double quotes, for example, `prefix = "!"`
Also, make sure you're actually running the bot with 64 bit java, it appears that you are not.
