### ISSUE TITLE
[Bug Report] LavaPlayer: Something broke when playing the track.

### ISSUE THREAD

**Issue by kubo6472** [jagrosh/MusicBot#542]
**Describe the bug**
Lavaplayer error

**To Reproduce**
Play a track

**Expected behavior**
Play the track

**Debug Info**
LOGS: https://hastebin.com/apeneyafaw.less

**Comment by mooseh** [comment]
Same issue for me too

**Comment by jagrosh** [comment]
Duplicate of #531
