### ISSUE TITLE
[Feature Request] add mixcloud

### ISSUE THREAD

**Issue by koreyexpress2** [jagrosh/MusicBot#544]
**Is your feature request related to a problem? Please describe.**
Yes it’s wont sense mixcloud links

A clear and concise description of what the problem is

Mixcloud was not adding in the source code and my friend was frustrated that he wanted to play a Pacific song and it’s tell error format or unknown url 

**Describe the solution you'd like**

I will like it to be add to the bot and no lagging

**Comment by jagrosh** [comment]
This would be a feature request for [lavaplayer](https://github.com/sedmelluq/lavaplayer), as that is what handles loading audio from external sources.
