### ISSUE TITLE
[Bug Report] whats wrong?

### ISSUE THREAD

**Issue by GenjiWang** [jagrosh/MusicBot#545]
how i deal
<img width="718" alt="擷取" src="https://user-images.githubusercontent.com/69521150/97794293-dc9ab100-1c32-11eb-8fb1-fe0de0cff23e.PNG">

**Comment by docentYT** [comment]
I have the same issue.

**Comment by MichailiK** [comment]
Duplicate of #531

**Comment by GenjiWang** [comment]
so how i solve t

docentYT <notifications@github.com> 於 2020年11月2日 週一 上午2:12寫道：

**Comment by GenjiWang** [comment]
so how i solve this problem?


docentYT <notifications@github.com> 於 2020年11月2日 週一 上午2:12寫道：

**Comment by Sanduhr32** [comment]
Wait for the next release 0.3.2!
