### ISSUE TITLE
Issue with Raspbian 32 bits

### ISSUE THREAD

**Issue by aedbrault** [jagrosh/MusicBot#557]
Hi since the last update 0.3.1 , i can't start anymore the bot , it's host on raspbian on raspberry 4b 4 Go ( 32 bits ), 
here is the error : "it appears that you may not be using a supported java version. please use 64 bit"
any tips ?

**Comment by MichailiK** [comment]
You must upgrade to a 64-bit Raspberry Pi, Operating System & Java to use the MusicBot properly. 32-bit systems are **not** supported.

**Comment by aedbrault** [comment]
But with old version it was possible , why create a version only for 64 now ?

**Comment by MichailiK** [comment]
[32-bit installations have always been poorly supported](https://github.com/jagrosh/MusicBot/issues/300#issuecomment-544161127). Things have changed behind the scenes that made it worse & worse to use MusicBot for 32-bit systems. Please try installing a 64-bit Raspbian OS & a 64-bit Java installation.

**Comment by jagrosh** [comment]
> But with old version it was possible , why create a version only for 64 now ?
**The latest change only adds a warning**, it doesn't fully prevent you from starting the bot. However, it has always been the case that certain features will simply not work on 32-bit systems; this has not changed.

Also, in the future, please use the template.
