### ISSUE TITLE
[Bug Report] When volume is turned up the bot is muffled

### ISSUE THREAD

**Issue by PraiseLag** [jagrosh/MusicBot#559]
**Describe the bug**
I was listening to music on the bot after the new 0.3.2 update and I turned the volume up and noticed that it sounds muffled when I did that.

**To Reproduce**
1. Be on the new 0.3.2 version
2. play music then turn the volume up until you notice it's muffled a bit

**Expected behavior**
I expected the music that I was playing to be louder and still clear like it was before I turned the volume up.

**Screenshots**
Can't really add a screenshot of this happening

**Debug Info**
```
System Properties:
  java.version = 14.0.1
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 14
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 14.0.1+7-Ubuntu-1ubuntu1
  java.specification.version = 14
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.3.2
  Owner = 447905731232923649
  Prefix = -
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = true
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.2.0_214
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.55

Runtime Information:
  Total Memory = 36
  Used Memory = 19

Discord Information:
  ID = 756627368533295254
  Guilds = 2
  Users = 4
```
**Additional context**
I am running the bot on a VPS and not in the back of my computer so I don't think this is the problem but I'm not sure.

**Comment by jagrosh** [comment]
Turning the volume above 100 means increasing gain, which could very easily be capping out (depending on the original volume of the song). This is not something that can be fixed, as it's just how audio gain manipulation works. I would not recommend setting the volume above 100, but instead try turning up your Discord or computer volume.

Also, setting the volume to anything besides 100 means that the audio stream has to be decoded and re-encoded. If you also notice muffling when setting the volume to 90, then it likely means your processor is not powerful enough to decode and re-encode quickly enough.

I'm going to close this issue, as I believe that it's one of the two scenarios described above. This can be reopened if there is evidence that this isn't one of the described scenarios.
