### ISSUE TITLE
serversettings.json is missing

### ISSUE THREAD

**Issue by oharamedia** [jagrosh/MusicBot#56]
Hey, i get a error for serversetting.json

[13:21:22] [Warning] [Settings]: Failed to load server settings: java.nio.file.NoSuchFileException: serversettings.json

:(

**Comment by Matthww** [comment]
your bot probably doesn't have write access. the serversettings.json gets made automatic.

**Comment by oharamedia** [comment]
Okay, will retry later when home again

**Comment by jagrosh** [comment]
That is not an error, it's a warning. The file wont exist if you haven't set any settings for any servers yet.
