### ISSUE TITLE
[Bug Report] Lyrics are never found

### ISSUE THREAD

**Issue by nickhodl** [jagrosh/MusicBot#560]
**Describe the bug**
No matter what provider I choose for lyrics, no lyrics are ever found. Always ":no_entry_sign: Lyrics for ... could not be found!"

**To Reproduce**
1. Choose A-Z Lyrics as default
2. Search for "Foo Fighters Shame Shame" (https://www.azlyrics.com/lyrics/foofighters/shameshame.html)
3. Observe no lyrics found

**Expected behavior**
For lyrics to appear

**Debug Info**
Please run the `debug` command and paste it here or upload it as an attachment. If you cannot run the command, please provide information about your system such as operating system version, JMusicBot version, etc.

[debug_information.txt](https://github.com/jagrosh/MusicBot/files/5522997/debug_information.txt)

**Comment by MichailiK** [comment]
I can't reproduce this. Have you checked if the PC/server you're hosting the bot on is able to access https://azlyrics.com without errors?
![image](https://user-images.githubusercontent.com/39029839/99547602-033d4380-29b8-11eb-92af-c29287df132d.png)

**Comment by jagrosh** [comment]
This is likely a problem with your hosting, it may be blocked by your chosen lyrics provider, or you have changed the lyrics settings.
