### ISSUE TITLE
[Bug Report] Title Here

### ISSUE THREAD

**Issue by LiGeten** [jagrosh/MusicBot#566]
**Describe the bug**
The bot stopped working today
when the playlist starts, the answer is silence

**To Reproduce**
1.I go to the text channel
2.I enter the command
3.bot does not play

**Screenshots**
https://skr.sh/s5NdzGsFnLh?a

**Debug Info**
[debug_information (1).txt](https://github.com/jagrosh/MusicBot/files/5612824/debug_information.1.txt)

**Additional context**
when restarting, incomprehensible errors with the token, but then successfully logs in
[log.log](https://github.com/jagrosh/MusicBot/files/5612823/log.log)

**Comment by jagrosh** [comment]
You are using version 0.2.7, which is severely outdated. Please use the [latest release](https://github.com/jagrosh/MusicBot/releases/latest).
