### ISSUE TITLE
[Feature Request] play local files with play command

### ISSUE THREAD

**Issue by spacedouche** [jagrosh/MusicBot#571]
**Is your feature request related to a problem? Please describe.**
Just to take advantage of local files more, https://github.com/jagrosh/MusicBot/issues/156

**Describe the solution you'd like**
Bot owner can be able to set a local folder to the songs library, then playing songs from there without a playlist. Maybe it can search the local folder for titles before searching Youtube.

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. local set <folder> 
2. play <title> / play local <title>
3. bot searches the local folder first if it is set

**Additional context**
Could make it easier to create local playlists or the local playlist solution can have this feature.

**Have you confirmed that this idea is not already described here?**
https://github.com/jagrosh/MusicBot/projects/1
It can be tacked on as an additional feature to https://github.com/jagrosh/MusicBot/issues/156

**Comment by jagrosh** [comment]
You can already play local files with the `play` command, ie `play path/to/file.mp3`

**Comment by AdrX003** [comment]
> 

unfortunately when i try this, most of the time the bot executes a search for a online result and plays the latter.
