### ISSUE TITLE
[low priority] Example config missing LyricsFreak in comment

### ISSUE THREAD

**Issue by redbrain** [jagrosh/MusicBot#580]
JMusicBot appears to run on JLyrics v0.4, which supports LyricsFreak as a source.
However, the [example config](https://github.com/jagrosh/MusicBot/wiki/Example-Config) fails to mention it as a possible default source.
I can't figure out how to submit a PR to the wiki section, so I'm submitting an issue to let you know, if it needs to be changed

**Comment by jagrosh** [comment]
Resolved as of the latest release
