### ISSUE TITLE
[Bug Report] Sharding error

### ISSUE THREAD

**Issue by kimjunsung04** [jagrosh/MusicBot#584]
**Describe the bug**
You cannot use the music bot in a bot that requires shading.
The program will terminate immediately upon attempting to use it.

**To Reproduce**
1. Run the program.
2. The program stops immediately.

**Expected behavior**
You can also use the musicbot function in larger bots.

**Screenshots**
The show turns off too quickly and cannot be filmed.

**Debug Info**
Please run the `debug` command and paste it here or upload it as an attachment. If you cannot run the command, please provide information about your system such as operating system version, JMusicBot version, etc.

**Additional context**
Replace this text with any other context about the problem.

**Comment by jagrosh** [comment]
JMusicBot does not support sharding, as it is not intended to be used as a public bot.
