### ISSUE TITLE
[Bug Report] Bot Not Working Correctly 

### ISSUE THREAD

**Issue by koreyexpress2** [jagrosh/MusicBot#586]
**Describe the bug**

Bot keeps on shutting down even i reset everything even reinstalling everything and updated everything

**To Reproduce**
1. Reset
2. Updated
3. Reinstalling 

**Expected behavior**

Keep on doing everything 

**Screenshots**
If applicable, add screenshots to help explain your problem here.
dont have a camera 

**Debug Info**
Please run the `debug` command and paste it here or upload it as an attachment. If you cannot run the command, please provide information about your system such as operating system version, JMusicBot version, etc.

i have window 10 and everything is updated

**Additional context**

Most of the time when the bot is playing music its always skipping

**Comment by jagrosh** [comment]
Closing as there isn't enough information to tell what is happening. Please provide a more-detailed description of what is going wrong, along with screenshots and the output of the debug command.
