### ISSUE TITLE
[Bug Report] Can not read playlist folder not write to playlist folder

### ISSUE THREAD

**Issue by tigartar** [jagrosh/MusicBot#588]
**Describe the bug**
When trying to set autoplaylist to songs.txt the following error is given "Could not find songs.txt" 
When trying to create playlist the following error is given "I was unable to create the playlist: Playlists\songs.txt"

**To Reproduce**
1. try to run any of the playlist commands for example playlist make songs

**Expected behavior**
That it would read/create said text files

**Screenshots**

**Debug Info**
```
System Properties:
  java.version = 1.8.0_191
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 1.8
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 1.8.0_191-b12
  java.specification.version = 1.8
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.3.2
  Owner = 185748289596030976
  Prefix = @mention
  AltPrefix = null
  MaxSeconds = 0
  NPImages = false
  SongInStatus = true
  StayInChannel = true
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.2.0_214
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.55

Runtime Information:
  Total Memory = 288
  Used Memory = 58

Discord Information:
  ID = 800147730227265546
  Guilds = 1
  Users = 3
```

**Additional context**

The bot runs from the C drive one folder deep it can read and write to config and such fine but it will not read or write to playlist folder

**Comment by Kreisverkehr** [comment]
I just looked into the code. It seems that the bot does not create the playlist folder if it does not exist. Have you tried creating the playlist folder manually? Mine just works finde, but I have reconfigured the playlist folder and created it myself.

**Comment by jagrosh** [comment]
> I just looked into the code. It seems that the bot does not create the playlist folder if it does not exist. Have you tried creating the playlist folder manually? Mine just works finde, but I have reconfigured the playlist folder and created it myself.

The bot does attempt to create the folder if it doesn't exist, as seen [here](https://github.com/jagrosh/MusicBot/blob/master/src/main/java/com/jagrosh/jmusicbot/playlist/PlaylistLoader.java#L119). This entire issue is probably because you are running the bot from a location that doesn't have folder permissions. Make sure to run it from a child of your "Documents" or similar folder, not from a root drive.
