### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by pedroricardo** [jagrosh/MusicBot#59]
After a while and with many servers using the bot, a bug appears in the command queue not showing the songs that will be played next.
Conceivably the bug also affects the ability to add new songs to the queue, stopping and exiting the call or jumping immediately to the new music added

**Comment by jagrosh** [comment]
Do you know of a reliable way to reproduce this?

**Comment by pedroricardo** [comment]
Add an autoplaylist that is a live youtube link.
After a while add songs to the playlist expect them to end and fall into the autoplaylist. After a while the autoplaylist is playing, ask some people to add several songs and use the QUEUE command!

I believe that if the bot spent a lot of time playing the autoplaylist it will be easier the bug appears!

But when I reboot the bot this bug disappears after a while!

**Comment by newbs0001** [comment]
Yeah I have the same problem. When using `!play <song>` with a standard playlist enabled will just make the bot say `:watch: Loading... [Song]` without it adding it to the queue.

**Comment by pedroricardo** [comment]
if the auto playlist function is enabled and playing, the Queue command does not work properly if you try to add a YouTube playlist

**Comment by pedroricardo** [comment]
![image](https://user-images.githubusercontent.com/25847896/29986430-afd4b69a-8f39-11e7-9970-caa497f26ebc.png)

**Comment by isteria** [comment]
indeed same happens to me with long playlists or radio streams

**Comment by pedroricardo** [comment]
this bug was resolved in version 0.0.9
but it seems that the bot is stopped while playing a live link I give youtube!

**Comment by jagrosh** [comment]
Can you check if this is resolved as of 0.1.1
