### ISSUE TITLE
[Bug Report] Not starting

### ISSUE THREAD

**Issue by Coolykoen** [jagrosh/MusicBot#599]
**Describe the bug**
The bot worked the first time, but every attempt afterwards it did not completely load.
To be more precise, i started the bot in debian 10 (in docker container) with this command:
`nohup java -Dnogui=true -jar /mb/JMusicBot.jar`
This worked the first time.
But after that, giving it the exact same command it starts loading, but hangs with 0% cpu usage and about 70mb of ram usage.

**To Reproduce**
1. download docker image debian version 10
2. `apt update;apt install default-jre -y`
3. `nohup java -Dnogui=true -jar /mb/JMusicBot.jar`

**Expected behavior**
The bot should start every time you enter the command from step 3.

**Screenshots**
![image](https://user-images.githubusercontent.com/48558949/107231947-2ad50280-6a21-11eb-962e-8939f78d4693.png)

**Debug Info**
I dont know how to run the debug command... is it something like `nohup java -Dnogui=true -jar /mb/JMusicBot.jar -debug`?
i am running docker with a container of debian 10 (their official docker image), on it i have installed the openjdk11-amd64 package. Then put the musicbot currently newest version, with my config files on there and ran it with the command of step 3.

**Additional context**
Not sure what else to put in here, so please point me in the right direction if needed.

-The same config files and jar do run fine on my windows pc with the gui.

**Comment by MichailiK** [comment]
Try running without `nohup` & see what it outputs (`java -Dnogui=true -jar /mb/JMusicBot.jar`).

**Comment by jagrosh** [comment]
It's also important to note that `nohup` does not run the process in the background; you need to include a `&` at the end of the command if you want to run in the background. Also, please include which version of JMusicBot you are running.

**Comment by Coolykoen** [comment]
Right, i have an answer to both of your questions.

Running without nohup (which i thought was necessary, my bad) gives a surprising result. It asks for a bot token, which tells me its not loading the config file that is in the same folder? in windows it does read that file, do i need to specify it in my command?

As for the answer to Jagrosh, i did specify the bot version, i mentioned it was the currently latest version, 0.3.3

Thanks for the help, appreciate it

**Comment by jagrosh** [comment]
You can use `-Dconfig=/path/to/configfile` to specify which config file to use. By default, it looks in your current working directory (wherever you run the command from).

**Comment by Coolykoen** [comment]
I see. when i run this:
`java -Dnogui=true -jar /mb/JMusicBot.jar -Dconfig=/mb/config.txt`
it still asks for the bot token. I can post my config txt if you want, but it wont be very usefull since i'd remove the bot token and user id from it haha for privacy, so what can i try?

**Comment by Coolykoen** [comment]
Whoops... got it running, had to place the Dconfig argument before the jar filename.

Thanks guys! :3

**Comment by jagrosh** [comment]
For anyone reading this down the line, the advanced config options page on the wiki can be found [here](https://github.com/jagrosh/MusicBot/wiki/Advanced-Config-Options)
