### ISSUE TITLE
Volume does not seem to work

### ISSUE THREAD

**Issue by Waester** [jagrosh/MusicBot#6]
System: Raspberry Pi 3
OS: Raspbian

Changing volume to anything beside 100 seems to mute/silent the bot.
Tested values as 50, 99, 150 and all the results was the same, bot went silent and didn't seem to transmit music.

Using version 0.0.2-patch

**Comment by jagrosh** [comment]
Can you see if this version works

[JMusicBot-0.0.2-patch2.zip](https://github.com/jagrosh/MusicBot/files/767387/JMusicBot-0.0.2-patch2.zip)

**Comment by Waester** [comment]
Yeah, that fixed it and I can also confirm it fixed #8

Awesome work :+1:

**Comment by jagrosh** [comment]
Alright, so... a long-term solution might be a bit weird for this, since the extra required natives adds more total space to the jar than I'd like. In future releases, I will either need to make a separate release for rpi, or I can supply the single file that you'll need to add to all future releases. I'll think about this and comment on this issue at the time of the next release depending on what I decide.

**Comment by Waester** [comment]
For some reason your patch2 build used higher CPU resource, around 20%, while usually it stays around 5%.

So I built my own lavaplayer build using these changes
https://github.com/Waester/lavaplayer/commit/2229c93e2bd472dddacb5eda0d02892c64d4db89
and it was back to the old low resource usage.

**Comment by jagrosh** [comment]
Depending on how you rebuild it, you may see reactions being added at a much slower rate (1 per 1 second instead of my build that is 1 per 250ms). The reason for this is that I use a custom build of JDA that manually sets the reaction-add ratelimit instead of using Discord's (wrong) headers.

**Comment by flaxues** [comment]
@Waester Could you maybe share the jar since I have no clue on how to compile this 😂

**Comment by flaxues** [comment]
@jagrosh You could also provide a special ARM compiled jar...

**Comment by jagrosh** [comment]
@flaxues if you scroll up a bit, I already did in my first reply to this issue.

**Comment by flaxues** [comment]
@jagrosh Yes but Waester said this: 

> "For some reason your patch2 build used higher CPU resource, around 20%, while usually it stays around 5%. 
> 
> So I built my own lavaplayer build using these changes
> Waester/lavaplayer@2c27e69
> and it was back to the old low resource usage."

**Comment by Waester** [comment]
@flaxues Here you go.
[JMusicBot.zip](https://github.com/jagrosh/MusicBot/files/844117/JMusicBot.zip)

**Comment by flaxues** [comment]
@Waester Thanks

**Comment by Matthww** [comment]
@jagrosh Can you still make an "Official Jar" supporting ARM based system? I want those new features
