### ISSUE TITLE
[Question] SetStatus

### ISSUE THREAD

**Issue by Virus5947** [jagrosh/MusicBot#60]
The new "setstatus"-Feature is overriding the Status constantly. I want to have it on DND, but it will override to ONLINE again till I stop the bot (I'm not using the "setstatus"-command). And could you add a config-entry to let the bot Change the Status on Startup?

**Comment by jagrosh** [comment]
Adding a default status to the config is definitely possible.

As for the other part of the question... how are you setting the status without using the setstatus command?

**Comment by Virus5947** [comment]
I'm using a second bot to handle that.
I have edited your bot to "not using" the "**censored because of a global-post **" - method.
It seems to work now to change the Playing-Status and the status..
~~~
Maybe you could create another config-entry too, 
for example: "dont-use-status-system" to disable the overriding of this!

**Comment by jagrosh** [comment]
1. There is no such thing as "overriding" a status; every single connection to Discord _must_ have a status. Some statuses just take priority over others. To prevent what you call "overriding" you need to set the music bot to invisible.
2. If you're editing the bot, please don't post issues here. I realize that your issue isn't necessarily related to your edits, but I won't provide support for edited versions.

**Comment by Virus5947** [comment]
It's not really an issue. And I'm aware that your won't give support of edits (bc I read stuff :P), but as you said, it has nothing to do with "supporting". It's like just giving you feedback or information of something. I didn't think about setting it on invisible! But for now the official version will "Not work", because of it's missing feature, as I said previously. (Auto-Restart) Btw, as I know so far, "Type <help-cmd>" is the default status, which is set, if the config-entry is null? If setting to "none", it will completly empty it. Or is both the same? 
If you don't want this type of conversation in this section, we can continue to write private if you want!

**Comment by lamepenguins** [comment]
> I'm using a second bot to handle that.

What bot is this?

**Comment by Virus5947** [comment]
> I'm using a second bot to handle that.
---
I'm not advertising another bot here.

**Comment by jagrosh** [comment]
The config and command from the latest release should cover this, feel free to re-open if it still doesn't cover what is needed here.
