### ISSUE TITLE
Feature Request: Restart the bot with a discord command

### ISSUE THREAD

**Issue by dragonballz2k** [jagrosh/MusicBot#61]
It would be very useful if a command start glitching, and so you don't have to login into rdp,ssh,etc..

**Comment by jagrosh** [comment]
That is not possible due to the way the Java Virtual Machine works; please run the bot from a loop script and restart with the `shutdown` command

Example loop script (linux):
`loopbot.sh`
```bash
#!/bin/sh

while true
do
    java -jar JMusicBot.jar
done
```
(change the jar name to match the filename, or vice-versa)
