### ISSUE TITLE
[Feature Request] Monitoring Option

### ISSUE THREAD

**Issue by SunnyTeater** [jagrosh/MusicBot#610]
Not a real problem, but it would be nice if the bot had a minimal web interface.
That way you could simply check the status of the bot with e.g. uptimerobot.
If the bot is offline, the website also goes off. 

You don't have to be able to do much, a simple html page that the bot is running would be perfectly sufficient.

**Comment by lazaroblanc** [comment]
How meaningful would that be?
If you just want to check if the Bot is up you just need to look at it's Bot Users status, no?
If the bot is not running, the user won't be online.

If you want something that monitors the bot from the outside and also can do alerting if it goes down you might want to look into monitoring solutions like Icinga, Nagios, CheckMK...

**Comment by jagrosh** [comment]
The easiest way would be to just look at the bot's status in Discord, as already stated. Also, there are numerous concerns/difficulties with hosting a web page (port forwarding, public-facing IP addresses, etc) that are frankly beyond the scope of this project.
