### ISSUE TITLE
[Bug Report] 404 

### ISSUE THREAD

**Issue by marzenie** [jagrosh/MusicBot#639]
**Describe the bug**
when I try to start any song I get an error

**Expected behavior**

listening to music

**Screenshots**
![image](https://user-images.githubusercontent.com/29224655/111463790-41593280-8720-11eb-8800-b7595a122d2a.png)

**Debug Info**
latest version 
**Additional context**

all attempts were made by Youtube, the bot stopped working overnight

**Comment by BjornLV** [comment]
yep, I'm having the same problem here...

**Comment by Wobak** [comment]
Same also...
