### ISSUE TITLE
[Bug Report] No

### ISSUE THREAD

**Issue by fmnewton** [jagrosh/MusicBot#648]
**Describe the bug** I can't set it up can I get a replit link on it

Replace this text with a clear and concise description of wha the bug is.

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**
Replace this text with a clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem here.

**Debug Info**
Please run the `debug` command and paste it here or upload it as an attachment. If you cannot run the command, please provide information about your system such as operating system version, JMusicBot version, etc.

**Additional context**
Replace this text with any other context about the problem.

**Comment by jagrosh** [comment]
Repl is not a supported host
