### ISSUE TITLE
Spotify Stream Support?

### ISSUE THREAD

**Issue by Thurrax** [jagrosh/MusicBot#66]
Hello and thanks for that great Bot. On my Private Server i want to use Spotify as Service with the Bot. Is that possible? I own Premium, thats why i am asking.

**Comment by jagrosh** [comment]
That is not possible because:
a) It breaks Spotify's terms of service
b) Spotify streams are not open like youtube/soundcloud

**Comment by Macley-Kun** [comment]
@jagrosh perhapes it is possible to add spotify stream support. But maybe not for PUBLIC.

I talked to the developers from another github project that does support Spotify, withoud going into ToS from Spotify.

https://github.com/Frederikam/FredBoat/search?utf8=%E2%9C%93&q=spotify&type=

Maybe if you read trough the code on that search term, you can reverse engineer how they pulled it off. I really think it's handy to use!

**Comment by Pendrag00n** [comment]
If a Spotify link is given, you could just query Youtube/SoundCloud for the name of the Spotify song. Seems like a fair solution to me
