### ISSUE TITLE
[Bug Report] Random Toy Story video queueing

### ISSUE THREAD

**Issue by alfonsojon** [jagrosh/MusicBot#661]
**Describe the bug**
Replace this text with a clear and concise description of what the bug is.

Occasionally, when selecting a song to play, it selects a random Toy Story video...

**To Reproduce**
1. Search for a song
2. Use the keyboard to select a song
3. Instead of the expected song playing, you get a Toy Story video!

**Expected behavior**
It plays the actual song

**Screenshots**
![image](https://user-images.githubusercontent.com/1163298/113395889-35947f80-9360-11eb-86b3-e07adfb773cb.png)
![image](https://user-images.githubusercontent.com/1163298/113396026-6f658600-9360-11eb-8085-2df96dd18d44.png)

**Debug Info**
```
System Properties:
  java.version = 11.0.10
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 11
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 11.0.10+9-Ubuntu-0ubuntu1.20.04
  java.specification.version = 11
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.3.2
  Owner = 150301926821462016
  Prefix = m!
  AltPrefix = @mention
  MaxSeconds = 0
  NPImages = false
  SongInStatus = true
  StayInChannel = false
  UseEval = false
  UpdateAlerts = false

Dependency Information:
  JDA Version = 4.2.0_214
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.55

Runtime Information:
  Total Memory = 378
  Used Memory = 83

Discord Information:
  ID = 406874017644019744
  Guilds = 5
  Users = 5
```

**Additional context**
Video is called "Vlad and Nikita vending machine kids toy story 2"

**Comment by MichailiK** [comment]
You're misunderstanding the search command. You're supposed to just type the number with your search, not `;;play 2`. `;;play 2` **probably** causes 2 things:

1. The search command sees you typed `2` & as such adds the second result to the queue
2. You are now using the `;;play` command, it picks the first result it finds for `2` and finds `Vlad and Nikita vending machine kids toy story 2`.

Just use either the reactions or just type the number.

**Comment by alfonsojon** [comment]
That totally makes sense, didn't even realize I was doing it. Thanks!
