### ISSUE TITLE
Bot gives error message

### ISSUE THREAD

**Issue by SkyDrift** [jagrosh/MusicBot#663]
the Bot just keep giving me (I am unable to connect to Research-Coding!) every time I ask to play any thing was something missing during setup that was not mentioned here or is the Bot just broken?

**Comment by MichailiK** [comment]
Your bot doesn't have permission to join your voice channel ("Research-Coding"). Make sure it has permission to connect & speak.

**Comment by SkyDrift** [comment]
figured it out thanks for fast response
