### ISSUE TITLE
[Bug Report] Custom Per-Server Prefix not working

### ISSUE THREAD

**Issue by Mitzythecat** [jagrosh/MusicBot#675]
**Describe the bug**
When i do -prefix !, both the original prefix and the prefix i set work

**To Reproduce**
1. -Prefix <anyprefix>
2. Both the original prefix (-) and the new prefix work
3. It should be that only the per-server defined prefix should work

**Expected behavior**
It should only use the per server prefix but instead, it uses the original prefix (-) as well, this can conflict with other bots

**Screenshots**
https://prnt.sc/11b0hdc

**Debug Info**
https://paste.md-5.net/irugekolog.coffeescript

**Additional context**
None, i said everything i need to

**Comment by jagrosh** [comment]
This is intentional, the prefix in the config will always work and setting a server prefix will not override it. If you want a prefix that does not conflict with other bots, I would recommend setting your prefix in the config to
```
prefix = "@mention"
```
