### ISSUE TITLE
change the about section

### ISSUE THREAD

**Issue by itsnotoli** [jagrosh/MusicBot#678]
You should make it that you can change the about section of the bot.
Many people use that section. So maybe you could make it customizable.

It would make it seem cooler!

**Comment by 1zq** [comment]
This can be done via your bot's description area 
![image](https://user-images.githubusercontent.com/41847143/130022569-86134d4b-d7bb-4561-ad42-5c76df2d2070.png)

**Comment by jagrosh** [comment]
As stated, you can use the Bot's description on the developer page to add a bio under your bot's status. There are currently no plans to allow changing of the `about` command.
