### ISSUE TITLE
Shutdown feature

### ISSUE THREAD

**Issue by kristisnfq** [jagrosh/MusicBot#68]
Hello, I am pretty new to all this thing. Ive finally managed to get the bot working, played around for a bit. Once i tried the shutdown function the but went offline, obviously. How do I get it back to work?

**Comment by MatthewRing** [comment]
The point of a shutdown feature is to shut the bot down. To turn it on again, you either double-click the jar file, or run `java -jar JMusicBot-X.Y.Z.jar -nogui` from the terminal (X, Y, and Z are your version numbers).

**Comment by kristisnfq** [comment]
Ok thank you alot!
