### ISSUE TITLE
[Bug Report] Error when playing song

### ISSUE THREAD

**Issue by Nuckerr** [jagrosh/MusicBot#698]
**Describe the bug**
When I do !p {song name} my bot joins, leaves and repeats. The error is: ```[10:47:29] [WARN] [RateLimiter]: Encountered 429 on route PATCH/channels/{channel_id} with bucket 9852e1a53c06ffc5a89d65fef85ca4ce:guild_id:829702024505458698:webhook_id Retry-After: 134726 ms````
**To Reproduce**
1. join vc
2. run !p {song name}
3. look at console

**Expected behavior**
Just play the music in vc

**Screenshots**
https://user-images.githubusercontent.com/62883418/118391409-0db95c80-b62c-11eb-9eba-e5736b1ecd04.mp4

**Debug Info**
```[10:47:29] [WARN] [RateLimiter]: Encountered 429 on route PATCH/channels/{channel_id} with bucket 9852e1a53c06ffc5a89d65fef85ca4ce:guild_id:829702024505458698:webhook_id Retry-After: 134726 ms```

**Comment by jagrosh** [comment]
This isn't from playing a song. This is normal behavior for the bot attempting to update the channel topic of the text channel that you've set with `settc`. If you don't want to see these messages, don't give your bot the Manage Channel permission in your server.
