### ISSUE TITLE
Remove the inserted command .play after it's bin added

### ISSUE THREAD

**Issue by Macley-Kun** [jagrosh/MusicBot#71]
I'm new to your bot, but already loving it so much! I do have a small request.

If i would play a song/vid. It nicely says which song is added. But i don't like that the chat stay's filled with the command i putted in (aka .play <url> <preview of the video>).

In the picture you can see what i mean with 'spammy'.

![schermafbeelding 2017-09-16 om 10 56 43](https://user-images.githubusercontent.com/26381427/30510895-c0fca87a-9acd-11e7-817f-1acfb6639d3a.png)

Is it an idea to make it optional that the bot removes the .play command a user inserted?

Love your bot dude, you have by far the best looking music bot (that also performs twice as well compared to others).

**Comment by jagrosh** [comment]
This is already on the [planned features list](https://github.com/jagrosh/MusicBot/projects/1)
