### ISSUE TITLE
[Feature Request] Video support

### ISSUE THREAD

**Issue by pooman2** [jagrosh/MusicBot#710]
it would be great if the bot can stream video off a YouTube livestream or video into a discord channel

**Comment by MichailiK** [comment]
This used to be possible when Go Live was initially released. Discord has completely disabled Go Live for all bots a few days later though.

**Comment by jagrosh** [comment]
As stated, bots cannot stream video. If this changes at some point in the future, another feature request (that follows the template) can be filled out.
