### ISSUE TITLE
so f i wanna make online the whole time how can i do it?

### ISSUE THREAD

**Issue by lucifer2600** [jagrosh/MusicBot#712]
**Is your feature request related to a problem? Please describe.**
Replace this text with a clear and concise description of what the problem is.

**Describe the solution you'd like**
Replace this text with a clear and concise description of what you want to happen.

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. 
2. 
3. 

**Additional context**

**Please check the following links to confirm that your feature has not already been requested:**
https://github.com/jagrosh/MusicBot/labels/enhancement
https://github.com/jagrosh/MusicBot/wiki/Things-That-Won%27t-Be-Added

**Comment by YJSoft** [comment]
You have to run jar file 24 / 7. There are no other ways to do that.

**Comment by lucifer2600** [comment]
okay ty
