### ISSUE TITLE
[Feature Request] Add "Goto" command

### ISSUE THREAD

**Issue by hermitoff** [jagrosh/MusicBot#713]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add "goto" command to go to a moment in the music.

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. (prefix)goto 1:08
2. The bot will go to 1 minute and 8 seconds

**Additional context**
Disable this command if the music is a live.

**Please check the following links to confirm that your feature has not already been requested:**
https://github.com/jagrosh/MusicBot/labels/enhancement ✅
https://github.com/jagrosh/MusicBot/wiki/Things-That-Won%27t-Be-Added ✅

**Comment by jagrosh** [comment]
There is already an open pull request for a seek command
