### ISSUE TITLE
[Bug Report] Build Failed.

### ISSUE THREAD

**Issue by iMu7aMMaD** [jagrosh/MusicBot#715]
- mvn clean package --batch-mode -DskipTest
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< com.jagrosh:JMusicBot >------------------------
[INFO] Building JMusicBot Snapshot
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] Downloading from bintray-sedmelluq-com.sedmelluq: https://dl.bintray.com/sedmelluq/com.sedmelluq/com/sedmelluq/lavaplayer-natives-extra/1.3.13/lavaplayer-natives-extra-1.3.13.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.964 s
[INFO] Finished at: 2021-06-20T22:05:50+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project JMusicBot: Could not resolve dependencies for project com.jagrosh:JMusicBot:jar:Snapshot: Failed to collect dependencies at com.sedmelluq:lavaplayer-natives-extra:jar:1.3.13: Failed to read artifact descriptor for com.sedmelluq:lavaplayer-natives-extra:jar:1.3.13: Could not transfer artifact com.sedmelluq:lavaplayer-natives-extra:pom:1.3.13 from/to bintray-sedmelluq-com.sedmelluq (https://dl.bintray.com/sedmelluq/com.sedmelluq): authorization failed for https://dl.bintray.com/sedmelluq/com.sedmelluq/com/sedmelluq/lavaplayer-natives-extra/1.3.13/lavaplayer-natives-extra-1.3.13.pom, status: 403 Forbidden -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by jagrosh** [comment]
Building this project yourself is not supported.
