### ISSUE TITLE
Discord bot have high ping with hosting server 

### ISSUE THREAD

**Issue by EnisYK** [jagrosh/MusicBot#716]
i have use the music bot but the problem is that it have high ping for no reason some time its going to 1000 ping websocket 104 ms but the bot react later then normal
![hoge ping](https://user-images.githubusercontent.com/81716532/122833301-03eedd00-d2ed-11eb-97ba-32f21fc04308.PNG)

**Comment by jagrosh** [comment]
This is a problem with your hosting, not with JMusicBot itself. You also haven't provided any additional information to help debug the issue.
