### ISSUE TITLE
[Bug Report] Queue loosing tracks after a while 

### ISSUE THREAD

**Issue by krummfinger** [jagrosh/MusicBot#720]
**Describe the bug**
I noticed that my Musicbot is loosing some tracks after some hours. In this case 3 of 24 songs where dropped

**To Reproduce**
I have the bot always on and tried songs from a yt playlist or single songs one after another.

**Expected behavior**
Songs stay in the playlist :-)

**Debug Info**
HW: pi4b 4gb

SW: 
Linux raspberrypi 5.10.17-v8+ #1421 SMP PREEMPT Thu May 27 14:01:37 BST 2021 aarch64 GNU/Linux
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.11+9-post-Debian-1deb10u1, mixed mode)

Starting parameters:
nohup java -Dnogui=true -jar JMusicBot-0.3.4.jar &

[nohuplog.txt](https://github.com/jagrosh/MusicBot/files/6702859/nohuplog.txt)

**Comment by jagrosh** [comment]
It looks like some tracks just failed to play. There are a multitude of reasons that could cause this, such as:
- a temporary drop in the bot's internet connection
- youtube temporarily blocking the bot or preventing a video from loading
- request timeouts
This is fairly normal behavior. A newer release of JMusicBot may help with this, but occasionally tracks having issues is to be expected.
