### ISSUE TITLE
[Feature Request] Update the JDA version to the last version

### ISSUE THREAD

**Issue by hermitoff** [jagrosh/MusicBot#724]
**Is your feature request related to a problem? Please describe.**
Update to the new update of JDA (https://github.com/DV8FromTheWorld/JDA/releases/tag/v4.3.0)

**Describe the solution you'd like**
Just update the JDA version for use the / commands and more !
The bot uses JDA version `(4.2.1_253)`. But the latest version is `4.3.0`

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. This is not a bug or an enhancement, just an update of JDA.

**Additional context**
None

**Please check the following links to confirm that your feature has not already been requested:**
https://github.com/jagrosh/MusicBot/labels/enhancement ✅
https://github.com/jagrosh/MusicBot/wiki/Things-That-Won%27t-Be-Added ✅

**PS** : When i use EVAL commands, in the console i have that : 
![image](https://user-images.githubusercontent.com/82811865/125150124-fe1c4700-e188-11eb-83b8-965e5f995bf9.png)

**Comment by jagrosh** [comment]
Simply updating the JDA version will not automatically make slash commands work; those will need to be implemented separately. Additionally, updating the JDA version is normal for every new release of JMusicBot. Finally, that warning is normal, the Nashorn engine may get removed at some point, but for now, it's fine to continue using it.
