### ISSUE TITLE
[Feature Request] Option to automatically leave the guild if owner is not present on join

### ISSUE THREAD

**Issue by revi** [jagrosh/MusicBot#725]
**Is your feature request related to a problem? Please describe.**
I don't want someone to use my bot without me knowing. (If they need the bot, they probably should self-host themselves)

**Describe the solution you'd like**
Make a config option to automatically leave if the `owner` is not present in the guild, when they join the new server.

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. Set a config option (probably boolean?) to define if bot should leave the server if the owner is not present in the server.
2. Bot checks user list (priv. intent probably required if true)
3. Leave if owner is not present

**Additional context**

**Please check the following links to confirm that your feature has not already been requested:**
https://github.com/jagrosh/MusicBot/labels/enhancement
https://github.com/jagrosh/MusicBot/wiki/Things-That-Won%27t-Be-Added

Closest ticket I could find was #39 but that's just manually force-leaving the server, not automatically leaving the server, so I would claim it is different.

**Comment by jagrosh** [comment]
This seems unnecessary, as you can just set your bot to private if you don't want people to add it. If the bot is already on servers you don't want it on, check the common eval scripts page on the wiki for how to remove it from servers using eval.
