### ISSUE TITLE
.status actully showing something different then .settings

### ISSUE THREAD

**Issue by Macley-Kun** [jagrosh/MusicBot#73]
Is it an option to make .status/.stats to show something like this?

![schermafbeelding 2017-09-16 om 14 08 11](https://user-images.githubusercontent.com/26381427/30512143-7ef09d90-9ae8-11e7-84f2-c02a2a1c178f.png)

Sometimes i need to check memory usage, uptime (other?). I would love if this could be added!

**Comment by Matthww** [comment]
I agree this would be nice to have!

**Comment by Macley-Kun** [comment]
I'm trying to ask teh developer but don't rlly get an answer, in Discord itself i don't find any numbers ether. I'm sure it's allright to do tho.

Anyone ok giving me the correct info/link were i have to look?

**Comment by TheMonitorLizard** [comment]
Why would a music bot need this?

This is a useless feature for a music bot.
If you want a feature like this you should just use Nadeko or some other bot like you did in that picture.

**Comment by Macley-Kun** [comment]
If you selfhost it's a nice have to check how your bot is doing withoud using ssh and doing htop for example.

Wouldn't say it's useless, rather limited to the audience :^)

**Comment by Matthww** [comment]
As @Macley-Kun said I want to know how what the stats are from the bot for example what the ram usage of the bot is, in how many servers the bot is playing music etc.

**Comment by jagrosh** [comment]
This has been added to the [suggested feature list](https://github.com/jagrosh/MusicBot/projects/1)
