### ISSUE TITLE
Loop feature

### ISSUE THREAD

**Issue by BoyGau** [jagrosh/MusicBot#74]
Is there a feature to loop songs in a queue or playlists? If no could you add this feature by command and can toggle it on and off? Thanks alot

**Comment by darkbeast1** [comment]
this is already suggested!

**Comment by jagrosh** [comment]
You can set an autoplaylist for a server to have it loop forever, and a repeat mode is already on the [planned feature list](https://github.com/jagrosh/MusicBot/projects/1)
