### ISSUE TITLE
[Feature Request] .m3u and .mp3 stream links

### ISSUE THREAD

**Issue by MarlonMagDich** [jagrosh/MusicBot#743]
**Is your feature request related to a problem? Please describe.**
There is no problem, but I would like to be able to stream links like: https://www.ilovemusic.de/iloveradio.m3u

**Describe the solution you'd like**
I would like to have the option for playing .m3u and .mp3 links

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1.  To Stream online radio

**Additional context**

**Please check the following links to confirm that your feature has not already been requested:**
https://github.com/jagrosh/MusicBot/labels/enhancement
https://github.com/jagrosh/MusicBot/wiki/Things-That-Won%27t-Be-Added

**Comment by MichailiK** [comment]
Uhh...

![image](https://user-images.githubusercontent.com/39029839/131220133-1fb71517-8f73-47bf-a3f3-f77c6d50473c.png)

**Comment by jagrosh** [comment]
Both of these formats are already supported
