### ISSUE TITLE
[Bug Report] If I play music, stop it a few seconds later it crashes

### ISSUE THREAD

**Issue by NOTBLADEZz** [jagrosh/MusicBot#746]
**Describe the bug**
When I stop using the bot for a few seconds it crashes [Running From Heroku]

**To Reproduce**
1. Play a Song
2. Stop The Song
3.  Wait for A few minutes 

**Expected behavior**
I expected the Bot to stay up after stopping the music 

**Screenshots**
![image](https://user-images.githubusercontent.com/78879375/131314272-3b057a9d-b4bd-4d80-b377-a5108c8e6cd7.png)

**Debug Info**
Please run the `debug` command and paste it here or upload it as an attachment. If you cannot run the command, please provide information about your system such as operating system version, JMusicBot version, etc.
OS Version - MS Windows 10 Home 10.0.19042 (But running off Heroku)
JMusic Bot Version - 0.3.4. (Latest)

**Comment by Sanduhr32** [comment]
Free hosts are not supported. If you would care to read your screenshot, you would see that Heroku expected a web app to bind to a certain port, which jmusicbot not does. Herold force stopped your bot thereby.
