### ISSUE TITLE
Missing config file

### ISSUE THREAD

**Issue by raffibaihaqy02** [jagrosh/MusicBot#761]
I try to run the bot and this happen
<img width="960" alt="1" src="https://user-images.githubusercontent.com/42157989/132248290-95220254-1dd9-43ef-ad91-e6e9e261aa6e.png">
it says config file located on C:\Windows\System32 but I can't find it
<img width="960" alt="2" src="https://user-images.githubusercontent.com/42157989/132248359-f29621ca-e8c4-42a7-b80f-9be2bde77269.png">

**Comment by MichailiK** [comment]
This is a bug that should have been already fixed. Could you tell/show us how you are starting the bot (best in a video)?
