### ISSUE TITLE
[Feature Request] Please Add Single Song repeat

### ISSUE THREAD

**Issue by masterlinnn** [jagrosh/MusicBot#762]
How this feature would be used:
1. This will allow user to choose and repeat an single song in the queue.
2. When is in single song repeat mode, it override the whole queue repeat and vice-versa.
3. When repeat is type in again after the single repeat song it will repeat the queue and stop repeat the single song choosen.

**Comment by MichailiK** [comment]
Feature already has a pull request (#359)
