### ISSUE TITLE
Announce new song in chat 

### ISSUE THREAD

**Issue by ItsJakeo** [jagrosh/MusicBot#769]
Have the ability to announce a new song in the chatbox when the song starts. 
Have the option in config file to turn on or off announce songs.

**Comment by DJMoffinz** [comment]
That’s a good idea.

**Comment by very-lame-username** [comment]
You could also just call nowplaying at the start of each song and delete the old one to keep it effectively pinned.

**Comment by StargazerVoyager** [comment]
Yes please, I'm very much interested in this feature!

**Comment by jagrosh** [comment]
Duplicate of #353
