### ISSUE TITLE
Song stays on 00:00

### ISSUE THREAD

**Issue by MedicOP** [jagrosh/MusicBot#78]
The first time you use !play, it will say "Loading bla bla song" but it will never finish loading

Then you use !play again, it loads the song, !np says it's playing the song, etc, but it stays at 00:00 and there is no sound

**Comment by jagrosh** [comment]
Do you have reliable steps to reproduce this? Is it always with a certain song? What platform are you running on? What settings do you have in place?

**Comment by MedicOP** [comment]
It happens with any song. I'm running on Centos 6.5 x64.

It works if I try it on my own Windows computer, but it does not work when I try it on any of my 7 CentOS servers. 

Default settings for the bot

**Comment by MedicOP** [comment]
No errors in console whatsoever either

**Comment by MedicOP** [comment]
Any way for me to debug this?

**Comment by chadouming** [comment]
I have the same problem when trying to play song from my ubuntu server. I'd be happy to help you debug if you can provide me some steps or a debug build.

**Comment by sebastianbinder** [comment]
> Edit: Seems to be related with my server being on Hetzner

Interesting fact. Cannot play any sounds on my Hetzner server as well. Any ideas how to solve this?

**Comment by MedicOP** [comment]
I use OVH, works fine on my own Windows computer

**Comment by jagrosh** [comment]
Discord blocks all voice connection from Hetzner, so there is no way to use this or any other music bot on a Hetzner server.

**Comment by MedicOP** [comment]
This one does work though on my OVH server https://github.com/Just-Some-Bots/MusicBot

**Comment by angelalukic** [comment]
Had this issue as well. Bot would keep leaving and rejoining the channel, unable to play the song.

It was not working on my Windows PC, but when I ran the bot from my Amazon EC2 server it worked. So it's probably an OS/Network issue?

**Comment by jagrosh** [comment]
Is this still an issue in Version 0.1.1?

**Comment by innerdaze** [comment]
Hi, I'm also having this issue. Running on a Debian 9 Digital Ocean server. Last successful message is
```
[JDA MainWS-ReadThread] INFO net.dv8tion.jda.core.managers.AudioManager - Audio System successfully setup!
```

**Comment by MedicOP** [comment]
@innerdaze are you using version 0.1.1?

**Comment by jagrosh** [comment]
Version 0.1.2 is the latest version, at the time of writing. The latest version can always be found [here](https://api.github.com/repos/jagrosh/MusicBot/releases/latest).

**Comment by jagrosh** [comment]
Closing as this has been untouched for several months and newer versions of the bot have been released.
