### ISSUE TITLE
How Can I Add Codes for Spotify Playlist

### ISSUE THREAD

**Issue by VisTy1** [jagrosh/MusicBot#787]
hello! wanted to ask if how i can codes for spotify?

**Please check the following links to confirm that your feature has not already been requested:**
https://github.com/jagrosh/MusicBot/labels/enhancement
https://github.com/jagrosh/MusicBot/wiki/Things-That-Won%27t-Be-Added

**Comment by YJSoft** [comment]
1. Spotify will not be added. See [this wiki page](https://github.com/jagrosh/MusicBot/wiki/Things-That-Won%27t-Be-Added)
2. Editing source code is not supported(see [README](https://github.com/jagrosh/MusicBot#editing))
3. Streaming from Spotify isn't allowed. so there are no way to stream from spotify.
