### ISSUE TITLE
[Bug Report] Everytime i go to play a song it doesnt play the song

### ISSUE THREAD

**Issue by Scummy123** [jagrosh/MusicBot#792]
so i type the name of the song for it to play, it says now playing (song name) no sound at all then 3 seconds later the bot disconnects, what do i do?

**Comment by Scummy123** [comment]
the error says Caused by: javax.crypto.AEADBadTagException: Tag mismatch!

**Comment by jagrosh** [comment]
Please follow the template and include the output of the debug command; there isn't nearly enough information here to debug your issue.
