### ISSUE TITLE
libconnector.so was not found (arm)

### ISSUE THREAD

**Issue by EarsKilla** [jagrosh/MusicBot#8]
> Required library at /natives/linux-arm/libconnector.so was not found

while trying to play music when it running on raspberry pi (debian 8)

**Comment by jagrosh** [comment]
Possibly related to #6 which was also on a raspberry pi; I'll be looking into this

**Comment by jagrosh** [comment]
Can you see if the `patch2` jar supplied in #6 solves this issue?

**Comment by EarsKilla** [comment]
yeah, problem is fixed
