### ISSUE TITLE
[Bug Report] Bot is offline - noob question 

### ISSUE THREAD

**Issue by TheBjorno** [jagrosh/MusicBot#804]
**Describe the bug**
Hi all, so i'm fairly new to all this, so i hope i'm in the correct place for questions. I followed all the steps in the setup guide but the bot itself stays offline in my server and doesnt respond to any commands. I just need it to work when I'm online myself for our personal discord server, so i don't need 24/7 hosting. Just want it to work when i'm online. 

**To Reproduce**
1.  Followed installation instructions
2.  Bot joins server but is offline
3.  Big sad

**Expected behavior**
Bot being online when i'm online 

**Debug Info**
windows build19042.1165
Bot version 0.35
Java version 8 update 301, buyld 1.8.0_301b09

**Comment by DJoepie** [comment]
Did you make a `config.txt` and are you actually running the bot?
Because after adding it to your server you still need to start the bot.
[Run JMusicBot](https://github.com/jagrosh/MusicBot/wiki/Setup#4%EF%B8%8F%E2%83%A3-run-jmusicbot)

I've personally just installed it on a Raspberry Pi and it seems to be working for me.

**Comment by MichailiK** [comment]
There can be a plethora of other reasons the bot may not be running. Consider joining the [development server](https://discord.gg/0p9LSGoRLu6Pet0k) and ask here instead of GitHub Issues. GitHub Issues are meant for bugs & feature requests.

**Comment by TheBjorno** [comment]
> Did you make a `config.txt` and are you actually running the bot?
> Because after adding it to your server you still need to start the bot.
> [Run JMusicBot](https://github.com/jagrosh/MusicBot/wiki/Setup#4%EF%B8%8F%E2%83%A3-run-jmusicbot)
> 
> I've personally just installed it on a Raspberry Pi and it seems to be working for me.

I had to launch the bot again.. thanks for the response! that fxied it
