### ISSUE TITLE
[Bug Report] Skip function removes song while on Repeat

### ISSUE THREAD

**Issue by toumaa** [jagrosh/MusicBot#805]
**Describe the bug**
Title

**How to Reproduce**
1. Add a playlist/ multiple songs
2. Make sure "Repeat" is "on"
3. Skip

**Expected behavior**
I expected the song to be moved on the end of the playlist.

**Additional context**
Repeat function also remains on even after the bot was shut down.

**Comment by MichailiK** [comment]
Both features are intentional.
