### ISSUE TITLE
[Feature Request] More Settings/Enhanced config file

### ISSUE THREAD

**Issue by Z0pyrus** [jagrosh/MusicBot#806]
I don't like that the bot can play files/videos that are not on YouTube..., thats why I would like to have a better Config file were you can set the bot to youtube only.
Also I think it would be nice if we had the chance to set the status and the rich presence (The "Playing now") more, like setting the image individually of the "game".

**Comment by MichailiK** [comment]
> were you can set the bot to youtube only
I believe there will only be a switch for external url sources. YouTube, Soundcloud, Twitch streams etc. would then still work.

> set the status and the rich presence
Bots can not set a custom status or have rich presence.

**Comment by MichailiK** [comment]
Regarding disallowing usage of external URLs (not from YouTube, SoundCloud) is now tracked under #808.
