### ISSUE TITLE
Suggestion: Autoplay

### ISSUE THREAD

**Issue by csb20** [jagrosh/MusicBot#81]
I've seen this feature in many other bots but not in this one, All it does is when the queue is empty it picks another song from youtube related to the last played (not local) song.

Maximum respect for making the bots btw, keep up the good work!:)

**Comment by darkbeast1** [comment]
Sounds good! 👍🏻

**Comment by jagrosh** [comment]
Playing a 'related song' is not as easy as it may sound, but I haven't looked into it a lot. In the meantime, consider putting together a playlist in a playlist file and set it to be the autoplaylist for a server - this will make it play from the autoplaylist when the user-requested queue runs out.

**Comment by jagrosh** [comment]
With the latest release (0.1.1 at the time of writing), you can now play youtube mixes by playing a song in it and then selecting to load the additional songs as well. This is probably the closest that can be gotten to a "related song" at this time, although I will continue to search for additional ways.
