### ISSUE TITLE
[Feature Request] Moderation commands for Admin level

### ISSUE THREAD

**Issue by LcorpOfficial** [jagrosh/MusicBot#812]
**Is your feature request related to a problem? Please describe.**
no ability to moderate users abusing usage.

**Describe the solution you'd like**
ability to use `[prefix]ban` to disallow requests in audio channel

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. admin users type command `[prefix]ban [ID or @mention]`
2. users recieve response in chat that they cannot request tracks at this time

**Comment by jagrosh** [comment]
This is an extremely niche feature, and not one usually needed by a private music bot.

Instead, I would recommend that you 
1. Use `settc` to lock the bot to only one channel where people can add music
2. Use channel permissions to prevent people from sending messages in that channel if you don't want them adding songs to the bot
