### ISSUE TITLE
Suggestion: Spotify 

### ISSUE THREAD

**Issue by darkbeast1** [jagrosh/MusicBot#82]
Since it’s not possible for the bot directly stream from Spotify, could it be possible for the bot (when given a Spotify link) to find the equivalent song automatically through other sources (YouTube, sc, band camp, etc.)?

**Comment by ArtutoGamer** [comment]
Not every Spotify track its on YouTube

**Comment by jagrosh** [comment]
I believe the Spotify API requires an API key, in which case this will not be added. If there is a free (no-key) version or way to obtain the songs, this issue can be reopened.

**Comment by Macley-Kun** [comment]
There is a way to aquire the songs. If you use the api-key of spotify you can read the songs.
Another bot (fredboat) actully looks up the song from spotify, and uses youtube, soundcloud (etc) and uses that to play.

**Comment by jagrosh** [comment]
I already stated in my last comment that I will not be adding a feature that requires an additional API key
