### ISSUE TITLE
after i enter !play `song name` bot connect and immediately disconnect

### ISSUE THREAD

**Issue by Wakjyst** [jagrosh/MusicBot#83]

**Comment by jagrosh** [comment]
What platform are you on, and what host provider are you using?

**Comment by Wakjyst** [comment]
Windows

**Comment by jagrosh** [comment]
Does this continue after restarting the bot?

**Comment by Wakjyst** [comment]
yes

**Comment by Wakjyst** [comment]
bot can interrupt the playback for no reason

**Comment by Wakjyst** [comment]
![screenshot_1](https://user-images.githubusercontent.com/29844383/31821592-4e2bcabe-b5ae-11e7-99bc-5709cda0303f.png)
maybe these problems are out of ping
