### ISSUE TITLE
Audio not playing in voice call

### ISSUE THREAD

**Issue by RetroGEO** [jagrosh/MusicBot#84]
After some time the bot will no longer play audio in the voice channel. The chat channel it's getting commands from says that songs are playing and I can use commands and see the queue just fine but audio doesn't play. Restarting the java program fixes this temporarily but I'm meant to run the bot continuously as others are online when I'm offline. All commands work fine but audio does not play.

**Comment by jagrosh** [comment]
Do other users have this same issue, or just you? Is the bot on multiple servers that you are on as well? What platform are you running the bot on?

**Comment by RetroGEO** [comment]
First, thanks for actually responding.
I'll be answering sequentially for clarity and brevity:

Any user in the server that attempts to enter a command during this "bugged" period experiences the same thing as myself.
The bot is only on this one server and is tied to only one text/voice channel respectively.
I'm using java 64-bit on windows 10 professional with a wired 1.0 Gbps Ethernet connection. I can list my individual hardware specs if needed.

**Comment by jagrosh** [comment]
Does the `nowplaying` command indicate that the song is moving forward?

**Comment by RetroGEO** [comment]
Yes, the scrubber moves forward like normal but no audio is actually playing as if id thinks a song is playing when it is not. I have also confirmed that no one is server muting the bot during these periods since that was something I was curious about at least.

**Comment by RetroGEO** [comment]
Update: Using .stop to stop the bot and playing something fixes the issue until the next time it's triggered.
Consider it a workaround of sorts.

**Comment by jagrosh** [comment]
I believe that any issues related to this should have been fixed a few releases ago (latest release at the time of writing is 0.1.1)
