### ISSUE TITLE
[Feature Request] Leave Command

### ISSUE THREAD

**Issue by BluepanicDV** [jagrosh/MusicBot#846]
It is simple, a command so that the bot can leave the music channel, I know that it can be configured so that after X time the bot leaves the channel, but it would be more like a second option if this leave command is added, allowing that the servers that have finished do not consume resources of the bot's servers

Example
_I think it's a bit obvious, but I'm going to put it anyway_

Bot prefix: **?**

Command in config archive: **Leave**

Using the command: **?Leave**

According to the configuration file, the bot would simply leave the channel or leave it and send a message to the channel where the _?Leave_ command was sent.

that simple, I hope to explain it well...

**Comment by MichailiK** [comment]
... `?stop`?
