### ISSUE TITLE
Ability to shuffle playlist + Repeat playlist after it completes

### ISSUE THREAD

**Issue by ThisTNTSquid** [jagrosh/MusicBot#85]
Just as the title says, If the bot is able to shuffle the playlist playing (which is impossible right at the moment), then it would be much more convenience as a radio bot. Also, if the situation is ok, it would be a great idea to allow repeating the playlist after it finished playing every song (now it just stops there, and exit)

**Comment by jagrosh** [comment]
This is already possible... there is a `shuffle` command to shuffle the songs that you have added.
If you are playing from a playlist file, you can add `#shuffle` or `//shuffle` on a separate line to automatically shuffle the playlist when loaded.
If you set an autoplaylist for a server, it will continue to repeat and not leave the channel.
