### ISSUE TITLE
[Bug Report] Bot has issues when playing local music

### ISSUE THREAD

**Issue by AnimeHasFallen** [jagrosh/MusicBot#850]
### Bug Description

When playing songs from the local music folder the bot seems to pause and skip occasionally. At first I thought it was just connection issues, but it's on a gigabit connection is a datacenter and other music sources will play fine.

### Steps to Reproduce

1. upload and play music from the local drive
2. Local songs skip and pause

### Expected Result

for the music to play smoothly like other sources.

### Debug Output

```shell
System Properties:
  java.version = 11.0.12
  java.vm.name = OpenJDK 64-Bit Server VM
  java.vm.specification.version = 11
  java.runtime.name = OpenJDK Runtime Environment
  java.runtime.version = 11.0.12+7-post-Debian-2deb10u1
  java.specification.version = 11
  os.arch = amd64
  os.name = Linux

JMusicBot Information:
  Version = 0.3.5
  Owner = 128202318876246017
  Prefix = ^
  AltPrefix = daddy
  MaxSeconds = 0
  NPImages = false
  SongInStatus = false
  StayInChannel = true
  UseEval = false
  UpdateAlerts = false

Dependency Information:
  JDA Version = 4.3.0_312
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.78

Runtime Information:
  Total Memory = 36
  Used Memory = 29

Discord Information:
  ID = 807512649591947264
  Guilds = 80
  Users = 89
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
I can't seem to reproduce this. Local AAC files are playing just fine for me. Could you send sample audio files that reproduce stutter on *every* system (and can thus be considered as a bug)?

Perhaps it is your system not being able to deal with the load. Try checking your CPU usage and Disk I/O while playing local files.

**Comment by MichailiK** [comment]
Assuming this issue is stale or resolved.
