### ISSUE TITLE
Ability to "Scrub Songs"

### ISSUE THREAD

**Issue by jordanmuss** [jagrosh/MusicBot#86]
Hey was just wondering if there is any way to play a specific time of a song?
Most of my playlists consist of 30-60 min long compilations and sometimes a User or Myself would love to listen to a specific part of said compilation.

**Comment by jagrosh** [comment]
This is already on the [planned features list](https://github.com/jagrosh/MusicBot/projects/1).

**Comment by MrDWilson** [comment]
Was this ever completed? I can't see a command for it in the help list. I can add it myself if it's not, just wanted to check.
