### ISSUE TITLE
[Feature Request] Restart regularly

### ISSUE THREAD

**Issue by Aumopko** [jagrosh/MusicBot#866]
Is your feature request related to the problem? Please describe.
Yes

Describe the solution you want
Restart regularly or restart by command

Describe the basic process/steps of using this function
1.Type "prefix" restart
2.restart every 6 hours, 12 hours, 24 hours

**Comment by jagrosh** [comment]
The bot is designed to be able to run continuously, there shouldn't be a need to restart it regularly.
