### ISSUE TITLE
[Feature Request] Can you add the option to hide the window of JMusicBot?

### ISSUE THREAD

**Issue by kurumicute** [jagrosh/MusicBot#888]
**Is your feature request related to a problem? Please describe.**
add the option to hide the window of JMusicBot

**Describe the solution you'd like**
There is a button to hide the program to run in the background

**Describe the basic flow/steps of using this feature**
How this feature would be used:
1. hit botton
2. Let the program run in the background

**Additional context**

**Please check the following links to confirm that your feature has not already been requested:**
https://github.com/jagrosh/MusicBot/labels/enhancement
https://github.com/jagrosh/MusicBot/wiki/Things-That-Won%27t-Be-Added

**Comment by MichailiK** [comment]
Duplicate of #546
