### ISSUE TITLE
[Feature Request] Search on Youtube from Spotify link

### ISSUE THREAD

**Issue by SPEED0U** [jagrosh/MusicBot#889]
**Describe the solution you'd like**
A feature to extract Spotify link data (artist and song name) to search on YouTube.

How this feature would be used:
1. When a Spotify link is sent get the artist and song name
2. Once artist and song name found play a matching song from YouTube

**Comment by MichailiK** [comment]
https://jmusicbot.com/things-that-wont-be-added

**Comment by SPEED0U** [comment]
I did not mean playing from Spotify. Just get artist and song name then search and play from Youtube.

**Comment by MichailiK** [comment]
Read the link I've sent. Spotify support **will not** be added for the reasons mentioned in the link, and the project maintainer has explicitly stated that Spotify support will **never** be added.
