### ISSUE TITLE
Bot keep disconnecting

### ISSUE THREAD

**Issue by toplez** [jagrosh/MusicBot#89]
Hello,
I using vps, playing youtube playlist
I think it's a problem from my vps.
I want to report to the vps provider but I do not know where the exact problem

OS : ubuntu 16.04
console logs:
> [02:17:26] [Warning] [JDASocket]: Got disconnected from WebSocket (Internet?!)...
> [02:17:26] [Warning] [JDASocket]: Attempting to reconnect in 2s
> [02:17:28] [Warning] [JDASocket]: Attempting to reconnect!
> [02:17:28] [Info] [JDASocket]: Connected to WebSocket
> [02:17:28] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 360733075358875649
> [02:17:28] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 360734323843792897
> [02:17:28] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 360735616914161664
> [02:17:28] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 360736316453027842
> [02:17:28] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 361015356816359424
> [02:17:28] [Info] [JDA]: Finished (Re)Loading!
> [02:17:50] [Warning] [JDASocket]: Got disconnected from WebSocket (Internet?!)...
> [02:17:50] [Warning] [JDASocket]: Attempting to reconnect in 2s
> [02:17:52] [Warning] [JDASocket]: Attempting to reconnect!
> [02:17:53] [Info] [JDASocket]: Connected to WebSocket
> [02:17:53] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 360733075358875649
> [02:17:53] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 360734323843792897
> [02:17:53] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 360735616914161664
> [02:17:53] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 360736316453027842
> [02:17:53] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 361015356816359424
> [02:17:53] [Info] [JDA]: Finished (Re)Loading!
> [02:19:10] [Warning] [JDASocket]: Got disconnected from WebSocket (Internet?!)...
> [02:19:10] [Warning] [JDASocket]: Attempting to reconnect in 2s
> [02:19:12] [Warning] [JDASocket]: Attempting to reconnect!
> [02:19:12] [Info] [JDASocket]: Connected to WebSocket
> [02:19:12] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 360733075358875649
> [02:19:12] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 360734323843792897
> [02:19:12] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 360735616914161664
> [02:19:12] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 360736316453027842
> [02:19:12] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 361015356816359424
> [02:19:12] [Info] [JDA]: Finished (Re)Loading!
> [02:21:16] [Warning] [JDASocket]: Got disconnected from WebSocket (Internet?!)...
> [02:21:16] [Warning] [JDASocket]: Attempting to reconnect in 2s
> [02:21:18] [Warning] [JDASocket]: Attempting to reconnect!
> [02:21:18] [Info] [JDASocket]: Connected to WebSocket
> [02:21:18] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 360733075358875649
> [02:21:18] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 360734323843792897
> [02:21:18] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 360735616914161664
> [02:21:18] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 360736316453027842
> [02:21:18] [Fatal] [JDASocket]: Got permission_override for unknown channel with id: 361015356816359424
> [02:21:18] [Info] [JDA]: Finished (Re)Loading!

thanks!

**Comment by jagrosh** [comment]
It looks like the VPS does not have a stable connection, or maybe limited/throttled bandwidth
