### ISSUE TITLE
[Feature Request] The ability to seek within a song

### ISSUE THREAD

**Issue by CaptainOfTheDirt** [jagrosh/MusicBot#891]
Would you be able to add the ability to seek within a song?
e.g. "!seek 1:00" which would make the bot skip to that point on the song.

Alternatively, would someone be able to tell me how to do this if it's already a feature?
I can't seem to find it anywhere.

Thanks!

**Comment by jagrosh** [comment]
#469

**Comment by CaptainOfTheDirt** [comment]
saw someone else had requested this, they just didn't use the word "seek" which is what I searched for, my bad
