### ISSUE TITLE
[Bug Report] WAV audio with 24-bit sample size fails to play

### ISSUE THREAD

**Issue by Kidyeon** [jagrosh/MusicBot#896]
### Bug Description

When attempting to play a file that is 24-bits per sample, the player spits out an <unknown filetype> error, and in the console it references it being a lavaplayer issue.

### Steps to Reproduce

1. Create a playlist with local 24-bit files.
2. Attempt to play them.
3. Bot spits out error:
![image](https://user-images.githubusercontent.com/15699373/134295967-394eeb82-1ea9-4344-9d81-5a81448bf86f.png)

### Expected Result

I simply expected the music to play alongside the other songs in my playlist. I didn't expect that having a higher-quality file would be an issue.

### Debug Output

```shell
System Properties:
  java.version = 17
  java.vm.name = Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.version = 17
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = 17+35-LTS-2724
  java.specification.version = 17
  os.arch = amd64
  os.name = Windows 10

JMusicBot Information:
  Version = 0.3.5
  Owner = 97392010037563392
  Prefix = ~
  AltPrefix = null
  MaxSeconds = 7200
  NPImages = false
  SongInStatus = false
  StayInChannel = false
  UseEval = false
  UpdateAlerts = true

Dependency Information:
  JDA Version = 4.3.0_312
  JDA-Utilities Version = 3.0.5
  Lavaplayer Version = 1.3.78

Runtime Information:
  Total Memory = 56
  Used Memory = 18

Discord Information:
  ID = 887759291006717972
  Guilds = 1
  Users = 5
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
Whoops, changed the title about the same time you did. Race condition in real life!

**Comment by Kidyeon** [comment]
Hahaha, thanks for being on top of the title then!

**Comment by Sanduhr32** [comment]
Donking Lavaplayer

**Comment by varneyc** [comment]
Any resolution found for this? Having same issue with latest version of the bot.

**Comment by MichailiK** [comment]
A [fix](https://github.com/lavalink-devs/lavaplayer/commit/701df404d9374d0f0d40804fce14ec615965b2c2) has been pushed by lavaplayer (the library we use for playing back audio.) We'll hopefully ship the fix in the next JMusicBot update.
