### ISSUE TITLE
A command like, @bot invite and then bot DMs it's invite link so that people can add it to their server!

### ISSUE THREAD

**Issue by DarkSlayer25** [jagrosh/MusicBot#908]
### Is your feature request related to a problem? Please describe.

Nope

### What is your ideal solution to the problem?

Just make a command `prefix invite` and then it DMs it's invite link

### How would this feature be used?

1. It would help in people inviting the bot!

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
Make the bot public & the `about` command will reveal an invite link.
