### ISSUE TITLE
Song title in Playing Status Message not working

### ISSUE THREAD

**Issue by cacamarena42** [jagrosh/MusicBot#91]
It just says "Type /help" when it's playing a song and not the song's title

**Comment by jagrosh** [comment]
Can you confirm a few things for me:
- You correctly set `songinstatus=true` in your config
- You uncommented the line (removed the // at the beginning)
- The bot is only playing music on one server

**Comment by cacamarena42** [comment]
Oh...I don't know how I didn't see the // at the beginning. Thank you!

**Comment by cacamarena42** [comment]
Some what unrelated, but I have a question. How do you make it the channel topic display what's currently being played?

**Comment by Brramble** [comment]
Make sure the bot has permission to edit the channel and set text channel
to that channel.

**Comment by cacamarena42** [comment]
@Brramble Huh, just tried it and it didn't seem to work. Also the 4 reaction buttons for the queue doesn't show up. :(

**Comment by cacamarena42** [comment]
Thanks guys!

**Comment by cacamarena42** [comment]
Last question, Is there a way to make it so that ONLY I can change the volume, but the dj's can do all of the other dj commands?
