### ISSUE TITLE
Doesn't show progress bar in the channel topic?

### ISSUE THREAD

**Issue by cacamarena42** [jagrosh/MusicBot#92]
I've allowed the bot to have full permissions for the text channel. Is this a bug?
![capture](https://user-images.githubusercontent.com/25369528/32025662-ce09a5f2-b9a6-11e7-84b8-68c946cab8fb.JPG)
![capture2](https://user-images.githubusercontent.com/25369528/32025673-d3926a54-b9a6-11e7-8247-90560d0665d8.JPG)

Shows up when using the now playing command.

**Comment by jagrosh** [comment]
There's no bug in what you've shown

**Comment by cacamarena42** [comment]
How so? Because in the example it shows it in there.
![687474703a2f2f692e696d6775722e636f6d2f677844646c524c2e706e67](https://user-images.githubusercontent.com/25369528/32025961-bb2a7da2-b9a7-11e7-83e0-e3f8d2135525.png)

**Comment by jagrosh** [comment]
That example is a bit old, the status bar in the topic has been removed due to ratelimit issues

**Comment by cacamarena42** [comment]
Oh, ok. Quick question as well. Is it possible to change what commands the DJ can use? I don't really want them to control the volume. I want it so that only I can change the volume. Is there a way I can implement this?

**Comment by jagrosh** [comment]
No, sorry, you cannot change which commands are in which category.

**Comment by cacamarena42** [comment]
Ok :( ty for the quick responses!

**Comment by cacamarena42** [comment]
Could this be a suggested feature?

**Comment by jagrosh** [comment]
I added it to the suggested features list

**Comment by hakufu** [comment]
@jagrosh Slightly off topic but could you add an option in the config to disable it updating the channel topic but retaining it's playing status in game? It's pretty spammy in the audit logs...

**Comment by jagrosh** [comment]
It won't be an option in the config, because you can just not give the bot permissions to edit the channel.

**Comment by hakufu** [comment]
Ah, alright that worked man. Should have thought of that sooner lol. Thanks.
