### ISSUE TITLE
[Feature Request] Add Youtube api key support (avoid rate limits)

### ISSUE THREAD

**Issue by AndyIshereBoi** [jagrosh/MusicBot#923]
### Is your feature request related to a problem? Please describe.

getting rate limtied by youtube is annoying.

### What is your ideal solution to the problem?

i propose you make it so that a youtube api key is optional, to avoid rate limiting.

### How would this feature be used?

1. add a optional setting to the config to use api key or not
2. will use it or not depending on what the user said
3. will not be rate limited as it uses the offical api if the api key is used

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
[Features requiring API keys will never be added](https://jmusicbot.com/things-that-wont-be-added#features-requiring-additional-api-keys). Additionally, none of the official YouTube APIs [allow you to download YouTube videos](https://stackoverflow.com/a/8081778). Even if it did, the YouTube (Data) API has [a quota system](https://developers.google.com/youtube/v3/guides/quota_and_compliance_audits) to limit your usage.
