### ISSUE TITLE
Hosting with Heroku

### ISSUE THREAD

**Issue by 2UNIEK** [jagrosh/MusicBot#93]
Was curious if there's a certain method to go about hosting the bot with Heroku. I already have one bot set up with JavaScript but not sure how to go about hosting this one with the .jar executable.

**Comment by jagrosh** [comment]
Heroku is designed for reactive apps, not things like Discord bots. Even if you managed to run it, the quality would likely be abysmal. I would recommend paying for a proper VPS; you can run around 2-4 JMusicBots (assuming standard, private usage) on a single $3.50/mo 2GB VPS from OVH.

**Comment by 2UNIEK** [comment]
That's seems more than suitable. Thank you very much!

**Comment by IsaacHasPrettyFuckingRadSocks** [comment]
Ok so I got the bot up and working, and it responds to every command, only problem is, the music just does not work, and the setgame command doesn't work, but the help command does. Everything worked fine, and this all started happening like after I put it on the Heroku vps

**Comment by jagrosh** [comment]
> 
> 
> Heroku is designed for reactive apps, not things like Discord bots. Even if you managed to run it, the quality would likely be abysmal. I would recommend paying for a proper VPS; you can run around 2-4 JMusicBots (assuming standard, private usage) on a single $3.50/mo 2GB VPS from OVH.
