### ISSUE TITLE
WTF is this ?

### ISSUE THREAD

**Issue by SoarCheats** [jagrosh/MusicBot#944]
### Bug Description

Adobe-KYS is the name of the bot it uses the jmusicbot extension ..
![wtf](https://user-images.githubusercontent.com/70775273/135764877-e841e7e0-a816-4bf5-936c-8cc9ae86db24.PNG)
.?

### Steps to Reproduce

it happned this morning i was asleep

### Expected Result

what is this and why

### Debug Output

```shell
dont know
```

### Additional Info

blawblaw

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
JMusicBot has no code to perform such behavior. You may have leaked your bot's token somewhere. Reset your token in the [Discord Developers Portal](https://discord.dev) to reset your bot's token.

**Comment by MichailiK** [comment]
To be fair, I would expect someone with "Cheat" in their name to leak their token or otherwise get hacked. 😁

**Comment by SoarCheats** [comment]
i havent leaked any token i just started the bot today to test it and it started speaking ?

**Comment by MichailiK** [comment]
**JMusicBot has no code to suddenly go sentient and "speak by itself"**. Just like how you can login on Discord with multiple devices (desktop, web, phone etc.) you can also login to a bot multiple times with the same token. These messages are **not sent by JMusicBot, they _cannot_ be sent with JMusicBot, as it has not been programmed to send these messages.** This can be proven [by searching "Fuck you"](https://github.com/jagrosh/MusicBot/search?q=Fuck+you&type=code) in [JMusicBot's source code](https://github.com/jagrosh/MusicBot/tree/master/src):

![image](https://user-images.githubusercontent.com/39029839/135769284-f3bb9610-e495-455d-a7f1-1b203f0f25a6.png)

Your bot's token has been compromised, whether you know it or not. You should reset your bot token's now and make sure to keep it secure.
