### ISSUE TITLE
[Feature Request] GraalVM (or different engine) for eval in Java 15+

### ISSUE THREAD

**Issue by MichailiK** [jagrosh/MusicBot#945]
### Is your feature request related to a problem? Please describe.

The eval command is broken in Java 15 and above, as [Nashorn has been removed since Java 15](https://openjdk.java.net/jeps/372), which the MusicBot relies on.

Aside from powerusers, the eval command is currently the only way to list & leave guilds (servers).

### What is your ideal solution to the problem?

Add a new JavaScript Engine as a dependency, for example Graal. I haven't looked much into Graal. I'm not sure if it supports bindings or if it works in Java 8.

### How would this feature be used?

N/A

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
what about changing the `eval = ` part of the config to a string, and let users who know what they are doing to specify their own interpreter
