### ISSUE TITLE
Audio Chopy?

### ISSUE THREAD

**Issue by mads4444** [jagrosh/MusicBot#95]
noticed after a while, that there where small cuts and jumps in the music coming from the bot.

**Comment by Zahh2615** [comment]
Sorry for a late response (I am not the owner of JMusicBot).

There is a easy fix to the problem if this audio problem is still persisting.

1) Run the bot from the command bar.
This can be done by opening Command Prompt, and going to the bot directory, and typing this:
java -Xmx(put a number here, preferably half or quarter of your RAM)G -jar JMusicBot-0.1.0.jar -nogui

2) Set the bot to high affinity by opening Task Manager, finding the Java instance, right clicking it, hovering over set affinity, and setting it to high.

3) Change your voice region to the closest available area to guarantee that you won't have much skips in the future.


This won't kill every single problem. You'll have skips still, but it will not be as frequent. Let the bot run for a long while, and the skips will happen nearly never.

I hope I fixed your problem!

-Zahh

**Comment by jagrosh** [comment]
I am waiting on a pull request in another library for a small fix with some youtube videos, and then I'll be pushing version 0.1.1 which will hopefully fix some generic quality issues

**Comment by Zahh2615** [comment]
Awesome.

**Comment by jagrosh** [comment]
Version 0.1.1 is released, hopefully this fixes any choppiness you might have been experiencing
