### ISSUE TITLE
Suggestion: Translations

### ISSUE THREAD

**Issue by SupremeNL** [jagrosh/MusicBot#96]
Hello There,

It would be nice if there is a translation file (from a couple of languages*), that you configure what language youre bot need to use.

(*English, French, Dutch, German, Spanish, Swedish, Russian, and more languages that people uses)

Greetings, Stefan

**Comment by jagrosh** [comment]
This is already on the [planned features list](https://github.com/jagrosh/MusicBot/projects/1)
