### ISSUE TITLE
More music sources

### ISSUE THREAD

**Issue by rainbowjose** [jagrosh/MusicBot#97]
Plain url, vimeo, spotify?

**Comment by jagrosh** [comment]
Plain URLs and vimeo are already supported, and spotify is not possible to support because it requires an account. See the [lavaplayer repo](https://github.com/sedmelluq/lavaplayer/tree/master/main/src/main/java/com/sedmelluq/discord/lavaplayer/source) for available supported sources.

**Comment by jagrosh** [comment]
Also, you can use this method to convert spotify playlists to youtube playlists: https://www.youtube.com/watch?v=KAYXAH-097o

**Comment by rainbowjose** [comment]
You are best. Simply.

**Comment by rainbowjose** [comment]
Also im checkeng a lot of bots, but your is the best bot. Tons of shit with tons of stars on github, but your bot is fucking awesome.
