### ISSUE TITLE
[Feature Request] Leave channel with a timeout when nothing is played

### ISSUE THREAD

**Issue by SPEED0U** [jagrosh/MusicBot#970]
### Is your feature request related to a problem? Please describe.

When "stayinchannel = false" there should be another parameter called like "leavechanneltimeout = 360" to apply a delay when the bot plays nothing before leaving.

### What is your ideal solution to the problem?

A parameter to set a timeout in second to keep the bot in the channel for (as example) 5 minutes when nothing is played but there is someone in channel so it doesn't live directly, but if after 5 minutes nothing is played then it can leave.

### How would this feature be used?

Just a parameter as I described earlier would be enough.

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
It has been discussed that this shouldn't be implemented, and that `stayinchannel` should be left to false if you are concerned about bandwidth.
