### ISSUE TITLE
[Bug Report] Setskip command not working

### ISSUE THREAD

**Issue by Zhhi** [jagrosh/MusicBot#971]
### Bug Description

The setskip command did not give any response.
Checked serversettings.json file, no additional info was found.

### Steps to Reproduce

Type command like usual in discord chat whit "prefix"setskip "value must be between 0 and 100"

### Expected Result

Per-server skip percentage setting successfully

### Debug Output

```shell
N/A
```

### Additional Info

The bot successfully playing song in voice channel and responding to play and ping command so I don't think this bug is related to permission issue. 

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by MichailiK** [comment]
Fixed as of version 0.3.7
