### ISSUE TITLE
[Bug Report] Bot server muted automatically

### ISSUE THREAD

**Issue by Tubboge** [jagrosh/MusicBot#977]
### Bug Description

The bot is server muted when joining. 

### Steps to Reproduce

1. Get the bot to play music

### Expected Result

I expected the bot not to be server-muted.

### Debug Output

```shell
OS - Windows 10 Pro Version 21H1 (OS Build 19403.1263)
JMB version - 0.3.6
```

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by jagrosh** [comment]
The bot does not server mute itself; you need to fix the permissions in your server.
