### ISSUE TITLE
[Feature Request] Make the update nag a little less naggy

### ISSUE THREAD

**Issue by matthewstrasiotto** [jagrosh/MusicBot#983]
### Is your feature request related to a problem? Please describe.

The update nag is a bit too frequesnt - It's been daily for a week. 

### What is your ideal solution to the problem?

Making it weekly or a command to tell it to chill a bit would be dope.

### How would this feature be used?

Maybe the update nag tells you can react with a thumbs down to its message, and if you do, it snoozes for a few weeks unless the update is security related.

### Additional Info

Ironically I will need to update my bot in order to get this feature.

I lied when I ticked "I am running the latest version of the bot" because by definition this cannot be true.

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by JetCrooked** [comment]
> You can stop update alerts by:
> 
> 1. Setting `updatealerts` to false in the configuration, which is not recommended.
> 2. Updating to the latest release
or 3. blocking the bot :^)
